### ISSUE TITLE
help!  tapo C500 camera, two way audio doesn't work, any idea how to fix it?

### ISSUE THREAD

**Issue by goblueapple** [koush/scrypted#1015]
[HomeKit]: motion fragment #14 sent. size: 122146
[HomeKit]: motion fragment #15 sent. size: 163633
[HomeKit]: motion fragment #16 sent. size: 182338
[HomeKit]: motion fragment #17 sent. size: 168632
[HomeKit]: motion fragment #18 sent. size: 160727
[HomeKit]: motion fragment #19 sent. size: 157425
[Video Analysis Plugin]: Resuming motion processing after active motion timeout.
[Rebroadcast Plugin]: Selected stream minorStream
[Rebroadcast Plugin]: minorStream prebuffer session started
stream url rtsp://192.168.2.242:554/stream2
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://192.168.2.242:554/stream2 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: Date: Sat, Aug 12 2023 18:33:09 GMT
[Rebroadcast Plugin]: Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.2.242:554/stream2 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: Date: Sat, Aug 12 2023 18:33:09 GMT
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="TP-LINK IP-Camera"
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="TP-LINK IP-Camera", nonce="[ sorry, i deleted this ]"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.2.242:554/stream2 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic [sorry, i deleted this]
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: Date: Sat, Aug 12 2023 18:33:09 GMT
[Rebroadcast Plugin]: Content-Base: rtsp://192.168.2.242:554/stream2/
[Rebroadcast Plugin]: Content-Type: application/sdp
[Rebroadcast Plugin]: Content-Length: 410
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: sdp v=0
[Rebroadcast Plugin]: o=- 14665860 31787219 1 IN IP4 192.168.2.242
[Rebroadcast Plugin]: s=Session streamed by "TP-LINK RTSP Server"
[Rebroadcast Plugin]: t=0 0
[Rebroadcast Plugin]: m=video 0 RTP/AVP 96
[Rebroadcast Plugin]: c=IN IP4 0.0.0.0
[Rebroadcast Plugin]: b=AS:4096
[Rebroadcast Plugin]: a=range:npt=0-
[Rebroadcast Plugin]: a=control:track1
[Rebroadcast Plugin]: a=rtpmap:96 H264/90000
[Rebroadcast Plugin]: a=fmtp:96 packetization-mode=1; profile-level-id=64001F; sprop-parameter-sets=[sorry, i deleted this]
[Rebroadcast Plugin]: m=audio 0 RTP/AVP 8
[Rebroadcast Plugin]: a=rtpmap:8 PCMA/8000
[Rebroadcast Plugin]: a=control:track2
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  SETUP rtsp://192.168.2.242:554/stream2/track1 RTSP/1.0
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=0-1
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic [sorry, i deleted this]
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: Date: Sat, Aug 12 2023 18:33:09 GMT
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=0-1
[Rebroadcast Plugin]: Session: 04DE85FA;timeout=15
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  SETUP rtsp://192.168.2.242:554/stream2/track2 RTSP/1.0
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=2-3
[Rebroadcast Plugin]: CSeq: 4
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic [sorry, i deleted this]
[Rebroadcast Plugin]: Session: 04DE85FA
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 4
[Rebroadcast Plugin]: Date: Sat, Aug 12 2023 18:33:09 GMT
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=2-3
[Rebroadcast Plugin]: Session: 04DE85FA;timeout=15
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: parsed sdp sps { width: 640, height: 360 }
[Rebroadcast Plugin]: Audio codec plugin reported vs detected mismatch g711 pcm_alaw
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  PLAY rtsp://192.168.2.242:554/stream2/ RTSP/1.0
[Rebroadcast Plugin]: Range: npt=0.000-
[Rebroadcast Plugin]: CSeq: 5
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic [sorry, i deleted this]
[Rebroadcast Plugin]: Session: 04DE85FA
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 5
[Rebroadcast Plugin]: Date: Sat, Aug 12 2023 18:33:09 GMT
[Rebroadcast Plugin]: Range: npt=0.000-
[Rebroadcast Plugin]: Session: 04DE85FA
[Rebroadcast Plugin]: RTP-Info: url=rtsp://192.168.2.242:554/stream2/track1;seq=1;rtptime=0,url=rtsp://192.168.2.242:554/stream2/track2;seq=1;rtptime=0
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: sending prebuffer 4000
[Rebroadcast Plugin]: parsed bitstream sps { width: 640, height: 360 }
[Video Analysis Plugin]: -hide_banner -analyzeduration 0 -probesize 500000 -reorder_queue_size 0 -rtsp_transport tcp -f rtsp -i rtsp:[REDACTED] -vcodec pam -pix_fmt rgb24 -vf fps=4,scale=640:360 -f image2pipe pipe:3
[Rebroadcast Plugin]: minorStream active rebroadcast clients: 1
[HomeKit]: motion fragment #20 sent. size: 142342
[HomeKit]: two way audio failed S [Error]: timeout waiting for client
[HomeKit]:     at Timeout._onTimeout (/@scrypted/homekit/main.nodejs.js:2:1022574)
[HomeKit]:     at listOnTimeout (node:internal/timers:569:17)
[HomeKit]:     at processTimers (node:internal/timers:512:7)
[Video Analysis Plugin]: Guessed Channel Layout for Input Stream #0.1 : mono

**Comment by rizlagatwick** [comment]
I'm having the same problem with TP C320WS:
scrypted             | [Tapo C320WS] received first audio packet
scrypted             |
scrypted             | unhandledRejection n [Error]:
scrypted             |     at PassThrough.o (/common/src/read-stream.ts:96:14)
scrypted             |     at PassThrough.emit (node:events:514:28)
scrypted             |     at PassThrough.emit (node:domain:489:12)
scrypted             |     at endReadableNT (node:internal/streams/readable:1359:12)
scrypted             |     at processTicksAndRejections (node:internal/process/task_queues:82:21)
scrypted             |
scrypted             | strema closed
scrypted             |
scrypted             | e Tapo Camera Plugin unhandledRejection Error
scrypted             | [Tapo C320WS] two way audio failed S [Error]: timeout waiting for client
scrypted             |     at Timeout._onTimeout (/@scrypted/homekit/main.nodejs.js:2:1022574)
scrypted             |     at listOnTimeout (node:internal/timers:569:17)
scrypted             |     at processTimers (node:internal/timers:512:7)
scrypted             |

**Comment by joe9000kimo** [comment]
Same problem with TP C320WS,too.

**Comment by codyc1515** [comment]
I had this issue. Reloaded ONVIF plug-in and working again. So, something _is_ broken somewhere.

**Comment by bmwcar** [comment]
as i know , all TAPO camera does not support 2 way audio in HSV

**Comment by taikun114** [comment]
Although the error is a little different, but I am having the same problem.

```
[HomeKit]: two way audio failed E [Error]: timeout waiting for client
[HomeKit]:     at Timeout._onTimeout (/@scrypted/homekit/main.nodejs.js:2:995747)
[HomeKit]:     at listOnTimeout (node:internal/timers:569:17)
[HomeKit]:     at processTimers (node:internal/timers:512:7)
```

I am currently getting `two way audio failed E`, but sometimes I get `two way audio failed S` or `two way audio failed C`. But I don't know exactly what the difference is between these.

I have a C500 and a C200 and both have the exact same problem, two-way audio does not work.
I have read somewhere that if the cloud password contains symbols it will not work, so I tried changing it to a password that does not contain symbols, but this did not change either.
I have also tried restarting the ONVIF plugin, the HomeKit plugin, and various other plugins, as well as restarting the Scrypted server itself, but two-way audio has not worked even once since I started using Scrypted.

Other than the two-way audio, everything else has worked flawlessly so far.

**Comment by ronnieSVK** [comment]
Sadly the same issue with C500. Even if "Two Way Audio" plugin for Tapo is installed and configured with local pass, everything enabled, Apple Home shows the Mic button and "it looks it works", sadly no sound output from the cameras :( Can i do anything else to make it work ? Thank you !

**Comment by koush** [comment]
Can you verify the recent update fixed this

**Comment by fnkr** [comment]
Works fine now on my Tapo C125 using Scrypted  v0.102.0 (was not working with v0.97.0). Thanks!

**Comment by ronnieSVK** [comment]
Hi @koush !
Hereby i can also confirm, that Two Way Audio via HKSV works great now ! (2xTapo C200, HomeAssistant addon).

Thanks for you continous great work !
