### ISSUE TITLE
Dahua VTO2111D-WP Two-way audio error

### ISSUE THREAD

**Issue by App-Plant** [koush/scrypted#1048]
Two-way audio won't work on Dahua VTO2111D-WP. 
Software version: 2020-03-11 V4.300.0000000.7.R
MCU version: 2016-05-12

VTO Log:

`rtsp incoming message
 RTSP/1.0 401 Unauthorized
CSeq: 1
WWW-Authenticate: Digest realm="Login to 3J02B2APAN00023", nonce="e8a81309e45181a5d01819a6a1e4f811"

[HomeKit]: intercom failed to start RPCResultError: auth failed
[HomeKit]:     at t.RtspClient.request (/common/src/rtsp-server.ts:643:23)
[HomeKit]:     at process.ret (node:internal/process/task_queues:95:5)
[HomeKit]:     at t.RtspClient.console (/common/src/rtsp-server.ts:658:15)
[HomeKit]:     at t.OnvifIntercom.intercomClient [as checkIntercom] (/onvif/src/onvif-intercom.ts:86:46)
[HomeKit]:     at t.OnvifIntercom.startIntercom (/onvif/src/onvif-intercom.ts:107:35)
[HomeKit]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:747:37)
[HomeKit]: @scrypted/amcrest:host
[HomeKit]: host:@scrypted/homekit {
[HomeKit]:   cause: undefined
[HomeKit]: }
[HomeKit]: two way audio failed S [Error]: timeout waiting for client
[HomeKit]:     at Timeout._onTimeout (/@scrypted/homekit/main.nodejs.js:2:1022574)
[HomeKit]:     at listOnTimeout (node:internal/timers:569:17)
[HomeKit]:     at processTimers (node:internal/timers:512:7)
[HomeKit]: two way audio failed S [Error]: timeout waiting for client
[HomeKit]:     at Timeout._onTimeout (/@scrypted/homekit/main.nodejs.js:2:1022574)
[HomeKit]:     at listOnTimeout (node:internal/timers:569:17)
[HomeKit]:     at processTimers (node:internal/timers:512:7)
[HomeKit]: handleStreamRequest { sessionID: '7a49c01a-4a39-49dd-8723-489d5455d578', type: 'stop' }
[HomeKit]: streaming session killed, duration: 38s
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 0
[HomeKit]: ffmpeg exited
debug event:
 --myboundary
Content-Type: text/plain
Content-Length:74

Code=SIPRegisterResult;action=Pulse;index=0;data={
   "Success" : false
}

debug event:
 --myboundary
Content-Type: text/plain
Content-Length:74

Code=SIPRegisterResult;action=Pulse;index=0;data={
   "Success" : false
}
`

Plugin log:
`rtsp outgoing message
 OPTIONS rtsp://192.168.1.111:554/cam/realmonitor?channel=1&subtype=0&proto=Onvif RTSP/1.0
CSeq: 1
User-Agent: Scrypted
Authorization: Digest username="admin", realm="Login to 3J02B2APAN00023", nonce="1c4f30498089bdeb322b2155207f369a", uri="rtsp://192.168.1.111:554/cam/realmonitor?channel=1&subtype=0&proto=Onvif", algorithm="MD5", response="371b112ef123eb8d342524821778717a"

rtsp incoming message
 RTSP/1.0 401 Unauthorized
CSeq: 1
WWW-Authenticate: Digest realm="Login to 3J02B2APAN00023", nonce="1c4f30498089bdeb322b2155207f369a"

debug event:
 --myboundary
Content-Type: text/plain
Content-Length:74

Code=SIPRegisterResult;action=Pulse;index=0;data={
   "Success" : false
}`

**Comment by App-Plant** [comment]
```
rtsp outgoing message
 OPTIONS rtsp://192.168.1.111:554/cam/realmonitor?channel=1&subtype=0&proto=Onvif RTSP/1.0
CSeq: 1
User-Agent: Scrypted
Authorization: Digest username="admin", realm="Login to 3J02B2APAN00023", nonce="4319bd7d36c7a242632d8f0cdfc1d158", uri="rtsp://192.168.1.111:554/cam/realmonitor?channel=1&subtype=0&proto=Onvif", algorithm="MD5", response="76cab2f9ec6eba141593e254035ee20e"



rtsp incoming message
 RTSP/1.0 401 Unauthorized
CSeq: 1
WWW-Authenticate: Digest realm="Login to 3J02B2APAN00023", nonce="4319bd7d36c7a242632d8f0cdfc1d158"

[HomeKit]: intercom failed to start RPCResultError: auth failed
[HomeKit]:     at t.RtspClient.request (/common/src/rtsp-server.ts:643:23)
[HomeKit]:     at process.ret (node:internal/process/task_queues:95:5)
[HomeKit]:     at t.RtspClient.console (/common/src/rtsp-server.ts:658:15)
[HomeKit]:     at t.OnvifIntercom.intercomClient [as checkIntercom] (/onvif/src/onvif-intercom.ts:86:46)
[HomeKit]:     at t.OnvifIntercom.startIntercom (/onvif/src/onvif-intercom.ts:107:35)
[HomeKit]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:747:37)
[HomeKit]: @scrypted/amcrest:host
[HomeKit]: host:@scrypted/homekit {
[HomeKit]:   cause: undefined
[HomeKit]: }
[HomeKit]: handleStreamRequest { sessionID: '53c25fef-dd3d-4e28-a74d-a5974375f73c', type: 'stop' }
[HomeKit]: streaming session killed, duration: 14s
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 0
[HomeKit]: ffmpeg exited
debug event:
 --myboundary
Content-Type: text/plain
Content-Length:108

Code=SIPRegisterResult;action=Pulse;index=0;data={
   "Date" : "2023-08-27 15:00:17",
   "Success" : true
}
```
