### ISSUE TITLE
ONVIF SOAP Fault

### ISSUE THREAD

**Issue by Greminn** [koush/scrypted#105]
Running on Synology docker with latest image, connected to Reolink camera via ONVIF:

2022-01-08 02:29:57	stdout	listen loop error, restarting in 10 seconds Error: ONVIF SOAP Fault: {"value":"SOAP-ENV:Sender"}
2022-01-08 02:29:57	stdout	
2022-01-08 02:29:57	stdout	    at o.parseString (/node_modules/xml2js/lib/parser.js:323:31)
2022-01-08 02:29:57	stdout	    at o.write (/node_modules/sax/lib/sax.js:1436:13)
2022-01-08 02:29:57	stdout	    at closeTag (/node_modules/sax/lib/sax.js:889:7)
2022-01-08 02:29:57	stdout	    at emitNode (/node_modules/sax/lib/sax.js:629:5)
2022-01-08 02:29:57	stdout	    at emit (/node_modules/sax/lib/sax.js:624:29)
2022-01-08 02:29:57	stdout	    at o.event [as onclosetag] (/node_modules/xml2js/lib/parser.js:262:26)
2022-01-08 02:29:57	stdout	    at o.emit (node:domain:475:12)
2022-01-08 02:29:57	stdout	    at o.emit (node:events:390:28)
2022-01-08 02:29:57	stdout	    at o.<anonymous> (/node_modules/xml2js/lib/parser.js:304:18)
2022-01-08 02:29:57	stdout	    at cb (/node_modules/onvif/lib/utils.js:101:13)
2022-01-08 02:29:57	stdout	createSubscription error Error: ONVIF SOAP Fault: {"value":"SOAP-ENV:Sender"}
2022-01-08 02:29:57	stdout	
2022-01-08 02:29:57	stdout	    at o.parseString (/node_modules/xml2js/lib/parser.js:323:31)
2022-01-08 02:29:57	stdout	    at o.write (/node_modules/sax/lib/sax.js:1436:13)
2022-01-08 02:29:57	stdout	    at closeTag (/node_modules/sax/lib/sax.js:889:7)
2022-01-08 02:29:57	stdout	    at emitNode (/node_modules/sax/lib/sax.js:629:5)
2022-01-08 02:29:57	stdout	    at emit (/node_modules/sax/lib/sax.js:624:29)
2022-01-08 02:29:57	stdout	    at o.event [as onclosetag] (/node_modules/xml2js/lib/parser.js:262:26)
2022-01-08 02:29:57	stdout	    at o.emit (node:domain:475:12)
2022-01-08 02:29:57	stdout	    at o.emit (node:events:390:28)
2022-01-08 02:29:57	stdout	    at o.<anonymous> (/node_modules/xml2js/lib/parser.js:304:18)
2022-01-08 02:29:57	stdout	    at cb (/node_modules/onvif/lib/utils.js:101:13)

**Comment by 3ne** [comment]
Make sure the ONVIF port is the same as in the camera. You can find it in advanced in the network option of the camera
![Snag_10b54c67](https://user-images.githubusercontent.com/4566763/148847403-79a46a1a-9521-4399-aee7-035227d24a9d.png)
![Snag_10b55a42](https://user-images.githubusercontent.com/4566763/148847410-f1f28516-4af3-489c-92dd-6471c4364482.png)
.

**Comment by hsshah** [comment]
@Greminn  I am getting the same error (using Reolink NVR via ONVIF). Did you find a solution?

**Comment by Greminn** [comment]
> @Greminn I am getting the same error (using Reolink NVR via ONVIF). Did you find a solution?

Actually, i ended up re-building my docker image as moved it to another host and have not had the issue post this. Note i also had to change my camera as my 822A only did H.265, which may have produced this error as well? Sorry i cannot be of any further assistance?

**Comment by Dima-Kal** [comment]
Also seeing these errors with Reolink camera, although looks like its working, any solution for this?
