### ISSUE TITLE
Issue loading Python codecs 3.10

### ISSUE THREAD

**Issue by wild-a** [koush/scrypted#1099]
System: Raspberry Pi 4b, running on Docker

av/logging.pyx:351:28: Cannot assign type 'void (void *, int, const char *, va_list) except * nogil' to 'av_log_callback'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, int, const char *, va_list) except * nogil'.
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-3p4ru9kp/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-3p4ru9kp/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-3p4ru9kp/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-3p4ru9kp/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 157, in <module>
        File "/tmp/pip-build-env-3p4ru9kp/overlay/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-3p4ru9kp/overlay/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: av/logging.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
pip install result 1
plugin start/fork failed
Traceback (most recent call last):
  File "/server/node_modules/@scrypted/server/python/plugin_remote.py", line 380, in loadZip
    return await self.loadZipWrapped(packageJson, zipData, options)
  File "/server/node_modules/@scrypted/server/python/plugin_remote.py", line 634, in loadZipWrapped
    raise Exception('non-zero result from pip %s' % result)
Exception: non-zero result from pip 1

**Comment by bjia56** [comment]
Your raspbian is running in mixed 32/64 bit which will cause issues with python. See #678

**Comment by wild-a** [comment]
> Your raspbian is running in mixed 32/64 bit which will cause issues with python. See #678 

Would you mind sharing what would cause that to happen? I bought a brand new RPi4, and only installed the 32-bit OS. Is it possible one of the codecs I installed was 64-bit in Scrypted?

**Comment by bjia56** [comment]
If I recall, some upgrades on 32-bit raspbian may switch the kernel to run in 64-bit without altering the filesystem contents, so 32-bit programs do not get updated. If this is a new system and all you're doing is running Scrypted on it, I suggest wiping the SD card and reinstalling 64bit raspbian, it will save you a lot of headache in the future.
