### ISSUE TITLE
Unable to view live stream in Scrypted or Apple Home for battery cameras (cocoa_camera) but can on indoor cam

### ISSUE THREAD

**Issue by ccanalia82** [koush/scrypted#1111]
Hello, this is the first time I am posting here but I have noticed within the last 2 weeks, suddenly none of my ring coco_camera devices do not allow streaming.  They throw an error in the console:

```
[Patio Cam]
[Patio Cam] rtsp outgoing message
 TEARDOWN rtsp://127.0.0.1:37093 RTSP/1.0
CSeq: 1
User-Agent: Scrypted


[Patio Cam] SIP prebuffer session ended with error s [Error]
    at Socket.o (/@scrypted/prebuffer-mixin/main.nodejs.js:1:81646)
    at Socket.emit (node:events:526:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Patio Cam]
[Patio Cam] client error Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (node:net:542:14)
    at E (/@scrypted/prebuffer-mixin/main.nodejs.js:1:84152)
    at t.RtspClient.write (/@scrypted/prebuffer-mixin/main.nodejs.js:1:86974)
    at t.RtspClient.writeRequest (/@scrypted/prebuffer-mixin/main.nodejs.js:1:88142)
    at t.RtspClient.writeTeardown (/@scrypted/prebuffer-mixin/main.nodejs.js:1:93362)
    at t.RtspClient.safeTeardown (/@scrypted/prebuffer-mixin/main.nodejs.js:1:87662)
    at g (/@scrypted/prebuffer-mixin/main.nodejs.js:1:142667)
    at t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:145856)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'EPIPE'
}
[Patio Cam] rebroadcast error Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (node:net:542:14)
    at E (/@scrypted/prebuffer-mixin/main.nodejs.js:1:84152)
    at t.RtspClient.write (/@scrypted/prebuffer-mixin/main.nodejs.js:1:86974)
    at t.RtspClient.writeRequest (/@scrypted/prebuffer-mixin/main.nodejs.js:1:88142)
    at t.RtspClient.writeTeardown (/@scrypted/prebuffer-mixin/main.nodejs.js:1:93362)
    at t.RtspClient.safeTeardown (/@scrypted/prebuffer-mixin/main.nodejs.js:1:87662)
    at g (/@scrypted/prebuffer-mixin/main.nodejs.js:1:142667)
    at t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:145856)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'EPIPE'
}
unhandledRejection s [Error]
    at Socket.o (/@scrypted/prebuffer-mixin/main.nodejs.js:1:81646)
    at Socket.emit (node:events:526:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Here's my indoor camera showing that everything loads fine.  

```
[Garage Cam]
[Garage Cam] sdp v=0
o=- 3747 461 IN IP4
s=-
c=IN IP4 127.0.0.1
t=0 0
m=audio 0 RTP/SAVPF 0
a=control:trackID=0
a=rtpmap:0 PCMU/8000
a=rtcp:51159 IN IP4 100.20.84.143
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:Xfh2vw8drTh/qv0XSatCyK34FEn/P02KcbjKsXsD
a=ptime:20
m=video 0 RTP/SAVPF 99
a=control:trackID=1
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42801F
a=rtcp:51132 IN IP4 100.20.84.143
a=rtcp-fb:99 nack
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:QZ7GgNVqfDnNLt0YKgKKkRCMp7ofXYQNjY+ZooW3
[Garage Cam] rtsp outgoing message
 SETUP rtsp://127.0.0.1:34933/trackID=0 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
CSeq: 2
User-Agent: Scrypted


[Garage Cam]
[Office Cam] Audio codec plugin reported vs detected mismatch pcm_mulaw pcm_ulaw
[Office Cam] H264 oddity detected.
[Garage Cam] rtsp incoming message
 RTSP/1.0 200 OK
Session: 96a6c5ee
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
CSeq: 2
[Garage Cam] Audio codec plugin reported vs detected mismatch pcm_mulaw pcm_ulaw
[Office Cam] sending prebuffer 4000
[Garage Cam]
[Garage Cam] rtsp outgoing message
 SETUP rtsp://127.0.0.1:34933/trackID=1 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=2-3
CSeq: 3
User-Agent: Scrypted
Session: 96a6c5ee


[Garage Cam]
[Garage Cam] rtsp incoming message
 RTSP/1.0 200 OK
Session: 96a6c5ee
Transport: RTP/AVP/TCP;unicast;interleaved=2-3
CSeq: 3
[Garage Cam]
[Garage Cam] refreshing media stream in 88247
[Garage Cam] rtsp outgoing message
 PLAY rtsp://127.0.0.1:34933 RTSP/1.0
Range: npt=0.000-
CSeq: 4
User-Agent: Scrypted
Session: 96a6c5ee


[Garage Cam]
[Garage Cam] rtsp incoming message
 RTSP/1.0 200 OK
RTP-Info: url=rtsp://127.0.0.1:34933/trackID=0,url=rtsp://127.0.0.1:34933/trackID=1
Range: npt=now-
Session: 96a6c5ee
CSeq: 4
[Garage Cam]
[Garage Cam] sending prebuffer 4000
[Garage Cam] H264 oddity detected.
```
I havent changed any of my settings, the cameras just stopped working.  I removed Ring/Homekit plugins and tried to load again, that did not fix the issue.  I also put fresh batteries in the cameras and that did not help either.  

Can you help with a fix on this?

**Comment by ccanalia82** [comment]
Forgot to mention that all snapshots load, its only when I tap into the camera in the Scrypted UI or HomeKit that I do not see the stream.  This happened within the last 1-2 weeks.  If I try to look at the streams on Ring app, everything works fine.

**Comment by nexuspcs** [comment]
Exact same issue for me with the Gen2 Doorbell
+1

**Comment by nexuspcs** [comment]
From what I've seen, its and issue on Ring's side, with their drop of support for a type of video encoding?
https://community.ring.com/t/location-to-toggle-legacy-video/210139
https://community.ring.com/t/location-to-toggle-legacy-video/210139/19 

There is an API available to transcode from the Ring servers I think (*from what I've read in the Scrypted Discord*), but no word if the developers plan to implement this...

**Comment by Meir-120** [comment]
Same with me Ring Video Doorbell Gen 4

**Comment by djgoku** [comment]
Just started to try out scrypted and I am getting a similar error as above but from unifi cameras. I currently am only using a G3 instant from unifi, and the G3 Flex have been offline for over a year, but they are still in the unifi UI just showing `offline`.
```
[UVC G3 Flex 4252]

[UVC G3 Flex 4252] rtsp incoming message
 RTSP/1.0 200 OK
CSeq: 0
Cache-Control: no-store
Date: Mon, 20 Nov 2023 01:36:04 UTC
Expires: Mon, 20 Nov 2023 01:36:04 UTC
Pragma: no-cache
Public: DESCRIBE, OPTIONS, PAUSE, PLAY, SETUP, TEARDOWN, ANNOUNCE, RECORD
Server: Unifi Protect (www.ui.com)

[UVC G3 Flex 4252]

[UVC G3 Flex 4252] rtsp outgoing message
 DESCRIBE rtsps://10.0.0.1:7441/null RTSP/1.0
Accept: application/sdp
CSeq: 1
User-Agent: Scrypted


[UVC G3 Flex 4252]

[UVC G3 Flex 4252] rtsp outgoing message
 TEARDOWN rtsps://10.0.0.1:7441/null RTSP/1.0
CSeq: 2
User-Agent: Scrypted



[UVC G3 Flex 4252] High prebuffer session ended with error s [Error]
    at TLSSocket.o (/@scrypted/prebuffer-mixin/main.nodejs.js:1:82229)
    at TLSSocket.emit (node:events:526:35)
    at TLSSocket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

[UVC G3 Flex 4252]

[UVC G3 Flex 4252] UVC G3 Flex 4252 restarting prebuffer session in 5 seconds
[UVC G3 Flex 4252] client error Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (node:net:542:14)
    at E (/@scrypted/prebuffer-mixin/main.nodejs.js:1:84735)
    at t.RtspClient.write (/@scrypted/prebuffer-mixin/main.nodejs.js:1:87557)
    at t.RtspClient.writeRequest (/@scrypted/prebuffer-mixin/main.nodejs.js:1:88725)
    at t.RtspClient.writeTeardown (/@scrypted/prebuffer-mixin/main.nodejs.js:1:93945)
    at t.RtspClient.safeTeardown (/@scrypted/prebuffer-mixin/main.nodejs.js:1:88245)
    at g (/@scrypted/prebuffer-mixin/main.nodejs.js:1:143787)
    at t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:146976)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'EPIPE'
}

[UVC G3 Flex 4252] rebroadcast error Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (node:net:542:14)
    at E (/@scrypted/prebuffer-mixin/main.nodejs.js:1:84735)
    at t.RtspClient.write (/@scrypted/prebuffer-mixin/main.nodejs.js:1:87557)
    at t.RtspClient.writeRequest (/@scrypted/prebuffer-mixin/main.nodejs.js:1:88725)
    at t.RtspClient.writeTeardown (/@scrypted/prebuffer-mixin/main.nodejs.js:1:93945)
    at t.RtspClient.safeTeardown (/@scrypted/prebuffer-mixin/main.nodejs.js:1:88245)
    at g (/@scrypted/prebuffer-mixin/main.nodejs.js:1:143787)
    at t.startRtspSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:146976)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'EPIPE'
}

unhandledRejection s [Error]
    at TLSSocket.o (/@scrypted/prebuffer-mixin/main.nodejs.js:1:82229)
    at TLSSocket.emit (node:events:526:35)
    at TLSSocket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by koush** [comment]
Ring h265 cams have been fixed.
