### ISSUE TITLE
Tuya Camera: Failed to capture stream

### ISSUE THREAD

**Issue by pergolafabio** [koush/scrypted#1140]
**Describe the bug**
Hi, i'm new to Scrypted, wanted to use it for my met Tuya Petfeeder with camera, so i installed scrypted, and enabled the Tuya plugin

**To Reproduce**
1. Installed 0.57.0 clean install
2. Installed tuya plugin 0.0.8
3. Provided nessary clientid/secret...
4. The plugin recognized my camera device, but i see snapshot failed? Below are the console logs

Maybe important, when i vision the IOT website from tuya, when i visit the API explorer, i'm also not able to retrieve an RTSP or HLS stream, the only command that scucceeds is getting the webrtc config

Is this plugin maybe not supported then?

**Screenshots**
![image](https://github.com/koush/scrypted/assets/43251136/7621b889-bf58-4815-9f72-883c37a33f5f)

**Desktop (please complete the following information):**
 - OS: debian, used the docker method to install

**Additional context**

```
linux x64 #1 SMP Debian 5.10.136-1 (2022-08-13)
server version: 0.57.0
plugin version: @scrypted/tuya 0.0.8
full
########################
10/17/2023, 11:32:38 AM
########################
[Rebroadcast Plugin]: prebuffer sessions starting in 5 seconds
[Rebroadcast Plugin]: prebuffer sessions releasing if started
[Rebroadcast Plugin]: prebuffer sessions starting in 5 seconds
[Rebroadcast Plugin]: Cloud RTSP prebuffer session started
[Rebroadcast Plugin]: Cloud RTSP prebuffer session starting
[Rebroadcast Plugin]: Cloud RTSP prebuffer session ended with error RPCResultError: Failed to capture stream for Pepe Sale: RTSPS link not found.
[Rebroadcast Plugin]:     at C.getVideoStream (/src/camera.ts:309:19)
[Rebroadcast Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:748:37)
[Rebroadcast Plugin]: @scrypted/tuya:host
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin {
[Rebroadcast Plugin]:   cause: undefined
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: Pepe Sale restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: Cloud RTSP prebuffer session started
[Rebroadcast Plugin]: Cloud RTSP prebuffer session ended with error RPCResultError: Failed to capture stream for Pepe Sale: RTSPS link not found.
[Rebroadcast Plugin]:     at C.getVideoStream (/src/camera.ts:309:19)
[Rebroadcast Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:748:37)
[Rebroadcast Plugin]: @scrypted/tuya:host
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin {
[Rebroadcast Plugin]:   cause: undefined
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: Cloud RTSP prebuffer session started
[Rebroadcast Plugin]: Cloud RTSP prebuffer session starting
[Rebroadcast Plugin]: Cloud RTSP prebuffer session ended with error RPCResultError: Failed to capture stream for Pepe Sale: RTSPS link not found.
[Rebroadcast Plugin]:     at C.getVideoStream (/src/camera.ts:309:19)
[Rebroadcast Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:748:37)
[Rebroadcast Plugin]: @scrypted/tuya:host
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin {
[Rebroadcast Plugin]:   cause: undefined
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: Pepe Sale restarting prebuffer session in 5 seconds
[Snapshot Plugin]: creating error image with background Snapshot Failed false
[Rebroadcast Plugin]: Cloud RTSP prebuffer session started
[Rebroadcast Plugin]: Cloud RTSP prebuffer session starting
[Rebroadcast Plugin]: Cloud RTSP prebuffer session ended with error RPCResultError: Failed to capture stream for Pepe Sale: RTSPS link not found.
[Rebroadcast Plugin]:     at C.getVideoStream (/src/camera.ts:309:19)
[Rebroadcast Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:748:37)
[Rebroadcast Plugin]: @scrypted/tuya:host
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin {
[Rebroadcast Plugin]:   cause: undefined
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: Pepe Sale restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: Cloud RTSP prebuffer session started
[Rebroadcast Plugin]: Cloud RTSP prebuffer session starting
[Rebroadcast Plugin]: Cloud RTSP prebuffer session ended with error RPCResultError: Failed to capture stream for Pepe Sale: RTSPS link not found.
[Rebroadcast Plugin]:     at C.getVideoStream (/src/camera.ts:309:19)
[Rebroadcast Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:748:37)
[Rebroadcast Plugin]: @scrypted/tuya:host
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin {
[Rebroadcast Plugin]:   cause: undefined
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: Pepe Sale restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: Cloud RTSP prebuffer session started
[Rebroadcast Plugin]: Cloud RTSP prebuffer session starting
[Rebroadcast Plugin]: Cloud RTSP prebuffer session ended with error RPCResultError: Failed to capture stream for Pepe Sale: RTSPS link not found.
[Rebroadcast Plugin]:     at C.getVideoStream (/src/camera.ts:309:19)
[Rebroadcast Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:748:37)
[Rebroadcast Plugin]: @scrypted/tuya:host
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin {
[Rebroadcast Plugin]:   cause: undefined
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: Pepe Sale restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: Cloud RTSP prebuffer session started
[Rebroadcast Plugin]: Cloud RTSP prebuffer session starting
[Rebroadcast Plugin]: Cloud RTSP prebuffer session ended with error RPCResultError: Failed to capture stream for Pepe Sale: RTSPS link not found.
[Rebroadcast Plugin]:     at C.getVideoStream (/src/camera.ts:309:19)
[Rebroadcast Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:748:37)
[Rebroadcast Plugin]: @scrypted/tuya:host
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin {
[Rebroadcast Plugin]:   cause: undefined
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: Pepe Sale restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: Cloud RTSP prebuffer session started
[Rebroadcast Plugin]: Cloud RTSP prebuffer session starting
[Rebroadcast Plugin]: Cloud RTSP prebuffer session ended with error RPCResultError: Failed to capture stream for Pepe Sale: RTSPS link not found.
```

**Comment by pergolafabio** [comment]
screens from iot:
![image](https://github.com/koush/scrypted/assets/43251136/81eade95-aa02-4d2f-a676-68af3a7e07c7)
![image](https://github.com/koush/scrypted/assets/43251136/721fd826-bf07-4d53-add0-cbf731224004)

**Comment by koush** [comment]
I dont think tuya provides a snapshot url. it eventually gets pulled when the stream is retrieved.

**Comment by pergolafabio** [comment]
Ah ok, but I also clicked on the image, but I was not getting a stream? Stayed black

**Comment by pergolafabio** [comment]
If i click on it, it stays on a black screen, with the same error log in console as i posted above

![image](https://github.com/koush/scrypted/assets/43251136/a026c685-f32d-43fb-a066-d86eedec37f8)

**Comment by pergolafabio** [comment]
Hi , any idea what could be wrong? Why it doesnt load the video?

Thnx for feedback
