### ISSUE TITLE
ZWave Network Key Conversion

### ISSUE THREAD

**Issue by marcptrs** [koush/scrypted#116]
Having a tough time figuring out how to translate the ZWave key I used in Home Assistant to Scrypted. The Home Assistant format is like this (taken from their doc):

2232666D100F795E5BB17F0A1BB7A146

When I enter this as a network key in Scrypted, I get the following error:

failure putSetting ZWaveError: The network key must be a buffer with length 16! (ZW0108)
    at checkOptions (/home/marc/node_modules/zwave-js/src/lib/driver/Driver.ts:295:10)
    at new Driver (/home/marc/node_modules/zwave-js/src/lib/driver/Driver.ts:440:3)
    at ZwaveControllerProvider.startDriver (/plugin/main.nodejs.js:51852:20)
    at ZwaveControllerProvider.putSetting (/plugin/main.nodejs.js:51932:10)
    at RpcPeer.handleMessage (/home/marc/.scrypted/node_modules/@scrypted/server/src/rpc.ts:483:37) {
  code: 108,
  context: undefined,
  transactionSource: undefined

What's the easiest way for me to convert this to a buffer with a length of 16?

**Comment by koush** [comment]
I think that's a hex key, and scrypted expects base64. should be easy enough to convert. here's what may work:

```
> Buffer.from('2232666D100F795E5BB17F0A1BB7A146','hex').toString('base64')
IjJmbRAPeV5bsX8KG7ehRg==
```

Let me know if that works, hop on discord if it does not.

**Comment by koush** [comment]
I'll convert the key storage format to hex, since that's what HA uses. I think OZW used to store in base64.

**Comment by marcptrs** [comment]
Yes you're right it's a hex string, seems to have converted fine for me. Thanks for the quick response!
