### ISSUE TITLE
Reolink Camera Plugin - 

### ISSUE THREAD

**Issue by Alias-ZA** [koush/scrypted#1173]
My setup:

Home Assistant OS on Intel NUC 
Scrypted 0.57.0
Reolink NVR (RLN16-410)
8 x RLC-811A
1 x Reolink Doorbell POE

All cameras are wired to the NVR with CAT 6. NVR is wired to network.  

I can load the RTMP stream of the Doorbell (Channel 0) into HA (Generic Camera) and a webhook for the still - this works perfectly and as expected. 

If I then go and add the next "normal" camera, it works as expected and on Scrypted I can see the still image and the feed is there if I click on the image. Looks to all be working fine. 

If I then go to add this camera (Channel 9) to a generic card - I get a timeout error. Opening the console of the camera in scrypted I see the below error:  [Rebroadcast Plugin]: RTMP main.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed

Similar to this: https://github.com/koush/scrypted/issues/1146 - my password is simple though (instacam), all lowercase and no special char - works fine with the doorbell.

**Screenshots**

```
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session started
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session starting
stream url rtmp://10.0.4.5:1935/bcs/channel9_main.bcs?channel=9&stream=0&user=admin&password=instacam
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -i rtmp:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:35049/d0e8ab99328f929c
debug event:
 [{"cmd":"GetMdState","code":0,"value":{"state":0}}]
[Rebroadcast Plugin]: rtmp://admin:instacam@10.0.4.5:1935/bcs/channel9_main.bcs?channel=9&stream=0&user=admin&password=instacam: End of file
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: ffmpeg exited
[Rebroadcast Plugin]:     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:76176)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:526:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Rebroadcast Plugin]: RTMP main.bcs prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
[Rebroadcast Plugin]:     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:76493
[Rebroadcast Plugin]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]: Reolink Camera restarting prebuffer session in 5 seconds
debug event:
 [{"cmd":"GetMdState","code":0,"value":{"state":0}}]
debug event:
 [{"cmd":"GetMdState","code":0,"value":{"state":0}}]
debug event:
 [{"cmd":"GetMdState","code":0,"value":{"state":0}}]
debug event:
 [{"cmd":"GetMdState","code":0,"value":{"state":0}}]
```

Am I missing something stupid here?

**Comment by Alias-ZA** [comment]
So not via the NVR?

**Comment by Alias-ZA** [comment]
Okay, I have taken all the cameras out of the NVR and they are now directly powered and plugged in via my Unifi Dream Machine Pro SE. 

I deleted all the entries in scrypted, restarted the HA server and re-added the camera's each with their own IP address. 

I get the same error. First camera works fine, the rest have the rebroadcast error. 

Any ideas?
