### ISSUE TITLE
failed to start

### ISSUE THREAD

**Issue by s8ngyu** [koush/scrypted#122]
I tried to run on Docker, using `docker-compose up`

and I get these errors
```
scrypted is up-to-date
Attaching to scrypted
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scrypted    | Failed to listen on port 10081. It may be in use.
scrypted    | Use the environment variable SCRYPTED_DEBUG_PORT to change the port.
scrypted    | Error: listen EADDRINUSE: address already in use :::10081
scrypted    |     at Server.setupListenHandle [as _listen2] (node:net:1334:16)
scrypted    |     at listenInCluster (node:net:1382:12)
scrypted    |     at Server.listen (node:net:1469:7)
scrypted    |     at listenServerPort (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:41:12)
scrypted    |     at Object.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:90:1)
scrypted    |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scrypted    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
scrypted    |     at Module.load (node:internal/modules/cjs/loader:981:32)
scrypted    |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scrypted    |     at Module.require (node:internal/modules/cjs/loader:1005:19)
```

I'm running it on Raspberry Pi 4 on bullseye.

**Comment by miwagner1** [comment]
You already have a service listening on ports. Perhaps you already have a container running. Check with docker ps
