### ISSUE TITLE
Arlo plugin failing

### ISSUE THREAD

**Issue by mikesalz** [koush/scrypted#1245]
As of this morning, I am getting the below failure:

> 
> linux x64 #42962 SMP Mon May 29 14:38:23 CST 2023
> server version: 0.80.0
> plugin version: @scrypted/arlo 0.11.13
> full
> ########################
> 1/5/2024, 3:46:27 PM
> ########################
> python version: python3.10
> python prefix: /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329
> requirements.txt (up to date)
> paho-mqtt==1.6.1
> aiohttp==3.9.1
> requests==2.31.0
> cachetools==5.3.2
> scrypted-arlo-go==0.6.4
> cloudscraper==1.2.71
> curl-cffi==0.5.10
> async-timeout==4.0.3
> beautifulsoup4==4.12.2
> --extra-index-url=https://bjia56.github.io/armv7l-wheels/
> --extra-index-url=https://bjia56.github.io/scrypted-arlo-go/
> --prefer-binary
> 
> site-packages: /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/local/lib/python3.10/dist-packages
> /server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/local/lib/python3.10/dist-packages/bs4/css.py:8: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
>   warnings.warn(
> plugin start/fork failed
> Traceback (most recent call last):
>   File "/server/node_modules/@scrypted/server/python/plugin_remote.py", line 381, in loadZip
>     return await self.loadZipWrapped(packageJson, zipData, options)
>   File "/server/node_modules/@scrypted/server/python/plugin_remote.py", line 746, in loadZipWrapped
>     from main import create_scrypted_plugin  # type: ignore
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-42535df81d6ad9d6f52c99fe22bb2ea6.zip/main.py", line 1, in <module>
>     from arlo_plugin import ArloProvider
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-42535df81d6ad9d6f52c99fe22bb2ea6.zip/arlo_plugin/__init__.py", line 1, in <module>
>     from .provider import ArloProvider
>   File "/server/volume/plugins/@scrypted/arlo/zip/1-42535df81d6ad9d6f52c99fe22bb2ea6.zip/arlo_plugin/provider.py", line 9, in <module>
>     import requests
>   File "/server/volume/plugins/@scrypted/arlo/python3.10-Linux-x86_64-20230329/local/lib/python3.10/dist-packages/requests/__init__.py", line 43, in <module>
>     import urllib3
> ModuleNotFoundError: No module named 'urllib3'
>

**Comment by koush** [comment]
for some reason your docker image wasn't updated with this:

SCRYPTED_BASE_VERSION='20240103'

That's why it's failing. The dependencies need to be rebuilt.

I think you can delete the plugins/@scrypted/arlo folder from your volume, reload the plugin, and it will reinstall.
