### ISSUE TITLE
problem to get item Ring Intercom from Ring cloud using Ring plugin

### ISSUE THREAD

**Issue by pilot1981** [koush/scrypted#1248]
**Describe the bug**
after successfully login in Ring plugin, unable to retrieve item Ring Intercom from Ring cloud; no any problem to login in Ring account

**To Reproduce**
1. Go to 'Ring Plugin' and add this plugin
2. insert username e password + token 2FA
3. Scroll down to 'Providing Things'
4. I only see an item with DeviceProvider type

**Expected behavior**
I would retrieve Ring Intercom doorbell, but I only see a DeviceProvider type, not any change to retrieve doorbell
Already tried to remove Ring plugin and add it again: same result!

**Screenshots**
![image](https://github.com/koush/scrypted/assets/46350465/c2021afe-a43f-450e-bee9-11f4ce7bd923)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version:120.0

**Smartphone (please complete the following information):**
 - Device: iPhone mini 12
 - OS: 17.2.1
 - Browser: chrome
 - Version: 120.0

**Additional context**
logs:
linux x64 #1 SMP PREEMPT_DYNAMIC Thu Jan  4 22:07:55 UTC 2024
server version: 0.80.0
plugin version: @scrypted/ring 0.0.136
full
########################
1/7/2024, 10:17:43 PM
########################
node modules /data/scrypted_data/plugins/@scrypted/ring/node18-linux-x64-20240103
native dependencies (outdated) got socket.io-client

added 55 packages, and audited 56 packages in 14s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
native dependencies installed.
plugin loaded
discovery failure Error: refresh token, username, and password are missing.
    at Vr.tryLogin (/src/main.ts:157:19)
    at Vr.discoverDevices (/src/main.ts:204:20)
    at new Vr (/src/main.ts:104:14)
    at Object.onLoadZip (/server/node_modules/@scrypted/server/src/plugin/plugin-remote-worker.ts:384:38)
    at Object.loadZip (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:660:28)
    at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:759:37)
login success, trying discovery
unhandledRejection TypeError: Cannot read properties of undefined (reading 'getLocations')
    at Vr.discoverDevices (/src/main.ts:206:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Vr.clearTryDiscoverDevices (/src/main.ts:119:52)
login completed successfully with 2 factor code
login success, trying discovery
discovery completed successfully
(node:17919) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by pilot1981** [comment]
I update issue with ne logs with lastest error (ring plugin retrieve always only item with DeviceProvider type):

    domain: 'repairs',
    services: {
      remove: [Object],
      create: [Object],
      unignore_all: [Object],
      ignore_all: [Object]
    }
  },
  {
    domain: 'spook',
    services: { random_fail: [Object], boo: [Object] }
  },
  {
    domain: 'netatmo',
    services: {
      set_persons_home: [Object],
      set_person_away: [Object],
      set_camera_light: [Object],
      set_schedule: [Object],
      set_preset_mode_with_end_datetime: [Object],
      set_temperature_with_end_datetime: [Object],
      set_temperature_with_time_period: [Object],
      clear_temperature_setting: [Object],
      register_webhook: [Object],
      unregister_webhook: [Object]
    }
  },
  {
    domain: 'huesyncbox',
    services: { set_bridge: [Object], set_sync_state: [Object] }
  },
  {
    domain: 'adguard',
    services: {
      add_url: [Object],
      remove_url: [Object],
      enable_url: [Object],
      disable_url: [Object],
      refresh: [Object]
    }
  },
  {
    domain: 'alexa_media',
    services: {
      update_last_called: [Object],
      clear_history: [Object],
      force_logout: [Object]
    }
  },
  { domain: 'onvif', services: { ptz: [Object] } }
]

native dependencies (up to date). got socket.io-client

node modules /data/scrypted_data/plugins/@scrypted/webrtc/node18-linux-x64-20240103

plugin loaded

i Scrypted Core loaded @scrypted/core
i Autoupdate Plugins automation is waiting for event trigger.
i Autoupdate Plugins event will fire at 1/9/2024, 3:15:08 AM
i Autoupdate Plugins event will fire in 994 minutes.
no device was returned by the plugin 35
no device was returned by the plugin 37
no device was returned by the plugin 38
no device was returned by the plugin 39
no device was returned by the plugin 40
plugin loaded

i WebRTC Plugin loaded @scrypted/webrtc
(node:134) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

no device was returned by the plugin 47
plugin loaded

i Ring Plugin loaded @scrypted/ring
login success, trying discovery

node modules /data/scrypted_data/plugins/@scrypted/webrtc/node18-linux-x64-20240103

(node:134) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

error occured retrieving device from plugin RPCResultError [TypeError]: Cannot read properties of undefined (reading 'find')
    at Vr.getDevice (/src/main.ts:237:45)
    at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:759:66)
    at RpcPeer.handleMessage (/server/node_modules/@scrypted/server/src/rpc.ts:700:18)
    at process.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-plugin-main.ts:33:47)
    at process.emit (node:events:517:28)
    at process.emit (node:domain:489:12)
    at process.emit (/server/node_modules/source-map-support/source-map-support.js:516:21)
    at emit (node:internal/child_process:944:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
@scrypted/ring:host {
  cause: undefined
}
(node:116) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by pilot1981** [comment]
add more logs:

plugin loaded

i WebRTC Plugin loaded @scrypted/webrtc
(node:121) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

no device was returned by the plugin 44
node modules /data/scrypted_data/plugins/@scrypted/webrtc/node18-linux-x64-20240103

(node:121) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

installing package @scrypted/ring 0.0.136
downloaded tarball 1337651
parsing entry package/package.json
parsing entry package/tsconfig.json
parsing entry package/README.md
parsing entry package/dist/plugin.zip
npm package files: package/package.json, package/tsconfig.json, package/README.md, package/dist/plugin.zip
Skipping @scrypted/snapshot : Plugin already installed.
Skipping @scrypted/webrtc : Plugin already installed.
i Ring Plugin loading @scrypted/ring
i Ring Plugin pid 164
node modules /data/scrypted_data/plugins/@scrypted/ring/node18-linux-x64-20240103

native dependencies (outdated) got socket.io-client

installing package @scrypted/prebuffer-mixin 0.10.11

downloaded tarball 195053
parsing entry package/package.json
parsing entry package/README.md
parsing entry package/dist/plugin.zip
npm package files: package/package.json, package/README.md, package/dist/plugin.zip
i Rebroadcast Plugin loading @scrypted/prebuffer-mixin
i Rebroadcast Plugin pid 186
node modules /data/scrypted_data/plugins/@scrypted/prebuffer-mixin/node18-linux-x64-20240103

plugin loaded

i Rebroadcast Plugin loaded @scrypted/prebuffer-mixin
i Rebroadcast Plugin fromMimeType: x-scrypted/x-rfc4571
i Rebroadcast Plugin toMimeType: x-scrypted/x-ffmpeg-input
i Rebroadcast Plugin Rebroadcaster scheduled for restart at 2AM: 500 minutes

added 55 packages, and audited 56 packages in 11s


10 packages are looking for funding
  run `npm fund` for details


found 0 vulnerabilities

native dependencies installed.

plugin loaded

discovery failure Error: refresh token, username, and password are missing.
    at Vr.tryLogin (/src/main.ts:157:19)
    at Vr.discoverDevices (/src/main.ts:204:20)
    at new Vr (/src/main.ts:104:14)
    at Object.onLoadZip (/server/node_modules/@scrypted/server/src/plugin/plugin-remote-worker.ts:384:38)
    at Object.loadZip (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:660:28)
    at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:759:37)

i Ring Plugin loaded @scrypted/ring
a Ring Plugin Enter your Ring username and password to complete setup.
alert {
  timestamp: 1704731993482,
  level: 'a',
  message: 'Enter your Ring username and password to complete setup.',
  path: '/device/49',
  title: 'Ring Plugin'
}
login success, trying discovery

a Ring Plugin Check your email or texts for your Ring login code, then enter it into the Two Factor Code setting to conplete login.
alert {
  timestamp: 1704732018029,
  level: 'a',
  message: 'Check your email or texts for your Ring login code, then enter it into the Two Factor Code setting to conplete login.',
  path: '/device/49',
  title: 'Ring Plugin'
}
unhandledRejection TypeError: Cannot read properties of undefined (reading 'getLocations')
    at Vr.discoverDevices (/src/main.ts:206:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Vr.clearTryDiscoverDevices (/src/main.ts:119:52)

e Ring Plugin unhandledRejection TypeError: Cannot read properties of undefined (reading 'getLocations')
login completed successfully with 2 factor code

login success, trying discovery

discovery completed successfully

(node:164) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by tom301080** [comment]
Same issue on my side. Would love to integrate the ring intercom

**Comment by piesinopoli** [comment]
Any updates?

**Comment by Lern2Play** [comment]
Is there a solution for this problem?

**Comment by drtp** [comment]
Would love to see a support for the new Ring Intercom Video within the Ring Plugin.

**Comment by dagasoft** [comment]
I also have problems trying to integrate Ring intercom. Is it possible to give support for this?

Thanks for your work.
