### ISSUE TITLE
"node" version out of date. Please update node to v18 or higher.')

### ISSUE THREAD

**Issue by Rustymage** [koush/scrypted#1285]
Running in an LXC on Proxmox. V0.85 works fine, updating inside the app results in the following issue:

![image](https://github.com/koush/scrypted/assets/19926955/c23a1b29-c79d-445c-8788-38f423b382da)

The logs are below:

```
Jan 25 21:07:36 scrypted npx[325]: Starting scrypted main...
Jan 25 21:07:36 scrypted npx[325]: running npm --prefix /root/.scrypted exec scrypted-serve
Jan 25 21:07:37 scrypted npx[402]: /root/.scrypted/node_modules/@scrypted/server/dist/scrypted-server-main.js:58
Jan 25 21:07:37 scrypted npx[402]:     throw new Error('"node" version out of date. Please update node to v18 or higher.');
Jan 25 21:07:37 scrypted npx[402]:     ^
Jan 25 21:07:37 scrypted npx[402]: Error: "node" version out of date. Please update node to v18 or higher.
Jan 25 21:07:37 scrypted npx[402]:     at Object.<anonymous> (/root/.scrypted/node_modules/@scrypted/server/dist/scrypted-server-main.js:58:11)
Jan 25 21:07:37 scrypted npx[402]:     at Module._compile (node:internal/modules/cjs/loader:1198:14)
Jan 25 21:07:37 scrypted npx[402]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
Jan 25 21:07:37 scrypted npx[402]:     at Module.load (node:internal/modules/cjs/loader:1076:32)
Jan 25 21:07:37 scrypted npx[402]:     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
Jan 25 21:07:37 scrypted npx[402]:     at Module.require (node:internal/modules/cjs/loader:1100:19)
Jan 25 21:07:37 scrypted npx[402]:     at require (node:internal/modules/cjs/helpers:119:18)
Jan 25 21:07:37 scrypted npx[402]:     at start (/root/.scrypted/node_modules/@scrypted/server/dist/scrypted-main-exports.js:53:23)
Jan 25 21:07:37 scrypted npx[402]:     at Object.<anonymous> (/root/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js:7:37)
Jan 25 21:07:37 scrypted npx[402]:     at Module._compile (node:internal/modules/cjs/loader:1198:14)
Jan 25 21:07:37 scrypted npx[325]: Service exited. Restarting momentarily.
Jan 25 21:07:47 scrypted npx[325]: Starting scrypted main...
Jan 25 21:07:47 scrypted npx[325]: running npm --prefix /root/.scrypted exec scrypted-serve
Jan 25 21:07:47 scrypted npx[432]: /root/.scrypted/node_modules/@scrypted/server/dist/scrypted-server-main.js:58
Jan 25 21:07:47 scrypted npx[432]:     throw new Error('"node" version out of date. Please update node to v18 or higher.');
Jan 25 21:07:47 scrypted npx[432]:     ^
Jan 25 21:07:47 scrypted npx[432]: Error: "node" version out of date. Please update node to v18 or higher.
Jan 25 21:07:47 scrypted npx[432]:     at Object.<anonymous> (/root/.scrypted/node_modules/@scrypted/server/dist/scrypted-server-main.js:58:11)
Jan 25 21:07:47 scrypted npx[432]:     at Module._compile (node:internal/modules/cjs/loader:1198:14)
Jan 25 21:07:47 scrypted npx[432]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
Jan 25 21:07:47 scrypted npx[432]:     at Module.load (node:internal/modules/cjs/loader:1076:32)
Jan 25 21:07:47 scrypted npx[432]:     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
Jan 25 21:07:47 scrypted npx[432]:     at Module.require (node:internal/modules/cjs/loader:1100:19)
Jan 25 21:07:47 scrypted npx[432]:     at require (node:internal/modules/cjs/helpers:119:18)
Jan 25 21:07:47 scrypted npx[432]:     at start (/root/.scrypted/node_modules/@scrypted/server/dist/scrypted-main-exports.js:53:23)
Jan 25 21:07:47 scrypted npx[432]:     at Object.<anonymous> (/root/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js:7:37)
Jan 25 21:07:47 scrypted npx[432]:     at Module._compile (node:internal/modules/cjs/loader:1198:14)
Jan 25 21:07:47 scrypted npx[325]: Service exited. Restarting momentarily.
```

https://github.com/koush/scrypted/issues/1268#issuecomment-1911001010

![image](https://github.com/koush/scrypted/assets/19926955/7b2e1d37-c55a-4a43-9a49-5551cf5a9a8a)

Not sure where to go from here, except backwards to a restore.

Thanks in advance.

**Comment by koush** [comment]
Upgrade node

**Comment by Rustymage** [comment]
To which version?

As you can see, I already have inside the LXC.

**Comment by koush** [comment]
Preferably switch to the official lxc script

**Comment by Rustymage** [comment]
I probably will but need to get to the backup version of Scrypted before I can - I don't fancy having to re-add everything...

**Comment by Rustymage** [comment]
Running `npm --prefix /root/.scrypted exec scrypted-serve` in the console has brought up the instance.
