### ISSUE TITLE
Can't set lockState from MQTT plugin due to missing LockState.* enum at execution

### ISSUE THREAD

**Issue by tagdara** [koush/scrypted#1302]
I am trying to create a virtual Lock which changes its condition based on an MQTT message.  My MQTT environment is functional and I am using something similar to the DIY Doorbell without issue.

When creating the device in the MQTT Plugin I use the following:
```
mqtt.subscribe({
    'Sofa.ButtonController/test/pressState': value => device.lockState = value.json.value === 'OFF' ?  LockState.Unlocked : LockState.Locked
});

mqtt.handleTypes(ScryptedInterface.Lock);
```
The MQTT message is received, the code is triggered, and then the MQTT plugin crashes with the following error (only visible in the MQTT plugin console, not in the device):
```
mqtt message Sofa.ButtonController/test/pressState {"value": "OFF", "timeOfSample": "2024-02-07T23:47:59.17Z"}
uncaughtException ReferenceError: LockState is not defined
    at cb (script.js:48:106)
    at v.<anonymous> (/src/main.ts:114:29)
    at v.emit (node:events:517:28)
    at v.emit (node:domain:489:12)
    at v._handlePublish (/node_modules/mqtt/lib/client.js:1277:12)
    at v._handlePacket (/node_modules/mqtt/lib/client.js:410:12)
    at work (/node_modules/mqtt/lib/client.js:321:12)
    at E._write (/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at /node_modules/readable-stream/lib/_stream_writable.js:398:5
```

Unfortunately, when trying to specify anything other than Lockstate.Locked/Unlocked/Jammed as the value, the UI specifies that only LockState.Unlocked/Locked/Jammed may be used.  I did also try sdk.pluginHostAPI.LockState.Locked which parsed but crashed with a different error message (only visible in the MQTT plugin console, not in the device):
```
uncaughtException Error: value must be a primitive type
    at checkProperty (/server/node_modules/@scrypted/server/src/plugin/plugin-state-check.ts:15:15)
    at DeviceStateProxyHandler.state [as set] (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:181:22)
    at I.<anonymous> (/sdk/dist/src/index.js:153:35)
    at cb (script.js:48:72)
    at v.<anonymous> (/src/main.ts:114:29)
    at v.emit (node:events:517:28)
    at v.emit (node:domain:489:12)
    at v._handlePublish (/node_modules/mqtt/lib/client.js:1277:12)
    at v._handlePacket (/node_modules/mqtt/lib/client.js:410:12)
    at l (/node_modules/mqtt/lib/client.js:321:12)
```

**Expected behavior**
An Enum such as LockState which is valid in the editor should also work when executed or warn or specify the correct syntax.

**Comment by koush** [comment]
You can see the string constant value. I plan on removing the constants anyways

**Comment by tagdara** [comment]
I used "Locked" and "Unlocked" as the values and even though the linter complained, it works fine now. Thanks!
```
mqtt.subscribe({
    'Sofa.ButtonController/default/pressState': value => device.lockState = value.json.value === 'OFF' ?  "Locked" : "Unlocked"
});
mqtt.handleTypes(ScryptedInterface.Lock);
```
