### ISSUE TITLE
homekit plugin bug

### ISSUE THREAD

**Issue by BazlTech** [koush/scrypted#1304]
**Describe the bug**
Scrypted installed via docker compose just fine.  Installing the homekit plugin through the gui works just fine. Literally nothing else done - just a fresh install and added the homekit plugin.
Unable to add scrypted to home, and I think it's due to an exception:
```
uncaughtException Error: [object Object]
    at Object.<anonymous> (/@scrypted/homekit/main.nodejs.js:2:164635)
    at EventEmitter.<anonymous> (/@scrypted/homekit/main.nodejs.js:2:163358)
    at EventEmitter.emit (node:events:517:28)
    at EventEmitter.emit (node:domain:489:12)
    at /@scrypted/homekit/main.nodejs.js:2:160081
    at Socket.<anonymous> (/@scrypted/homekit/main.nodejs.js:2:181064)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at emitReadable_ (node:internal/streams/readable:633:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
e HomeKit uncaughtException Error: [object Object]
```

**To Reproduce**
1. Install homekit plugin
2. Check the logs, it'll be there immediately

**Expected behavior**
I expect to easily add scrypted to home using the homekit plugin.

**Screenshots**
![image](https://github.com/koush/scrypted/assets/105654927/a5ccc67f-dd29-447d-a0b0-9d2a3f3821f4)
![image](https://github.com/koush/scrypted/assets/105654927/7dca3540-80bc-4ef9-a05f-8da1f8c7930a)

**Comment by koush** [comment]
install method?

**Comment by BazlTech** [comment]
I just came here to cancel this.
I installed via docker compose.

I was using the mounting option for avahi/dbus.  I commented that out, disabled the services on the host, and instead used the env variable to use avahi via docker.  Restarted the container, and now the homekit pairs just fine.
