### ISSUE TITLE
lite version docker not show stream from camers after update from 0.93.0 to latest

### ISSUE THREAD

**Issue by twocolors** [koush/scrypted#1392]
**Workaround:**
docker:18-jammy-lite-v0.93.0

**Repro step:**
update docker:lite from 0.93.0 to latest

**Server:** N100

**OS:** debian
**Installation Method:** docker

**Software:** Browser/Homekit

update docker:lite from [v0.93.0](https://github.com/koush/scrypted/releases/tag/v0.93.0) to [v0.96.0](https://github.com/koush/scrypted/releases/tag/v0.96.0) and camers not show i see log
```
scrypted  | i WebRTC Plugin loaded @scrypted/webrtc
scrypted  | (node:57) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
scrypted  | (Use `node --trace-deprecation ...` to show where the warning was created)
scrypted  |
scrypted  | no device was returned by the plugin 19
scrypted  | mdns bind address [ '192.168.0.10' ]
scrypted  |
scrypted  | starting plugin @scrypted/webrtc
scrypted  |
scrypted  | node modules /server/volume/plugins/@scrypted/webrtc/node20-linux-x64-20240321
scrypted  |
scrypted  | [Intercom Child] HomeKit Connection 192.168.0.31
scrypted  |
scrypted  | starting plugin @scrypted/prebuffer-mixin
scrypted  |
scrypted  | starting plugin @scrypted/prebuffer-mixin
scrypted  |
scrypted  | [Intercom Homeowner] HomeKit Connection 192.168.0.31
scrypted  |
scrypted  | node modules /server/volume/plugins/@scrypted/prebuffer-mixin/node20-linux-x64-20240321
scrypted  |
scrypted  | node modules /server/volume/plugins/@scrypted/prebuffer-mixin/node20-linux-x64-20240321
scrypted  |
scrypted  | [Intercom Child] prebuffer sessions starting in 5 seconds
scrypted  |
scrypted  | [Intercom Homeowner] prebuffer sessions starting in 5 seconds
scrypted  |
scrypted  | [Intercom Child] Stream 1 prebuffer session started
scrypted  | [Intercom Homeowner] Stream 1 prebuffer session started
scrypted  |
scrypted  | [Intercom Child] Stream 1 prebuffer session starting
scrypted  | [Intercom Homeowner] Stream 1 prebuffer session starting
scrypted  |
scrypted  | (node:57) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
scrypted  | (Use `node --trace-deprecation ...` to show where the warning was created)
scrypted  |
scrypted  | [Intercom Child] -hide_banner -fflags +genpts -i http:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:35003/0be7eae1fa296898
scrypted  |
scrypted  | [Intercom Homeowner] -hide_banner -fflags +genpts -i http:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:43261/314c0fee6f2486d4
scrypted  |
scrypted  | [Intercom Homeowner] ffmpeg exited
scrypted  |
scrypted  | [Intercom Homeowner] rebroadcast error Error: ffmpeg exited
scrypted  |     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:71744)
scrypted  |     at ChildProcess.emit (node:events:530:35)
scrypted  |     at ChildProcess.emit (node:domain:488:12)
scrypted  |     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
scrypted  |
scrypted  | i Intercom Homeowner online: false
scrypted  | [Intercom Homeowner] Intercom Homeowner restarting prebuffer session in 5 seconds
scrypted  |
scrypted  | [Intercom Homeowner] Stream 1 prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
scrypted  |     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:72061
scrypted  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
scrypted  |
scrypted  | [Intercom Child] ffmpeg exited
scrypted  |
scrypted  | [Intercom Child] rebroadcast error Error: ffmpeg exited
scrypted  |     at ChildProcess.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:71744)
scrypted  |     at ChildProcess.emit (node:events:530:35)
scrypted  |     at ChildProcess.emit (node:domain:488:12)
scrypted  |     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
scrypted  |
scrypted  | i Intercom Child online: false
scrypted  | [Intercom Child] Intercom Child restarting prebuffer session in 5 seconds
scrypted  |
scrypted  | [Intercom Child] Stream 1 prebuffer session ended with error Error: ffmpeg killed before sdp could be parsed
scrypted  |     at /@scrypted/prebuffer-mixin/main.nodejs.js:1:72061
scrypted  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
scrypted  |
^Ccanceled
```
if i install docker:full all work 
```
scrypted  | i WebRTC Plugin loaded @scrypted/webrtc
scrypted  | (node:57) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
scrypted  | (Use `node --trace-deprecation ...` to show where the warning was created)
scrypted  |
scrypted  | Removed Recordings: 0: 0 bytes.
scrypted  | Retained Recordings: 0: 0 bytes.
scrypted  |
scrypted  | no device was returned by the plugin 19
scrypted  | mdns bind address [ '192.168.0.10' ]
scrypted  |
scrypted  | starting plugin @scrypted/webrtc
scrypted  |
scrypted  | [Intercom Child] HomeKit Connection 192.168.0.31
scrypted  |
scrypted  | node modules /server/volume/plugins/@scrypted/webrtc/node20-linux-x64-20240321
scrypted  |
scrypted  | starting plugin @scrypted/prebuffer-mixin
scrypted  |
scrypted  | starting plugin @scrypted/prebuffer-mixin
scrypted  |
scrypted  | node modules /server/volume/plugins/@scrypted/prebuffer-mixin/node20-linux-x64-20240321
scrypted  |
scrypted  | node modules /server/volume/plugins/@scrypted/prebuffer-mixin/node20-linux-x64-20240321
scrypted  |
scrypted  | [Intercom Homeowner] prebuffer sessions starting in 5 seconds
scrypted  |
scrypted  | [Intercom Child] prebuffer sessions starting in 5 seconds
scrypted  |
scrypted  | [Intercom Child] Stream 1 prebuffer session started
scrypted  |
scrypted  | [Intercom Child] Stream 1 prebuffer session starting
scrypted  |
scrypted  | [Intercom Homeowner] Stream 1 prebuffer session started
scrypted  |
scrypted  | [Intercom Homeowner] HomeKit Connection 192.168.0.31
scrypted  |
scrypted  | [Intercom Homeowner] Stream 1 prebuffer session starting
scrypted  |
scrypted  | [Intercom Homeowner] -hide_banner -fflags +genpts -i http:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:44121/707df0cd516248e1
scrypted  |
scrypted  | [Intercom Child] -hide_banner -fflags +genpts -i http:[REDACTED] -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://127.0.0.1:38957/1b6083c28d8d5469
scrypted  |
scrypted  | (node:57) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
scrypted  | (Use `node --trace-deprecation ...` to show where the warning was created)
scrypted  |
scrypted  | [Intercom Homeowner] Input #0, flv, from 'http://192.168.0.10:18000/stream?cameraID=64870437':
scrypted  |   Metadata:
scrypted  |     encoder         : Lavf58.29.100
scrypted  |   Duration: 00:00:00.00, start: 2061353.569000, bitrate: N/A
scrypted  |   Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 1k tbn
scrypted  |   Stream #0:1: Audio: mp3, 44100 Hz, mono, fltp, 64 kb/s
scrypted  |
scrypted  |
scrypted  | [Intercom Homeowner] Output #0, rtsp, to 'rtsp://127.0.0.1:44121/707df0cd516248e1':
scrypted  |   Metadata:
scrypted  |     encoder         : Lavf58.76.100
scrypted  |   Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, q=2-31, 25 fps, 25 tbr, 90k tbn, 1k tbc
scrypted  |   Stream #0:1: Audio: mp3, 44100 Hz, mono, fltp, 64 kb/s
scrypted  | Stream mapping:
scrypted  |   Stream #0:0 -> #0:0 (copy)
scrypted  |   Stream #0:1 -> #0:1 (copy)
scrypted  | Press [q] to stop, [?] for help
scrypted  | frame=    1 fps=0.0 q=-1.0 size=N/A time=00:00:00.00 bitrate=N/A speed=N/A
scrypted  |
scrypted  | [Intercom Homeowner] video/audio detected, discarding further input
scrypted  |
scrypted  | [Intercom Child] Input #0, flv, from 'http://192.168.0.10:18000/stream?cameraID=64870433':
scrypted  |   Metadata:
scrypted  |     encoder         : Lavf58.29.100
scrypted  |   Duration: 00:00:00.00, start: 765858.398000, bitrate: N/A
scrypted  |   Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 1k tbn
scrypted  |   Stream #0:1: Audio: mp3, 44100 Hz, mono, fltp, 64 kb/s
scrypted  |
scrypted  |
scrypted  | [Intercom Child] Output #0, rtsp, to 'rtsp://127.0.0.1:38957/1b6083c28d8d5469':
scrypted  |   Metadata:
scrypted  |     encoder         : Lavf58.76.100
scrypted  |   Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, q=2-31, 25 fps, 25 tbr, 90k tbn, 1k tbc
scrypted  |   Stream #0:1: Audio: mp3, 44100 Hz, mono, fltp, 64 kb/s
scrypted  | Stream mapping:
scrypted  |   Stream #0:0 -> #0:0 (copy)
scrypted  |   Stream #0:1 -> #0:1 (copy)
scrypted  | Press [q] to stop, [?] for help
scrypted  | frame=    1 fps=0.0 q=-1.0 size=N/A time=00:00:00.00 bitrate=N/A speed=N/A
scrypted  |
scrypted  | [Intercom Child] video/audio detected, discarding further input
scrypted  |
```

and if dowgrate docker to version [18-jammy-lite-v0.93.0](https://hub.docker.com/layers/koush/scrypted/18-jammy-lite-v0.93.0/images/sha256-b4c5efc97ee77af71faea0e7631704e5cc17408b3fe76ee383c1228e0fa2f7c5?context=explore) all work

**Comment by koush** [comment]
Are you using a hostname for this camera or a bare ip

**Comment by twocolors** [comment]
i use
```
http://localhost:18000/stream?cameraID=64870433
```
this url redirect to public stream url

**Comment by koush** [comment]
is the public stream URL a hostname?

also, can you verify it works on full tag?

**Comment by twocolors** [comment]
public stream URL is hostname , add docker tag:full work ... and work [18-jammy-lite-v0.93.0](https://hub.docker.com/layers/koush/scrypted/18-jammy-lite-v0.93.0/images/sha256-b4c5efc97ee77af71faea0e7631704e5cc17408b3fe76ee383c1228e0fa2f7c5?context=explore)

on top i add to logs from lite and full docker tag ... tag **full** work

**Comment by koush** [comment]
ok this is a known issue I'll see if I can fix it

**Comment by koush** [comment]
Changed my mind. No plans to fix this as it would require additional dependencies into lite version which I do not want to maintain. Will be phasing it out and making full image smaller.
