### ISSUE TITLE
Raspberry pi: ffmpeg-linux-arm: Syntax error: newline unexpected

### ISSUE THREAD

**Issue by bondskin** [koush/scrypted#1399]
I see the following error messages constantly (it started a few days ago, most likely related to upgrade to 0.95.0):
```
[TheOffice] motion recording starting
[TheOffice] -hide_banner -analyzeduration 0 -probesize 2597786 -reorder_queue_size 0 -rtsp_transport tcp -f rtsp -i rtsp:[REDACTED] -vcodec copy -acodec copy -bsf:a aac_adtstoasc -movflags frag_keyframe+empty_moov+default_base_moof+skip_sidx+skip_trailer -f mp4 pipe:3
[TheOffice] motion recording started
[TheOffice] /home/pi/.scrypted/node_modules/@scrypted/ffmpeg-static/artifacts/ffmpeg-linux-arm: 8: /home/pi/.scrypted/node_modules/@scrypted/ffmpeg-static/artifacts/ffmpeg-linux-arm: Syntax error: newline unexpected

[TheOffice] motion recording completed Error: stream ended
[HDS ::ffff:192.168.2.147] Delegate finished streaming for 1 without setting RecordingPacket.isLast.         Can't notify Controller about endOfStream!
[HDS ::ffff:192.168.2.147] Delegate finished recording stream 1 without sending anything out.       Controller will CANCEL.
[TheOffice] ffmpeg exited
unhandledRejection Error: 6
    at /@scrypted/homekit/main.nodejs.js:2:1088114
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[TheOffice] motion recording starting
[TheOffice] -hide_banner -analyzeduration 0 -probesize 3401679 -reorder_queue_size 0 -rtsp_transport tcp -f rtsp -i rtsp:[REDACTED] -vcodec copy -acodec copy -bsf:a aac_adtstoasc -movflags frag_keyframe+empty_moov+default_base_moof+skip_sidx+skip_trailer -f mp4 pipe:3
[TheOffice] motion recording started
[TheOffice] /home/pi/.scrypted/node_modules/@scrypted/ffmpeg-static/artifacts/ffmpeg-linux-arm: 8: /home/pi/.scrypted/node_modules/@scrypted/ffmpeg-static/artifacts/ffmpeg-linux-arm: Syntax error: newline unexpected

[TheOffice] motion recording completed Error: stream ended
[HDS ::ffff:192.168.2.147] Delegate finished streaming for 1 without setting RecordingPacket.isLast.         Can't notify Controller about endOfStream!
[HDS ::ffff:192.168.2.147] Delegate finished recording stream 1 without sending anything out.       Controller will CANCEL.
[TheOffice] ffmpeg exited
unhandledRejection Error: 6
    at /@scrypted/homekit/main.nodejs.js:2:1088114
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - OS: Debian
 - Installation Method: local

**Hardware Model (please complete the following information):**
 - Device: Raspberrypi

**Client (please complete the following information, if applicable):**
 - Software: Browser

**Additional context**

**Comment by koush** [comment]
armv7 not supported.

**Comment by RomanGz** [comment]
> armv7 not supported.

WTH - Since what version?

**Comment by koush** [comment]
maintenance stopped on arm7 a year ago.

**Comment by hugoj-goncalves** [comment]
v0.93.0 works fine
