### ISSUE TITLE
Local Hardware Doorbell - Alsa issue

### ISSUE THREAD

**Issue by nitaybz** [koush/scrypted#140]
I've built a doorbell with RPI4,
I'm trying to configure Raspberry Pi Camera Module + USB connected microphone for sound.

I've managed to connect it to Homebridge with following ffmpeg command:
`-f video4linux2 -input_format h264 -video_size 1280x720 -framerate 30 -i /dev/video0 -f alsa -thread_queue_size 8192 -ac 1 -r 25 -i hw:1,0 -r 25 -filter:a volume=5.0`

Now I'm trying to move all to scrypted but I'm stuck i a position where it does not recognize 'alsa' for ffmpeg, what can I do?

Logs:

```
[Rebroadcast Plugin]: restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: prebuffer session started channel0
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -f video4linux2 -input_format h264 -video_size 1280x720 -framerate 30 -i /dev/video0 -f alsa -thread_queue_size 8192 -ac 1 -r 25 -i hw:1,0 -r 25 -filter:a volume=5.0 -vcodec copy -bsf:a aac_adtstoasc -acodec libfdk_aac -profile:a aac_low -flags +global_header -ar 8k -b:a 100k -ac 1 -movflags frag_keyframe+empty_moov+default_base_moof -f mp4 tcp://127.0.0.1:42421 -vcodec copy -bsf:a aac_adtstoasc -acodec libfdk_aac -profile:a aac_low -flags +global_header -ar 8k -b:a 100k -ac 1 -f mpegts tcp://127.0.0.1:40083
[Rebroadcast Plugin]: Input #0, video4linux2,v4l2, from '/dev/video0':
[Rebroadcast Plugin]:   Duration: N/A, start: 12041.375641, bitrate: N/A
[Rebroadcast Plugin]:   Stream #0:0: Video: h264, yuv420p(progressive), 1280x720,
[Rebroadcast Plugin]: 30 fps, 30 tbr, 1000k tbn, 2000k tbc
[Rebroadcast Plugin]: Unknown input format: 'alsa'
[Rebroadcast Plugin]: ffmpeg exited
[Rebroadcast Plugin]: rebroadcast error Error: killed
[Rebroadcast Plugin]:     at ChildProcess.x (/common/src/ffmpeg-rebroadcast.ts:131:34)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:402:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:475:12)
[Rebroadcast Plugin]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
[Rebroadcast Plugin]: prebuffer session ended with error Error: ffmpeg was killed before connecting to the rebroadcast session
[Rebroadcast Plugin]:     at ChildProcess.x (/common/src/ffmpeg-rebroadcast.ts:140:16)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:events:402:35)
[Rebroadcast Plugin]:     at ChildProcess.emit (node:domain:475:12)
[Rebroadcast Plugin]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
[Rebroadcast Plugin]: restarting prebuffer session in 5 seconds
```

**Comment by koush** [comment]
I'll see about building ffmpeg with alsa, but you can also set the SCRYPTED_FFMPEG_PATH environment variable to use a custom ffmpeg instead of the one built in.

**Comment by chip131001** [comment]
Hello nitaybz,
I have a similar configuration.
Did you implement the Dorrbell solution in scrypted?

**Comment by koush** [comment]
people should use a custom ffmpeg if they need to. scrypted will eventually switch to a distribution ffmpeg, which may or may not have alsa.
