### ISSUE TITLE
Openvino failing to start

### ISSUE THREAD

**Issue by netconnectsolutions** [koush/scrypted#1513]
**Describe the bug**
Have had Scrypted nvr running for a while now but the last few days the object detection has stopped working. I have looked at the openvino console and it is showing an error message that it could not start the openvino plugin. I have attached the logs in the screenshots section

**To Reproduce**
1. Go to Plugins
2. At the top of the screen it has the error message

**Expected behavior**
Objects should be detected like usual

**Screenshots**

linux x64 #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-3 (2024-05-02T11:55Z)
server version: 0.114.0
plugin version: @scrypted/openvino 0.1.104
########################
6/28/2024, 7:21:33 AM
########################
python version: python3.10
interpreter: /usr/bin/python3
pip target: /root/.scrypted/volume/plugins/@scrypted/openvino/python3.10-Linux-x86_64-20240317
requirements.txt (up to date)
# must ensure numpy is pinned to prevent dependencies with an unpinned numpy from pulling numpy>=2.0.
numpy==1.26.4
openvino==2024.1.0
Pillow==10.3.0

Available devices:
CPU :
	SUPPORTED_PROPERTIES:
		AVAILABLE_DEVICES: 
		RANGE_FOR_ASYNC_INFER_REQUESTS: 1, 1, 1
		RANGE_FOR_STREAMS: 1, 8
		EXECUTION_DEVICES: CPU
		FULL_DEVICE_NAME:       Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz
		OPTIMIZATION_CAPABILITIES: FP32, FP16, INT8, BIN, EXPORT_IMPORT
		DEVICE_TYPE: Type.INTEGRATED
		DEVICE_ARCHITECTURE: intel64
		NUM_STREAMS: 1
		AFFINITY: Affinity.CORE
		INFERENCE_NUM_THREADS: 0
		PERF_COUNT: False
		INFERENCE_PRECISION_HINT: <Type: 'float32'>
		PERFORMANCE_HINT: PerformanceMode.LATENCY
		EXECUTION_MODE_HINT: ExecutionMode.PERFORMANCE
		PERFORMANCE_HINT_NUM_REQUESTS: 0
		ENABLE_CPU_PINNING: True
		SCHEDULING_CORE_TYPE: SchedulingCoreType.ANY_CORE
		MODEL_DISTRIBUTION_POLICY: set()
		ENABLE_HYPER_THREADING: True
		DEVICE_ID: 
		CPU_DENORMALS_OPTIMIZATION: False
		LOG_LEVEL: Level.NO
		CPU_SPARSE_WEIGHTS_DECOMPRESSION_RATE: 1.0
		DYNAMIC_QUANTIZATION_GROUP_SIZE: 0
		KV_CACHE_PRECISION: <Type: 'float16'>

available devices: ['CPU']
model/mode/precision: scrypted_yolov9t_320/CPU/FP32
Creating directory for /root/.scrypted/volume/plugins/@scrypted/openvino/files/v5/scrypted_yolov9t_320/FP32/best.xml.tmp
Downloading https://github.com/koush/openvino-models/raw/main/scrypted_yolov9t_320/FP32/best.xml
Error downloading https://github.com/koush/openvino-models/raw/main/scrypted_yolov9t_320/FP32/best.xml
Traceback (most recent call last):
  File "/root/.scrypted/volume/plugins/@scrypted/openvino/zip/1-331893b0088c8bed0410dd0770ce5c7a.zip/predict/__init__.py", line 50, in downloadFile
    response = urllib.request.urlopen(url)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
plugin start/fork failed
Traceback (most recent call last):
  File "/root/.scrypted/node_modules/@scrypted/server/python/plugin_remote.py", line 379, in loadZip
    return await self.loadZipWrapped(packageJson, getZip, options)
  File "/root/.scrypted/node_modules/@scrypted/server/python/plugin_remote.py", line 691, in loadZipWrapped
    pluginInstance = await rpc.maybe_await(create_scrypted_plugin())
  File "/root/.scrypted/volume/plugins/@scrypted/openvino/zip/1-331893b0088c8bed0410dd0770ce5c7a.zip/main.py", line 4, in create_scrypted_plugin
    return OpenVINOPlugin()
  File "/root/.scrypted/volume/plugins/@scrypted/openvino/zip/1-331893b0088c8bed0410dd0770ce5c7a.zip/ov/__init__.py", line 153, in __init__
    xmlFile = self.downloadFile(
  File "/root/.scrypted/volume/plugins/@scrypted/openvino/zip/1-331893b0088c8bed0410dd0770ce5c7a.zip/predict/__init__.py", line 50, in downloadFile
    response = urllib.request.urlopen(url)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Server (please complete the following information):**
 - OS: Debian
 - Installation Method: Local

**Hardware Model (please complete the following information):**
 - Device: Reolink Doorbell & Mini POE IP camera

**Client (please complete the following information, if applicable):**
 - Software: [e.g. Home app, NVR app, Alexa, Browser]

**Additional context**

**Comment by koush** [comment]
fixed. looks like you changed a setting at some point that was removed.
