### ISSUE TITLE
Wyze Plugin - after recent core/plugin upgrade cameras says settings fail to load

### ISSUE THREAD

**Issue by kd-koda** [koush/scrypted#1528]
**Describe the bug**
I have Scrypted running as unpriviledge LXC on PVE 8.1.4 with the Wyze Plugin (if I recall correctly the very first version of the plugin)
Things were working fine without a problem so I never upgraded scrypted or the plugin. But recently, auto update seems to have forced an upgrade. 

Now the plugin is throwing an error for each cameras. Example "Hallway Cam Extension settings failed to load."
Camera feed preview in scrypted doesn't work. And the cameras don't have a working video feed in homekit either.
I also use the Ring and FFmpeg Camera Plugin and these devices do not have any issue. 

I have tried several steps to try and fix this including restoring a proxmox backup of the LXC from a few weeks ago. To my surprise, blowing up the LXC, and redeploying from scratch also have the same issue. 

**To Reproduce**
It's happening 100% of the time now for all wyze cameras 

**Expected behavior**
Error shouldn't be there and each camera should have a preview

**Screenshots**
Please see attached screenshot
![Screenshot 2024-07-15 184758](https://github.com/user-attachments/assets/2ccb47d0-b04f-4f01-a815-0156f1c46c4c)

**Server (please complete the following information):**
 - OS: PVE 8.1.4
 - Installation Method: LXC using TTeck proxmox VE helper script

**Hardware Model (please complete the following information):**
 - Device: Wyze Cam V3

**Additional context**
Console log from Plugin:
`linux x64 #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-8 (2024-01-30T12:27Z)
server version: 0.114.0
plugin version: @scrypted/wyze 0.0.52
########################
7/15/2024, 6:05:10 PM
########################
python version: python3.10
interpreter: /root/.scrypted/node_modules/py/python-3.10.14-linux-x86_64/bin/python
pip target: /root/.scrypted/volume/plugins/@scrypted/wyze/python3.10-Linux-x86_64-20240317
requirements.txt (up to date)
pydantic
requests
xxtea

Wyze plugin must be installed under Scrypted for Linux.
Wyze plugin must be installed under Scrypted for Linux.
`

Console log from camera:
`linux x64 #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-8 (2024-01-30T12:27Z)
server version: 0.114.0
plugin version: @scrypted/wyze 0.0.52
########################
7/15/2024, 6:05:10 PM
########################
[Rebroadcast Plugin]: prebuffer sessions starting in 5 seconds
[Rebroadcast Plugin]: Hallway Cam Extension settings failed to load. RPCResultError: device "Unknown Device" is unavailable [id: 24] [mixin: undefined]
[Rebroadcast Plugin]:     at PluginDeviceProxyHandler.applyMixin (/root/.scrypted/node_modules/@scrypted/server/src/plugin/plugin-device.ts:377:23)
[Rebroadcast Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Rebroadcast Plugin]:     at RpcPeer.handleMessageInternal (/root/.scrypted/node_modules/@scrypted/server/src/rpc.ts:759:37)
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin
[Rebroadcast Plugin]: host:@scrypted/prebuffer-mixin {
[Rebroadcast Plugin]:   cause: undefined

**Comment by kd-koda** [comment]
I was able to redeploy and set it all up from scratch using Scrypted Promox VE install script. Not sure why the tteck helper script had the issue. Also not sure what caused the original LXC (tteck helper install script) that was working in the first place to fail.
