### ISSUE TITLE
Wyze - Stream stopped working

### ISSUE THREAD

**Issue by ghostbitmeta** [koush/scrypted#1566]
My Wyze plugin setup suddenly stopped working and I cannot get any stream. Nothing looks obvious from the logs to me. Can anyone else see something I cant?

```
[WebRTC Plugin]: signalingState have-remote-offer
[WebRTC Plugin]: signalingState stable
[WebRTC Plugin]: iceGatheringState gathering
[WebRTC Plugin]: waiting ice connected
[WebRTC Plugin]: iceConnectionState completed
[WebRTC Plugin]: iceGatheringState complete
[WebRTC Plugin]: connectionState connecting
[WebRTC Plugin]: iceConnectionState checking
[WebRTC Plugin]: iceConnectionState connected
[WebRTC Plugin]: connectionState connected
[WebRTC Plugin]: Connection is local network: true 192.168.1.6 {
[WebRTC Plugin]:   ipv4: true,
[WebRTC Plugin]:   type: 'prflx',
[WebRTC Plugin]:   isLocalNetwork: true,
[WebRTC Plugin]:   destinationId: '192.168.1.6'
[WebRTC Plugin]: }
[WebRTC Plugin]: done waiting ice connected
[WebRTC Plugin]: Connection is local network: true 192.168.1.6 {
[WebRTC Plugin]:   ipv4: true,
[WebRTC Plugin]:   type: 'prflx',
[WebRTC Plugin]:   isLocalNetwork: true,
[WebRTC Plugin]:   destinationId: '192.168.1.6'
[WebRTC Plugin]: }
fetching main codec info
Error retrieving codec info
Traceback (most recent call last):

  File "/server/volume/plugins/@scrypted/wyze/zip/1-22567265b22eda7296b6847f55d4fa14.zip/main.py", line 392, in getVideoStream
    codec, sampleRate, sps, pps = await self.probeCodec(False)

  File "/server/volume/plugins/@scrypted/wyze/zip/1-22567265b22eda7296b6847f55d4fa14.zip/main.py", line 309, in probeCodec
    async for audio, data, codec, sampleRate in gen:

  File "/server/volume/plugins/@scrypted/wyze/zip/1-22567265b22eda7296b6847f55d4fa14.zip/main.py", line 352, in gen
    async for payload in await wyzeFork.open_stream(

  File "/server/node_modules/@scrypted/server/python/rpc.py", line 76, in __anext__
    return await RpcProxyMethod(self, self.__dict__[RpcPeer.PROPERTY_PROXY_PROPERTIES]['Symbol(Symbol.asyncIterator)']['next'])()

  File "/server/node_modules/@scrypted/server/python/rpc.py", line 506, in createPendingResult
    return await future

rpc.RPCResultError: (None, 'peer was killed')

[WebRTC Plugin]: Error starting playback for WebRTC track. [Traceback (most recent call last):
[WebRTC Plugin]:   File "/server/node_modules/@scrypted/server/python/rpc.py", line 442, in handleMessage
[WebRTC Plugin]:     value = await maybe_await(invoke(*args))
[WebRTC Plugin]:   File "/server/node_modules/@scrypted/server/python/rpc.py", line 20, in maybe_await
[WebRTC Plugin]:     return await value
[WebRTC Plugin]:   File "/server/volume/plugins/@scrypted/wyze/zip/1-22567265b22eda7296b6847f55d4fa14.zip/main.py", line 392, in getVideoStream
[WebRTC Plugin]:     codec, sampleRate, sps, pps = await self.probeCodec(False)
[WebRTC Plugin]:   File "/server/volume/plugins/@scrypted/wyze/zip/1-22567265b22eda7296b6847f55d4fa14.zip/main.py", line 309, in probeCodec
[WebRTC Plugin]:     async for audio, data, codec, sampleRate in gen:
[WebRTC Plugin]:   File "/server/volume/plugins/@scrypted/wyze/zip/1-22567265b22eda7296b6847f55d4fa14.zip/main.py", line 352, in gen
[WebRTC Plugin]:     async for payload in await wyzeFork.open_stream(
[WebRTC Plugin]:   File "/server/node_modules/@scrypted/server/python/rpc.py", line 76, in __anext__
[WebRTC Plugin]:     return await RpcProxyMethod(self, self.__dict__[RpcPeer.PROPERTY_PROXY_PROPERTIES]['Symbol(Symbol.asyncIterator)']['next'])()
[WebRTC Plugin]:   File "/server/node_modules/@scrypted/server/python/rpc.py", line 506, in createPendingResult
[WebRTC Plugin]:     return await future
[WebRTC Plugin]: rpc.RPCResultError: (None, 'peer was killed')
[WebRTC Plugin]: 
[WebRTC Plugin]: @scrypted/wyze:host
[WebRTC Plugin]: host:@scrypted/webrtc] {
[WebRTC Plugin]:   cause: undefined
[WebRTC Plugin]: }
[WebRTC Plugin]: signalingState closed
[WebRTC Plugin]: connectionState closed
[WebRTC Plugin]: iceConnectionState closed
```

**Comment by goin3d2** [comment]
I’m getting the exact same on a new Wyze cam battery, but the stream is working for a Wyze pan camera. What camera are you using?  Have you made any progress?

**Comment by ghostbitmeta** [comment]
> I’m getting the exact same on a new Wyze cam battery, but the stream is working for a Wyze pan camera. What camera are you using? Have you made any progress?

I'n using an old V2. I tried recreating new API key and reinstalling the plugin, but still can't get it working again.

**Comment by VACIndustries** [comment]
Having the same issue.  Curious why it was closed with no response
