### ISSUE TITLE
HomeKit two-way audio not working with DS-KD8003

### ISSUE THREAD

**Issue by kargie** [koush/scrypted#1580]
I was having trouble with getting HomeKit two-way audio working with my Hikvison doorbell.

My configurations

- Hikvision doorbell DS-KD8003, firmware v2.2.62 build 230204, encoding version v4.0 build 181206
- AppleTV gen3
- iphone se gen3
- Proxmox 8.2 
- Scrypted v0.118.0,
- plugins:
![image](https://github.com/user-attachments/assets/008d9b5d-fbfa-4487-b7ae-c50a3524e13a)

case 1 with hikvision 
![image](https://github.com/user-attachments/assets/84cf86c3-398b-4e1c-9c33-213ef6692bcb)

When I tried to active two-way audio I got errors in my logs:
[HomeKit]: intercom failed to start RPCResultError: Did not find WWW-Authenticate header.
[HomeKit]:     at eval (/packages/auth-fetch/src/auth-fetch.ts:122:19)
[HomeKit]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[HomeKit]:     at t.HikvisionCameraAPI.body [as request] (/src/hikvision-camera-api.ts:82:9)
[HomeKit]:     at S.startIntercom (/src/main.ts:538:17)
[HomeKit]:     at RpcPeer.handleMessageInternal (/root/.scrypted/node_modules/@scrypted/server/src/rpc.ts:744:37)
[HomeKit]: @scrypted/hikvision:host
[HomeKit]: host:@scrypted/homekit {
[HomeKit]:   cause: undefined
[HomeKit]: }

case 2 with ONVIF
[HomeKit]: intercom failed to start RPCResultError: ONVIF audio backchannel not found
[HomeKit]:     at t.OnvifIntercom.checkIntercom (/onvif/src/onvif-intercom.ts:40:19)
[HomeKit]:     at process.intercomClient (node:internal/process/task_queues:95:5)
[HomeKit]:     at t.OnvifIntercom.startIntercom (/onvif/src/onvif-intercom.ts:50:35)
[HomeKit]:     at RpcPeer.handleMessageInternal (/root/.scrypted/node_modules/@scrypted/server/src/rpc.ts:744:37)
[HomeKit]: @scrypted/hikvision:host
[HomeKit]: host:@scrypted/homekit {
[HomeKit]:   cause: undefined
[HomeKit]: } 

I keep seeing the following messages in the console
listen loop connection failed, restarting listener. Did not find WWW-Authenticate header.
listen loop connection failed, restarting listener. Did not find WWW-Authenticate header.
listen loop connection failed, restarting listener. Did not find WWW-Authenticate header.

I think that something is wrong in packages/auth-fetch/src/auth-fetch.ts. 
please help me solve the problem, thx.

**Comment by KeryanB** [comment]
Hello, I am having the same issue, no fix?

**Comment by iHunterX** [comment]
`listen loop connection failed, restarting listener. Did not find WWW-Authenticate header.`

Im having the same issue, I think its because door bell doesnt have Digest/Basic Auth

but do we have to live with it?
