### ISSUE TITLE
HomeKit Remote Streaming (G4 Doorbell)

### ISSUE THREAD

**Issue by Mixpower** [koush/scrypted#163]
I can't get the HomeKit Remote Streaming working on my G4 Doorbell.
When I'm at home it works great through the Home app, but when I'm not home I can see the recordings but live view I always get a timeout.

I already put Livestream (hub) on low and it still does not work, I even enabled transcoding on the remote stream without any change.

This is the console output I get on my G4 Doorbell when I start live view from my iPhone.

```
[HomeKit]: streaming request {
[HomeKit]:   sessionID: 'b3f08b5f-d80d-484b-a58c-7ab0314c0b25',
[HomeKit]:   type: 'start',
[HomeKit]:   video: {
[HomeKit]:     codec: 0,
[HomeKit]:     profile: 1,
[HomeKit]:     level: 2,
[HomeKit]:     packetizationMode: 0,
[HomeKit]:     cvoId: undefined,
[HomeKit]:     width: 1280,
[HomeKit]:     height: 720,
[HomeKit]:     fps: 30,
[HomeKit]:     pt: 99,
[HomeKit]:     ssrc: 870980242,
[HomeKit]:     max_bit_rate: 299,
[HomeKit]:     rtcp_interval: 0.5,
[HomeKit]:     mtu: 1378
[HomeKit]:   },
[HomeKit]:   audio: {
[HomeKit]:     codec: 'AAC-eld',
[HomeKit]:     channel: 1,
[HomeKit]:     bit_rate: 0,
[HomeKit]:     sample_rate: 24,
[HomeKit]:     packet_time: 30,
[HomeKit]:     pt: 110,
[HomeKit]:     ssrc: 2038620282,
[HomeKit]:     max_bit_rate: 24,
[HomeKit]:     rtcp_interval: 5,
[HomeKit]:     comfort_pt: 13,
[HomeKit]:     comfortNoiseEnabled: false
[HomeKit]:   }
[HomeKit]: }
[HomeKit]: isHomeKitHub true selected stream Low
[HomeKit]: fetching video stream
[Rebroadcast Plugin]: Low prebuffer session started
[Rebroadcast Plugin]: -hide_banner -fflags +genpts -rtsp_transport tcp -max_delay 1000000 -i rtsp:[REDACTED] -vcodec copy -acodec copy -bsf:a aac_adtstoasc -movflags frag_keyframe+empty_moov+default_base_moof -f mp4 pipe:[REDACTED] -vcodec copy -acodec copy -bsf:a aac_adtstoasc -f mpegts pipe:[REDACTED] -sdp_file pipe:[REDACTED]
[Rebroadcast Plugin]: Input #0, rtsp, from 'rtsp://10.0.1.1:7447/3hW8Lji0sB6Xf47O':
[Rebroadcast Plugin]:   Metadata:
[Rebroadcast Plugin]:     title           : 74ACB99EF5CD_2
[Rebroadcast Plugin]:   Duration: N/A, start: 0.000000, bitrate: N/A
[Rebroadcast Plugin]: Stream #0:0: Audio: aac, 48000 Hz, mono, fltp
[Rebroadcast Plugin]:   Stream #0:1: Video: h264, yuvj420p(pc, bt709, progressive), 480x360 [SAR 1:1 DAR 4:3], 24 fps, 45 tbr, 90k tbn, 48 tbc
[Rebroadcast Plugin]: Output #0, mp4, to 'pipe:3':
[Rebroadcast Plugin]:   Metadata:
[Rebroadcast Plugin]:     title           : 74ACB99EF5CD_2
[Rebroadcast Plugin]:     encoder         : Lavf58.76.100
[Rebroadcast Plugin]:   Stream #0:0: Video: h264 (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 480x360 [SAR 1:1 DAR 4:3], q=2-31, 24 fps, 45 tbr, 90k tbn, 90k tbc
[Rebroadcast Plugin]:   Stream #0:1: Audio: aac (mp4a / 0x6134706D), 48000 Hz, mono, fltp
[Rebroadcast Plugin]: Detected audio codec is mp4/mpegts compatible. aac
[Rebroadcast Plugin]: Low prebuffer request started
[Rebroadcast Plugin]: Output #1, mpegts, to 'pipe:4':
[Rebroadcast Plugin]:   Metadata:
[Rebroadcast Plugin]:     title           : 74ACB99EF5CD_2
[Rebroadcast Plugin]:     encoder         : Lavf58.76.100
[Rebroadcast Plugin]:   Stream #1:0: Video: h264, yuvj420p(pc, bt709, progressive), 480x360 [SAR 1:1 DAR 4:3], q=2-31, 24 fps, 45 tbr, 90k tbn, 90k tbc
[Rebroadcast Plugin]:   Stream #1:1: Audio: aac, 48000 Hz, mono, fltp
[Rebroadcast Plugin]: Stream mapping:
[Rebroadcast Plugin]:   Stream #0:1 -> #0:0 (copy)
[Rebroadcast Plugin]:   Stream #0:0 -> #0:1 (copy)
[Rebroadcast Plugin]:   Stream #0:1 -> #1:0 (copy)
[Rebroadcast Plugin]:   Stream #0:0 -> #1:1 (copy)
[Rebroadcast Plugin]: Press [q] to stop, [?] for help
[Rebroadcast Plugin]: frame=    0 fps=0.0 q=-1.0 q=-1.0 size=       1kB time=00:00:00.00 bitrate=N/A speed=   0x
[Rebroadcast Plugin]: video/audio detected, discarding further input
[HomeKit]: -hide_banner -analyzeduration 0 -probesize 500000 -f mpegts -i tcp:[REDACTED] -f lavfi -i anullsrc=cl=1 -shortest -an -sn -dn -vcodec copy -payload_type 99 -ssrc 5413190 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params TEzeorAuNXXrEk21qegMmR7yVDB0TOns46+jjyHP srtp:[REDACTED] -vn -sn -dn -acodec libfdk_aac -profile:a aac_eld -flags +global_header -ar 24k -b:a 24k -bufsize 96k -ac 1 -payload_type 110 -ssrc 5202646 -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params RuUSNuMLmwCM2McxtNSGzFh2Hf42uU7wDOuLm0T8 -fflags +flush_packets -flush_packets 1 -f rtp srtp:[REDACTED]
[HomeKit]: ffmpeg /server/node_modules/@scrypted/ffmpeg/ffmpeg-debian-arm-v1.0.6
[Rebroadcast Plugin]: Low active rebroadcast clients: 1
starting 2 way audio [
  '-protocol_whitelist',
  'pipe,udp,rtp,file,crypto,tcp',
  '-acodec',
  'libfdk_aac',
  '-ac',
  '1',
  '-f',
  'sdp',
  '-i',
  'tcp://127.0.0.1:41871',
  '-acodec',
  'libfdk_aac',
  '-profile:a',
  'aac_low',
  '-threads',
  '0',
  '-avioflags',
  'direct',
  '-max_delay',
  '1000000',
  '-flush_packets',
  '1',
  '-flags',
  '+global_header',
  '-ar',
  '22050',
  '-ac',
  '1',
  '-b:a',
  '16k',
  '-f',
  'adts',
  'tcp://127.0.0.1:39399'
]
ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-nonfree --enable-gpl --enable-openssl --enable-libdav1d --enable-libx264 --enable-libx265 --enable-libvpx --enable-libxvid --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libfdk-aac --enable-libwebp --enable-libsrt --disable-debug --disable-doc --disable-shared --disable-sdl2 --disable-libxcb --enable-pthreads --enable-static --enable-small --enable-version3 --extra-cflags=-I/ffmpeg-build-script/workspace/include --extra-ldexeflags= --extra-ldflags=-L/ffmpeg-build-script/workspace/lib --extra-libs='-ldl -lpthread -lm -lz' --pkgconfigdir=/ffmpeg-build-script/workspace/lib/pkgconfig --pkg-config-flags=--static --prefix=/ffmpeg-build-script/workspace --extra-version=
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100

[udp @ 0x2bf9020] attempted to set receive buffer to size 393216 but it only ended up set as 360448

[udp @ 0x2bf9190] attempted to set receive buffer to size 393216 but it only ended up set as 360448

[HomeKit]: Input #0, mpegts, from 'tcp://127.0.0.1:46179':
[HomeKit]:   Duration: N/A, start: 1.400000, bitrate: N/A
[HomeKit]:   Program 1 
[HomeKit]:     Metadata:
[HomeKit]:       service_name    : 74ACB99EF5CD_2
[HomeKit]:       service_provider:
[HomeKit]: FFmpeg
[HomeKit]:   Stream #0:0[0x100]: Video: h264 ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709, progressive), 480x360 [SAR 1:1 DAR 4:3], 24 fps, 45 tbr, 90k tbn, 48 tbc
[HomeKit]:   Stream #0:1[0x101]: Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, mono, fltp, 63 kb/s
[HomeKit]: Input #1, lavfi, from 'anullsrc=cl=1':
[HomeKit]:   Duration: N/A, start: 0.000000, bitrate: 352 kb/s
[HomeKit]:   Stream #1:0: Audio: pcm_u8, 44100 Hz, 1 channels (FL), u8, 352 kb/s
[HomeKit]: Output #0, rtp, to 'srtp://10.0.1.93:55876?rtcpport=55876&pkt_size=1378':
[HomeKit]:   Metadata:
[HomeKit]:     encoder         : Lavf58.76.100
[HomeKit]:   Stream #0:0: Video: h264 ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709, progressive), 480x360 [SAR 1:1 DAR 4:3], q=2-31,
[HomeKit]: video/audio detected, discarding further input
[HomeKit]: SDP:
[HomeKit]: v=0
[HomeKit]: o=- 0 0 IN IP4 127.0.0.1
[HomeKit]: s=No Name
[HomeKit]: t=0 0
[HomeKit]: a=tool:libavformat 58.76.100
[HomeKit]: m=video 55876 RTP/AVP 99
[HomeKit]: c=IN IP4 10.0.1.93
[HomeKit]: a=rtpmap:99 H264/90000
[HomeKit]: a=fmtp:99 packetization-mode=1; sprop-parameter-sets=Z01AFY2NQPBf8uAtwEBAUAAAPoAAC7gJ2giEag==,aO44gAA=; profile-level-id=4D4015
[HomeKit]: a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:TEzeorAuNXXrEk21qegMmR7yVDB0TOns46+jjyHP
[HomeKit]: m=audio 64789 RTP/AVP 110
[HomeKit]: c=IN IP4 10.0.1.93
[HomeKit]: b=AS:24
[HomeKit]: a=rtpmap:110 MPEG4-GENERIC/24000/1
[HomeKit]: a=fmtp:110 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=F8EC2126A000
[HomeKit]: a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:RuUSNuMLmwCM2McxtNSGzFh2Hf42uU7wDOuLm0T8
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, sdp, from 'tcp://127.0.0.1:41871':
  Metadata:
    title           : HomeKit Audio Talkback
  Duration: N/A, bitrate: N/A

  Stream #0:0: Audio: aac, 16000 Hz, mono, s16

sending audio data to wss://10.0.1.1:7443/ws/talkback?uniqid=ws-d1d15446-6023-4680-8a5b-ad637285525a
Stream mapping:
  Stream #0:0 -> #0:0 (aac (libfdk_aac) -> aac (libfdk_aac))
Press [q] to stop, [?] for help

[HomeKit]: streaming request { sessionID: 'b3f08b5f-d80d-484b-a58c-7ab0314c0b25', type: 'stop' }
[HomeKit]: streaming session killed
[HomeKit]: rtp sink closed
[Rebroadcast Plugin]: Low active rebroadcast clients: 0
[Rebroadcast Plugin]: Low prebuffer request ended
[HomeKit]: ffmpeg exited
tcp://127.0.0.1:41871: Connection timed out
Finishing stream 0:0 without any data written to it.

Output #0, adts, to 'tcp://127.0.0.1:39399':
  Metadata:
    title           : HomeKit Audio Talkback
    encoder         : Lavf58.76.100

  Stream #0:0: Audio: aac, 22050 Hz, mono, s16, 16 kb/s
    Metadata:
      encoder         : Lavc58.134.100 libfdk_aac
[libfdk_aac @ 0x2c210a0] Trying to remove 1024 samples, but the queue is empty
    Last message repeated 1 times
size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

video/audio detected, discarding further input
ffmpeg exited
[Rebroadcast Plugin]: Low terminating rebroadcast due to inactivity
[Rebroadcast Plugin]: rebroadcast error Error: killed
[Rebroadcast Plugin]:     at Object.kill (/common/src/ffmpeg-rebroadcast.ts:114:34)
[Rebroadcast Plugin]:     at Timeout._onTimeout (/src/main.ts:518:15)
[Rebroadcast Plugin]:     at listOnTimeout (node:internal/timers:557:17)
[Rebroadcast Plugin]:     at processTimers (node:internal/timers:500:7)
[Rebroadcast Plugin]: rebroadcast parse error Error: stream ended during read for minimum 8 bytes
[Rebroadcast Plugin]:     at Socket.n (/common/src/read-stream.ts:26:20)
[Rebroadcast Plugin]:     at Socket.emit (node:events:402:35)
[Rebroadcast Plugin]:     at Socket.emit (node:domain:475:12)
[Rebroadcast Plugin]:     at endReadableNT (node:internal/streams/readable:1343:12)
[Rebroadcast Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[Rebroadcast Plugin]: ffmpeg exited
```

I can't figure out what the issue is, I tried many settings but there's no change.

**Comment by koush** [comment]
set your remote hub stream to a lower resolution stream.
