### ISSUE TITLE
ONVIF SOAP Fault: {"value":"SOAP-ENV:Sender"} with 2N intercom

### ISSUE THREAD

**Issue by longzheng** [koush/scrypted#1655]
**Describe the bug**
Noticed this error in my ONVIF camera device logs (2N Intercom). I suspect it's also related to an issue with the motion trigger not working correctly.

```
<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope       ><SOAP-ENV:Body><tev:GetEventPropertiesResponse><tev:TopicNamespaceLocation>http://www.onvif.org/onvif/ver10/topics/topicns.xml</tev:TopicNamespaceLocation><wsnt:FixedTopicSet>true</wsnt:FixedTopicSet><wstop:TopicSet><tns1:Device><Trigger><DigitalInput wstop:topic="true"><tt:MessageDescription IsProperty="true"><tt:Source><tt:SimpleItemDescription Name="InputToken" Type="tt:ReferenceToken"></tt:SimpleItemDescription></tt:Source><tt:Data><tt:SimpleItemDescription Name="LogicalState" Type="xs:boolean"></tt:SimpleItemDescription></tt:Data></tt:MessageDescription></DigitalInput><Relay wstop:topic="true"><tt:MessageDescription IsProperty="true"><tt:Source><tt:SimpleItemDescription Name="RelayToken" Type="tt:ReferenceToken"></tt:SimpleItemDescription></tt:Source><tt:Data><tt:SimpleItemDescription Name="LogicalState" Type="tt:RelayLogicalState"></tt:SimpleItemDescription></tt:Data></tt:MessageDescription></Relay></Trigger></tns1:Device><tns1:VideoSource><MotionAlarm wstop:topic="true"><tt:MessageDescription IsProperty="true"><tt:Source><tt:SimpleItemDescription Name="Source" Type="tt:ReferenceToken"></tt:SimpleItemDescription></tt:Source><tt:Data><tt:SimpleItemDescription Name="State" Type="xs:boolean"></tt:SimpleItemDescription></tt:Data></tt:MessageDescription></MotionAlarm><GlobalSceneChange><ImagingService wstop:topic="true"><tt:MessageDescription IsProperty="true"><tt:Source><tt:SimpleItemDescription Name="Source" Type="tt:ReferenceToken"></tt:SimpleItemDescription></tt:Source><tt:Data><tt:SimpleItemDescription Name="State" Type="xs:boolean"></tt:SimpleItemDescription></tt:Data></tt:MessageDescription></ImagingService></GlobalSceneChange></tns1:VideoSource><tns1:Media><ProfileChanged wstop:topic="true"><tt:MessageDescription><tt:Source><tt:SimpleItemDescription Name="Token" Type="tt:ReferenceToken"></tt:SimpleItemDescription></tt:Source></tt:MessageDescription></ProfileChanged><ConfigurationChanged wstop:topic="true"><tt:MessageDescription><tt:Source><tt:SimpleItemDescription Name="Token" Type="tt:ReferenceToken"></tt:SimpleItemDescription><tt:SimpleItemDescription Name="Type" Type="xs:string"></tt:SimpleItemDescription></tt:Source></tt:MessageDescription></ConfigurationChanged></tns1:Media></wstop:TopicSet><wsnt:TopicExpressionDialect>http://docs.oasis-open.org/wsn/t-1/TopicExpression/Concrete</wsnt:TopicExpressionDialect><wsnt:TopicExpressionDialect>http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet</wsnt:TopicExpressionDialect><tev:MessageContentFilterDialect>http://www.onvif.org/ver10/tev/messageContentFilter/ItemFilter</tev:MessageContentFilterDialect><tev:MessageContentSchemaLocation>http://www.onvif.org/ver10/schema/onvif.xsd</tev:MessageContentSchemaLocation></tev:GetEventPropertiesResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>
Camera supports WSPullPoint <?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope   ><SOAP-ENV:Body><tds:GetCapabilitiesResponse><tds:Capabilities><tt:Device><tt:XAddr>http://192.168.1.3/onvif/device_service</tt:XAddr><tt:Network><tt:IPFilter>false</tt:IPFilter><tt:ZeroConfiguration>false</tt:ZeroConfiguration><tt:IPVersion6>false</tt:IPVersion6><tt:DynDNS>false</tt:DynDNS><tt:Extension><tt:Dot11Configuration>false</tt:Dot11Configuration></tt:Extension></tt:Network><tt:System><tt:DiscoveryResolve>true</tt:DiscoveryResolve><tt:DiscoveryBye>true</tt:DiscoveryBye><tt:RemoteDiscovery>true</tt:RemoteDiscovery><tt:SystemBackup>false</tt:SystemBackup><tt:SystemLogging>false</tt:SystemLogging><tt:FirmwareUpgrade>false</tt:FirmwareUpgrade><tt:SupportedVersions><tt:Major>21</tt:Major><tt:Minor>6</tt:Minor></tt:SupportedVersions><tt:Extension><tt:HttpFirmwareUpgrade>false</tt:HttpFirmwareUpgrade><tt:HttpSystemBackup>false</tt:HttpSystemBackup><tt:HttpSystemLogging>false</tt:HttpSystemLogging><tt:HttpSupportInformation>false</tt:HttpSupportInformation></tt:Extension></tt:System><tt:IO><tt:InputConnectors>13</tt:InputConnectors><tt:RelayOutputs>7</tt:RelayOutputs></tt:IO><tt:Security><tt:TLS1.1>true</tt:TLS1.1><tt:TLS1.2>true</tt:TLS1.2><tt:OnboardKeyGeneration>true</tt:OnboardKeyGeneration><tt:AccessPolicyConfig>false</tt:AccessPolicyConfig><tt:X.509Token>false</tt:X.509Token><tt:SAMLToken>false</tt:SAMLToken><tt:KerberosToken>false</tt:KerberosToken><tt:RELToken>false</tt:RELToken><tt:Extension><tt:TLS1.0>true</tt:TLS1.0><tt:Extension><tt:Dot1X>false</tt:Dot1X><tt:SupportedEAPMethod>0</tt:SupportedEAPMethod><tt:RemoteUserHandling>false</tt:RemoteUserHandling></tt:Extension></tt:Extension></tt:Security></tt:Device><tt:Events><tt:XAddr>http://192.168.1.3/onvif/device_service</tt:XAddr><tt:WSSubscriptionPolicySupport>true</tt:WSSubscriptionPolicySupport><tt:WSPullPointSupport>true</tt:WSPullPointSupport><tt:WSPausableSubscriptionManagerInterfaceSupport>false</tt:WSPausableSubscriptionManagerInterfaceSupport></tt:Events><tt:Imaging><tt:XAddr>http://192.168.1.3/onvif/device_service</tt:XAddr></tt:Imaging><tt:Media><tt:XAddr>http://192.168.1.3/onvif/device_service</tt:XAddr><tt:StreamingCapabilities><tt:RTPMulticast>true</tt:RTPMulticast><tt:RTP_TCP>true</tt:RTP_TCP><tt:RTP_RTSP_TCP>true</tt:RTP_RTSP_TCP></tt:StreamingCapabilities><tt:Extension><tt:ProfileCapabilities><tt:MaximumNumberOfProfiles>12</tt:MaximumNumberOfProfiles></tt:ProfileCapabilities></tt:Extension></tt:Media><tt:Extension><tt:DeviceIO><tt:XAddr>http://192.168.1.3/onvif/device_service</tt:XAddr><tt:VideoSources>1</tt:VideoSources><tt:VideoOutputs>0</tt:VideoOutputs><tt:AudioSources>1</tt:AudioSources><tt:AudioOutputs>1</tt:AudioOutputs><tt:RelayOutputs>7</tt:RelayOutputs></tt:DeviceIO></tt:Extension></tds:Capabilities></tds:GetCapabilitiesResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>
createSubscription error Error: ONVIF SOAP Fault: {"value":"SOAP-ENV:Sender"}
    at cb (C:\node_modules\onvif\lib\utils.js:101:13)
    at o.eval (C:\node_modules\xml2js\lib\parser.js:318:18)
    at o.emit (node:events:518:28)
    at o.emit (node:domain:489:12)
    at r.event [as onclosetag] (C:\node_modules\xml2js\lib\parser.js:276:26)
    at emit (C:\node_modules\sax\lib\sax.js:624:29)
    at emitNode (C:\node_modules\sax\lib\sax.js:629:5)
    at closeTag (C:\node_modules\sax\lib\sax.js:889:7)
    at r.write (C:\node_modules\sax\lib\sax.js:1436:13)
    at o.parseString (C:\node_modules\xml2js\lib\parser.js:337:31)
listen loop connection failed, restarting listener. ONVIF SOAP Fault: {"value":"SOAP-ENV:Sender"}
```

This error seems to loop forever (I think it keeps retrying).

I believe restarting the device somehow fixes it.

I will investigate more with debugging tools later.

**To Reproduce**
N/A

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - OS: Windows
 - Installation Method: Local

**Hardware Model (please complete the following information):**
 - Device: [2N IP Solo](https://www.2n.com/en-US/products/intercoms/2n-ip-solo/)

**Client (please complete the following information, if applicable):**
N/A

**Additional context**

**Comment by koush** [comment]
very likely a device side issue with busted onvif implementation.
