### ISSUE TITLE
Google Device Access Something went wrong

### ISSUE THREAD

**Issue by jonnylangefeld** [koush/scrypted#171]
Hi, I followed [all the steps in the google-device-access plugin readme](https://github.com/koush/scrypted/tree/main/plugins/google-device-access). I'm logged in to scrypted cloud with my google account, I have a Device Access Console project configured with the client ID from the oauth credential, I put in the project ID, oauth ID and oauth secret into the UI on scrypted. When I click login, then select my user account on the google UI, I get this as the next screen:
![Screen Shot 2022-02-13 at 9 18 57 AM](https://user-images.githubusercontent.com/18717376/153766767-e114bd28-946d-47e5-a747-cc43234d850c.png)

Scrypted logs just say this (no surprise there):
```
Error: Missing token. Please log in.
    at GoogleSmartDeviceAccess.loadToken (/src/main.ts:675:19)
    at GoogleSmartDeviceAccess.authGet (/src/main.ts:714:20)
    at GoogleSmartDeviceAccess.apply (/src/main.ts:510:37)
    at invokeFunc (/node_modules/lodash/debounce.js:95:19)
    at trailingEdge (/node_modules/lodash/debounce.js:144:14)
    at Timeout.w [as _onTimeout] (/node_modules/lodash/debounce.js:132:14)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**Comment by jonnylangefeld** [comment]
If anyone else stumbles upon this: I made the mistake and copied the google project ID into the project ID field instead of the Google Device Access project ID. While that's confusing, the scrypted UI actually clearly says "Google Device Access Project ID", so that was my bad
