### ISSUE TITLE
Error thrown on Raspbian Docker installation

### ISSUE THREAD

**Issue by adamnpeace** [koush/scrypted#182]
Hi, firstly thank you for the great project - I have it running at my home on a Docker instance and it works amazingly. I'm trying to install on a Raspberry Pi 3 in my parents home and having an issue.

I followed all the instructions for the docker install and when I set up username/password in console and try to log in, I'm seeing this in my logs:

```
installing package @scrypted/core 0.0.197
downloaded tarball 5731716
parsing entry package/package.json
parsing entry package/README.md
parsing entry package/dist/main.nodejs.js.LICENSE.txt
parsing entry package/dist/plugin.zip
npm package files: package/package.json, package/README.md, package/dist/main.nodejs.js.LICENSE.txt, package/dist/plugin.zip
@scrypted/core auto install failed Error: Could not extract the file
    at /server/node_modules/adm-zip/adm-zip.js:620:27
    at Array.forEach (<anonymous>)
    at Object.extractAllTo (/server/node_modules/adm-zip/adm-zip.js:604:26)
    at new PluginHost (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:153:24)
    at ScryptedRuntime.runPlugin (/server/node_modules/@scrypted/server/src/runtime.ts:532:28)
    at ScryptedRuntime.installPlugin (/server/node_modules/@scrypted/server/src/runtime.ts:490:21)
    at ScryptedRuntime.getPluginForEndpoint (/server/node_modules/@scrypted/server/src/runtime.ts:186:34)
    at ScryptedRuntime.getEndpointPluginData (/server/node_modules/@scrypted/server/src/runtime.ts:245:21)
    at ScryptedRuntime.endpointHandler (/server/node_modules/@scrypted/server/src/plugin/plugin-http.ts:70:28)
TypeError: Cannot read properties of undefined (reading 'io')
    at ScryptedRuntime.handleEngineIOEndpoint (/server/node_modules/@scrypted/server/src/runtime.ts:338:24)
    at ScryptedRuntime.endpointHandler (/server/node_modules/@scrypted/server/src/plugin/plugin-http.ts:109:17)
```

**Comment by koush** [comment]
Thanks for the stack trace, will fix.

**Comment by koush** [comment]
https://github.com/koush/scrypted/commit/a159d58fee538cf5b4ed2e315446a8983fe646fd

**Comment by koush** [comment]
new docker build in progress

**Comment by adamnpeace** [comment]
Pulled the latest version. It seems to be working past the previous error, but now its throwing elsewhere:
```
installing package @scrypted/core 0.0.197
downloaded tarball 5731716
parsing entry package/package.json
parsing entry package/README.md
parsing entry package/dist/main.nodejs.js.LICENSE.txt
parsing entry package/dist/plugin.zip
npm package files: package/package.json, package/README.md, package/dist/main.nodejs.js.LICENSE.txt, package/dist/plugin.zip
@scrypted/core auto install failed Error: Could not extract the file
    at /server/node_modules/adm-zip/adm-zip.js:620:27
    at Array.forEach (<anonymous>)
    at Object.extractAllTo (/server/node_modules/adm-zip/adm-zip.js:604:26)
    at new PluginHost (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:153:24)
    at ScryptedRuntime.runPlugin (/server/node_modules/@scrypted/server/src/runtime.ts:539:28)
    at ScryptedRuntime.installPlugin (/server/node_modules/@scrypted/server/src/runtime.ts:497:21)
    at ScryptedRuntime.getPluginForEndpoint (/server/node_modules/@scrypted/server/src/runtime.ts:186:34)
    at ScryptedRuntime.getEndpointPluginData (/server/node_modules/@scrypted/server/src/runtime.ts:245:21)
    at ScryptedRuntime.endpointHandler (/server/node_modules/@scrypted/server/src/plugin/plugin-http.ts:70:28)
plugin does not exist or is still starting up.
installing package @scrypted/core 0.0.197
downloaded tarball 5731716
parsing entry package/package.json
parsing entry package/README.md
parsing entry package/dist/main.nodejs.js.LICENSE.txt
parsing entry package/dist/plugin.zip
npm package files: package/package.json, package/README.md, package/dist/main.nodejs.js.LICENSE.txt, package/dist/plugin.zip
@scrypted/core auto install failed Error: Could not extract the file
    at /server/node_modules/adm-zip/adm-zip.js:620:27
    at Array.forEach (<anonymous>)
    at Object.extractAllTo (/server/node_modules/adm-zip/adm-zip.js:604:26)
    at new PluginHost (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:153:24)
    at ScryptedRuntime.runPlugin (/server/node_modules/@scrypted/server/src/runtime.ts:539:28)
    at ScryptedRuntime.installPlugin (/server/node_modules/@scrypted/server/src/runtime.ts:497:21)
    at ScryptedRuntime.getPluginForEndpoint (/server/node_modules/@scrypted/server/src/runtime.ts:186:34)
    at ScryptedRuntime.getEndpointPluginData (/server/node_modules/@scrypted/server/src/runtime.ts:245:21)
    at ScryptedRuntime.endpointHandler (/server/node_modules/@scrypted/server/src/plugin/plugin-http.ts:70:28)
TypeError: Cannot read properties of undefined (reading 'unzippedPath')
    at ScryptedRuntime.handleRequestEndpoint (/server/node_modules/@scrypted/server/src/runtime.ts:356:84)
    at ScryptedRuntime.endpointHandler (/server/node_modules/@scrypted/server/src/plugin/plugin-http.ts:109:17)
```

**Comment by koush** [comment]
can you `rm -rf ~/.scrypted/volume` and try again?
wondering if you got into a weird state.

**Comment by adamnpeace** [comment]
Closing as I believe the instance was on Debian Buster. Tried the same method on Bullseye with no problems.

Would love to see Buster support in future though - now I need 2 Raspberry Pi's, one to run Unifi Controller (requires Buster) and one to run Scrypted

**Comment by koush** [comment]
you can use scrypted:16 on docker for buster support, or apparently update some buster kernel/libs on your installation. or run unifi controller in docker itself.
