### ISSUE TITLE
error starting plugin @scrypted/core Error: Could not extract the file

### ISSUE THREAD

**Issue by banjohb** [koush/scrypted#187]
Need help - installed via docker on raspberry pi 3B - what is the problem?

error starting plugin @scrypted/core Error: Could not extract the file,
    at /server/node_modules/adm-zip/adm-zip.js:620:27,
    at Array.forEach (<anonymous>),
    at Object.extractAllTo (/server/node_modules/adm-zip/adm-zip.js:604:26),
    at new PluginHost (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:177:24),
    at ScryptedRuntime.runPlugin (/server/node_modules/@scrypted/server/src/runtime.ts:539:28),
    at ScryptedRuntime.start (/server/node_modules/@scrypted/server/src/runtime.ts:746:22),
    at processTicksAndRejections (node:internal/process/task_queues:96:5),
    at start (/server/node_modules/@scrypted/server/src/scrypted-server-main.ts:216:5),
#######################################################,
Scrypted Server (Local)   : https://localhost:10443/,
Scrypted Server (Remote)  : https://100.10.1.50:10443/,
Scrypted Server (Remote)  : https://fd2f:16e2:bfcc:4d84:6135:7fec:5db3:d0ef:10443/,
Scrypted Server (Remote)  : https://fd2f:16e2:bfcc:4d84:7d8a:4ac8:e927:814f:10443/,
Scrypted Server (Remote)  : https://fe80::9ce8:7291:8278:525f:10443/,
Version:       : 0.0.148,
#######################################################,
Chrome Users: You may need to type "thisisunsafe" into,
              the window to bypass the warning. There,
              may be no button to continue, type the,
              letters "thisisunsafe" and it will proceed.,
#######################################################,
Scrypted insecure http service port: 10080,
Ports can be changed with environment variables.,
https: $SCRYPTED_SECURE_PORT,
http : $SCRYPTED_INSECURE_PORT,
Certificate can be modified via tls.createSecureContext options in,
JSON file located at SCRYPTED_HTTPS_OPTIONS_FILE environment variable:,
export SCRYPTED_HTTPS_OPTIONS_FILE=/path/to/options.json,
https://nodejs.org/api/tls.html#tlscreatesecurecontextoptions,
#######################################################,
installing package @scrypted/core 0.0.205,
downloaded tarball 6197882,
parsing entry package/package.json,
parsing entry package/README.md,
parsing entry package/dist/main.nodejs.js.LICENSE.txt,
parsing entry package/dist/plugin.zip,
npm package files: package/package.json, package/README.md, package/dist/main.nodejs.js.LICENSE.txt, package/dist/plugin.zip,
@scrypted/core auto install failed Error: Could not extract the file,
    at /server/node_modules/adm-zip/adm-zip.js:620:27,
    at Array.forEach (<anonymous>),
    at Object.extractAllTo (/server/node_modules/adm-zip/adm-zip.js:604:26),
    at new PluginHost (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:177:24),
    at ScryptedRuntime.runPlugin (/server/node_modules/@scrypted/server/src/runtime.ts:539:28),
    at ScryptedRuntime.installPlugin (/server/node_modules/@scrypted/server/src/runtime.ts:497:21),
    at /server/node_modules/@scrypted/server/src/runtime.ts:471:25,
    at ScryptedRuntime.getPluginForEndpoint (/server/node_modules/@scrypted/server/src/runtime.ts:186:34),
    at ScryptedRuntime.getEndpointPluginData (/server/node_modules/@scrypted/server/src/runtime.ts:245:21),
    at ScryptedRuntime.endpointHandler (/server/node_modules/@scrypted/server/src/plugin/plugin-http.ts:70:28),
TypeError: Cannot read properties of undefined (reading 'unzippedPath'),
    at ScryptedRuntime.handleRequestEndpoint (/server/node_modules/@scrypted/server/src/runtime.ts:356:84),
    at ScryptedRuntime.endpointHandler (/server/node_modules/@scrypted/server/src/plugin/plugin-http.ts:109:17)

**Comment by banjohb** [comment]
TypeError: Cannot read properties of undefined (reading 'unzippedPath')

This is message in webbrowser

**Comment by koush** [comment]
Something is causing the initial download and installation of the web ui plugin to fail:
> @scrypted/core auto install failed Error: Could not extract the file,
make sure you have enough disk space and your pi doesnt have internet connectivity issue.
