### ISSUE TITLE
Amcrest broke after update to 0.0.158

### ISSUE THREAD

**Issue by Anzic23** [koush/scrypted#193]
On version 0.0.154 everything worked fine, after the update I get the following error in the log:
```
[spal-cam-sv] snapshot error host:@scrypted/homekit
@scrypted/core:host
host:@scrypted/core
@scrypted/amcrest:host
Error: Request failed with status code 401
    at createError (/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.<anonymous> (/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:532:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  cause: undefined
}
[spal-cam-sv] spal-cam-sv encountered an error while retrieving a new snapshot. Consider installing the Snapshot Plugin to show the most recent snapshot. origin:/#/component/plugin/install/@scrypted/snapshot}
[Spalna-hksv] snapshot error host:@scrypted/homekit
@scrypted/amcrest:host
Error: Request failed with status code 401
    at createError (/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.<anonymous> (/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:532:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  cause: undefined
```

**Comment by koush** [comment]
> rtsp stream url rtsp://undefined:554/cam/realmonitor?channel=1&subtype=0

no ip specified

**Comment by Anzic23** [comment]
> > rtsp stream url rtsp://undefined:554/cam/realmonitor?channel=1&subtype=0
> 
> no ip specified
specified
![image](https://user-images.githubusercontent.com/37106885/158870132-dcb2abc4-b727-4de5-b504-98c279fd7d7e.png)

![image](https://user-images.githubusercontent.com/37106885/158870293-6915edbe-8c22-4b0f-a0c1-2c40b2e11c4e.png)
![image](https://user-images.githubusercontent.com/37106885/158870494-76a14098-f628-42d2-a161-eda99b22e448.png)

**Comment by Anzic23** [comment]
this and other cameras worked for me on 0.0.154. After the update it stopped. I tried to enter a new one, it does not help.
