### ISSUE TITLE
unhandledRejection Error: stream ended during read for minimum 1 bytes

### ISSUE THREAD

**Issue by mwhuss** [koush/scrypted#203]
I'm no longer able to login to the web interface. Checking the logs I get this error message.

```
[Office]

[Office] prebuffer session ended with error Error: stream ended during read for minimum 1 bytes
    at TLSSocket.n (/common/src/read-stream.ts:27:20)
    at TLSSocket.emit (node:events:532:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

[Office] restarting prebuffer session in 5 seconds

unhandledRejection Error: stream ended during read for minimum 1 bytes
    at TLSSocket.n (/common/src/read-stream.ts:27:20)
    at TLSSocket.emit (node:events:532:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

e Rebroadcast Plugin unhandledRejection Error: stream ended during read for minimum 1 bytes
```

**Comment by koush** [comment]
That error seems unrelated. What site are you navigating to? The 9443 port was deprecated. https://localhost:10443.

**Comment by koush** [comment]
A screenshot of what you see in Safari/Chrome would be helpful too.

**Comment by koush** [comment]
may be this https://github.com/koush/scrypted/issues/204

**Comment by mwhuss** [comment]
Will work on a screenshot. The symptoms are the same, I'm not able to login and get a Network Unreachable error.

**Comment by koush** [comment]
changed the insecure http port to 30080 a few days ago which I think may be a common Kubernetes port. going to switch it again.

**Comment by mwhuss** [comment]
Updating to the latest docker image (0.0.163) resolves the issue for me.

**Comment by koush** [comment]
> Updating to the latest docker image (0.0.163) resolved my issue of not being able to login. I do still see the original error in the logs still.

I need a screenshot of the browser and the contents of the dev console
