### ISSUE TITLE
Error streaming with Unifi

### ISSUE THREAD

**Issue by mattbroekhuis** [koush/scrypted#226]
Not sure if I should post this here or the unifi github. The screenshots work

I am running latest versions of scypted and homekit plugin on a raspberry pi 3. It has been working pretty well, but lately all the streaming has stopped working. I get this error in the unifi plugin logs when I attempt to initiate a stream on my phone.  I do not have any vlans. I have set the fixed IP address of the scrypted host. (it is not hooked to wifi, only wired)

```
[Rebroadcast Plugin]: Detected audio codec is mp4/mpegts compatible. aac
[HomeKit]: using address override 192.168.1.3
[HomeKit]: streaming request {
[HomeKit]:   sessionID: 'b6a4281d-05c6-45ce-a58c-89331513831c',
[HomeKit]:   type: 'start',
[HomeKit]:   video: {
[HomeKit]:     codec: 0,
[HomeKit]:     profile: 1,
[HomeKit]:     level: 2,
[HomeKit]:     packetizationMode: 0,
[HomeKit]:     cvoId: undefined,
[HomeKit]:     width: 1280,
[HomeKit]:     height: 720,
[HomeKit]:     fps: 30,
[HomeKit]:     pt: 99,
[HomeKit]:     ssrc: 3587627607,
[HomeKit]:     max_bit_rate: 299,
[HomeKit]:     rtcp_interval: 0.5,
[HomeKit]:     mtu: 1378
[HomeKit]:   },
[HomeKit]:   audio: {
[HomeKit]:     codec: 'OPUS',
[HomeKit]:     channel: 1,
[HomeKit]:     bit_rate: 0,
[HomeKit]:     sample_rate: 24,
[HomeKit]:     packet_time: 20,
[HomeKit]:     pt: 110,
[HomeKit]:     ssrc: 3231285506,
[HomeKit]:     max_bit_rate: 24,
[HomeKit]:     rtcp_interval: 5,
[HomeKit]:     comfort_pt: 13,
[HomeKit]:     comfortNoiseEnabled: false
[HomeKit]:   }
[HomeKit]: }
[HomeKit]: {
[HomeKit]:   dynamicBitrate: false,
[HomeKit]:   isLowBandwidth: false,
[HomeKit]:   isWatch: false,
[HomeKit]:   transcodeStreaming: false,
[HomeKit]:   stream: 'High'
[HomeKit]: }
[HomeKit]: fetching video stream
[Rebroadcast Plugin]: sending prebuffer 6007.5
[HomeKit]: streaming error SyntaxError: Unexpected token o in JSON at position 1
[HomeKit]:     at JSON.parse (<anonymous>)
[HomeKit]:     at /src/types/camera/camera-streaming-ffmpeg.ts:30:29
[HomeKit]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[HomeKit]:     at Object.handleStreamRequest (/src/types/camera/camera-streaming.ts:258:13)
[HomeKit]: streaming request { sessionID: 'b6a4281d-05c6-45ce-a58c-89331513831c', type: 'stop' }
[HomeKit]: streaming session killed`


<img width="336" alt="image" src="https://user-images.githubusercontent.com/1326836/163724294-2af35337-52bc-4ff7-8de5-016f6f558638.png">

**Comment by koush** [comment]
make sure your scrypted server is up to date. this log is also incomplete.

**Comment by mattbroekhuis** [comment]
Here's a screen shot showing my version

<img width="554" alt="image" src="https://user-images.githubusercontent.com/1326836/163732215-862575a5-5bb5-44ed-9ea2-fae1d879f067.png">


Here's my plugin versions

<img width="1757" alt="image" src="https://user-images.githubusercontent.com/1326836/163732238-8770b1d6-57c7-4a34-abca-82e285f7e2f7.png">

Here is hopefully better formatted logs. I am in the log of the particular camera (it is the same for any of them). I didn't see any error logs in the plugin log itself.

```
[HomeKit]: using address override 192.168.1.3
[HomeKit]: streaming request {
[HomeKit]:   sessionID: '3ddf89bb-5b4f-4a1d-938b-dcca5a1ef4e8',
[HomeKit]:   type: 'start',
[HomeKit]:   video: {
[HomeKit]:     codec: 0,
[HomeKit]:     profile: 1,
[HomeKit]:     level: 2,
[HomeKit]:     packetizationMode: 0,
[HomeKit]:     cvoId: undefined,
[HomeKit]:     width: 1280,
[HomeKit]:     height: 720,
[HomeKit]:     fps: 30,
[HomeKit]:     pt: 99,
[HomeKit]:     ssrc: 3654588906,
[HomeKit]:     max_bit_rate: 299,
[HomeKit]:     rtcp_interval: 0.5,
[HomeKit]:     mtu: 1378
[HomeKit]:   },
[HomeKit]:   audio: {
[HomeKit]:     codec: 'OPUS',
[HomeKit]:     channel: 1,
[HomeKit]:     bit_rate: 0,
[HomeKit]:     sample_rate: 24,
[HomeKit]:     packet_time: 20,
[HomeKit]:     pt: 110,
[HomeKit]:     ssrc: 2182273064,
[HomeKit]:     max_bit_rate: 24,
[HomeKit]:     rtcp_interval: 5,
[HomeKit]:     comfort_pt: 13,
[HomeKit]:     comfortNoiseEnabled: false
[HomeKit]:   }
[HomeKit]: }
[HomeKit]: {
[HomeKit]:   dynamicBitrate: false,
[HomeKit]:   isLowBandwidth: false,
[HomeKit]:   isWatch: false,
[HomeKit]:   transcodeStreaming: false,
[HomeKit]:   stream: 'High'
[HomeKit]: }
[HomeKit]: fetching video stream
[Rebroadcast Plugin]: sending prebuffer 6018
[HomeKit]: streaming error SyntaxError: Unexpected token o in JSON at position 1
[HomeKit]:     at JSON.parse (<anonymous>)
[HomeKit]:     at /src/types/camera/camera-streaming-ffmpeg.ts:30:29
[HomeKit]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[HomeKit]:     at Object.handleStreamRequest (/src/types/camera/camera-streaming.ts:258:13)
[HomeKit]: streaming request { sessionID: '3ddf89bb-5b4f-4a1d-938b-dcca5a1ef4e8', type: 'stop' }
[HomeKit]: streaming session killed
```

**Comment by mattbroekhuis** [comment]
It says 01.38 is up to date, I think that's a lie. Updating the docker image

**Comment by mattbroekhuis** [comment]
It indeed was not accurate. After updating the docker container I'm back in business. Thank you for the awesome plugin
