### ISSUE TITLE
opencv plugin fails to load with python3.7

### ISSUE THREAD

**Issue by mk01** [koush/scrypted#276]
traceback:
```
Jun 06 20:39:04 xxxxx npx[891477]: i OpenCV Motion Detection loading @scrypted/opencv
Jun 06 20:39:04 xxxxx npx[891477]: i OpenCV Motion Detection pid 892131
Jun 06 20:39:04 xxxxx npx[891477]: Traceback (most recent call last):
Jun 06 20:39:04 xxxxx npx[891477]:   File "/home/scrypted/.scrypted/node_modules/@scrypted/server/python/plugin-remote.py", line 25, in <module>
Jun 06 20:39:04 xxxxx npx[891477]:     import scrypted_python.scrypted_sdk.types
Jun 06 20:39:04 xxxxx npx[891477]:   File "/home/scrypted/.scrypted/node_modules/@scrypted/types/scrypted_python/scrypted_sdk/types.py", line 7, in <module>
Jun 06 20:39:04 xxxxx npx[891477]:     from .other import *
Jun 06 20:39:04 xxxxx npx[891477]:   File "/home/scrypted/.scrypted/node_modules/@scrypted/types/scrypted_python/scrypted_sdk/other.py", line 2, in <module>
Jun 06 20:39:04 xxxxx npx[891477]:     from typing import AbstractSet, Any, TypedDict
Jun 06 20:39:04 xxxxx npx[891477]: ImportError: cannot import name 'TypedDict' from 'typing' (/usr/lib/python3.7/typing.py)
```
as per https://github.com/python/typeshed/issues/3500 , after installing python3-typing-extensions (apt-get install python3-typing-extensions on Debian/Buster) and change of imports in ```.scrypted/node_modules/@scrypted/types/scrypted_python/scrypted_sdk/other.py``` to 
```
from typing import AbstractSet, Any
from typing_extensions import TypedDict
```

all is fine

**Comment by koush** [comment]
alright will fix this, will need to rebuild the various plugins too.
