### ISSUE TITLE
access-control-allow-origin Error when loading webui

### ISSUE THREAD

**Issue by jamesharding** [koush/scrypted#283]
Hello!

When logging in to the webUI, the entire scrypted process is crashing and restarting with the following error:

```
scrypted  | wtf TypeError: Cannot set properties of undefined (setting 'access-control-allow-origin')
scrypted  |     at ServerResponse.setHeader (node:_http_outgoing:585:45)
scrypted  |     at ServerResponse.header (/server/node_modules/express/lib/response.js:794:10)
scrypted  |     at ScryptedRuntime.endpointHandler (/server/node_modules/@scrypted/server/src/plugin/plugin-http.ts:96:17)
scrypted  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
scrypted  | TypeError: Cannot set properties of undefined (setting 'access-control-allow-origin')
scrypted  |     at ServerResponse.setHeader (node:_http_outgoing:585:45)
scrypted  |     at ServerResponse.header (/server/node_modules/express/lib/response.js:794:10)
scrypted  |     at ScryptedRuntime.endpointHandler (/server/node_modules/@scrypted/server/src/plugin/plugin-http.ts:96:17)
scrypted  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I am using the latest docker container.

**Comment by jamesharding** [comment]
It appears that this error is happening in Firefox, but not Chrome.
