### ISSUE TITLE
ONVIF Security Rejection Error

### ISSUE THREAD

**Issue by mouth4war** [koush/scrypted#324]
ONVIF Camera Plugin unhandled Rejection Error: ONVIF SOAP Fault: The data in element 'Security' must be understood but cannot be handled

I get this error for a Xiaovv ONVIF camera. I've changed HTTP port to 8899 and entered correct username/password. Any ideas?

**Comment by mouth4war** [comment]
> i Scrypted Core requested listen Xiaovv "Camera"
i Scrypted Core requested listen Xiaovv "Readme"
i Scrypted Core requested listen Xiaovv "Settings"
i Scrypted Core requested listen Xiaovv "MotionSensor"
i Scrypted Core requested listen Xiaovv "AudioSensor"
unhandledRejection Error: ONVIF SOAP Fault: The data in element 'Security' must be understood but cannot be handled
    at cb (/external/onvif/lib/utils.js:101:13)
    at o.<anonymous> (/external/onvif/node_modules/xml2js/lib/parser.js:304:18)
    at o.emit (node:events:537:28)
    at o.emit (node:domain:482:12)
    at o.event [as onclosetag] (/external/onvif/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/external/onvif/node_modules/sax/lib/sax.js:624:29)
    at emitNode (/external/onvif/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/external/onvif/node_modules/sax/lib/sax.js:889:7)
    at o.write (/external/onvif/node_modules/sax/lib/sax.js:1436:13)
    at o.parseString (/external/onvif/node_modules/xml2js/lib/parser.js:323:31)
e ONVIF Camera Plugin unhandledRejection Error: ONVIF SOAP Fault: The data in element 'Security' must be understood but cannot be handled
error retrieving onvif profiles Error: ONVIF SOAP Fault: The data in element 'Security' must be understood but cannot be handled
    at cb (/external/onvif/lib/utils.js:101:13)
    at o.<anonymous> (/external/onvif/node_modules/xml2js/lib/parser.js:304:18)
    at o.emit (node:events:537:28)
    at o.emit (node:domain:482:12)
    at o.event [as onclosetag] (/external/onvif/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/external/onvif/node_modules/sax/lib/sax.js:624:29)
    at emitNode (/external/onvif/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/external/onvif/node_modules/sax/lib/sax.js:889:7)
    at o.write (/external/onvif/node_modules/sax/lib/sax.js:1436:13)
    at o.parseString (/external/onvif/node_modules/xml2js/lib/parser.js:323:31)
[Xiaovv] error retrieving getVideoStreamOptions TypeError: Cannot read properties of undefined (reading 'map')
    at Object.onGet (/src/stream-settings.ts:201:35)
    at process.onGet (node:internal/process/task_queues:95:5)
    at se.push [as getSettings] (/common/src/settings.ts:114:15)
    at Ke.mixinSettings [as getMixinSettings] (/src/main.ts:1387:14)
    at Ke.getSettings (/common/src/settings-mixin.ts:50:19)
    at RpcPeer.handleMessage (/server/node_modules/@scrypted/server/src/rpc.ts:504:37)

**Comment by mouth4war** [comment]
For reference, HomeAssistant connects via ONVIF to this camera just fine.

**Comment by koush** [comment]
Sorry without access to the camera I have no idea.
