### ISSUE TITLE
HomeKit / Unfi Pi Crashing

### ISSUE THREAD

**Issue by justinshuls** [koush/scrypted#340]
Running on a clean pi 3b, 64 gb with docker, cameras go online and offline randomly and for short and long durations, during this time pi is not accessible via ssh. Have tried numerous clean installs, pi replacement, but cant get it stable. 5 cameras on one hub. Should they each be individual? How might I go about troubleshooting. Hard to diagnose in logs since not timestamped. TIA otherwise slick project

**Comment by koush** [comment]
This sounds like a low memory issue or crash. You can check the docker container uptime to see if it crashed. I’m leaning towards low memory since it’s inaccessible in ssh. Probably paging swap file and locking.

**Comment by koush** [comment]
Generally I suggest 2gb memory but you might be able to get away with 1gb if not using opencv or other intensive plugins.

**Comment by cheme75** [comment]
> Generally I suggest 2gb memory but you might be able to get away with 1gb if not using opencv or other intensive plugins.

Fwiw, my old 1.3ghz 4gb netbook runs a lubuntu gui, homebridge for a few bulbs and switches, and scrypted with opencv and so far has been pretty reliable. Not sure how the old dual core cpu compares to a rpi though.

**Comment by justinshuls** [comment]
Anyway guidance to troubleshoot this? This is my second pi 3, fresh install, 64gb memory card. 6 cameras. Kicks out multiple times ad day but eventually comes back. Using docker.

**Comment by justinshuls** [comment]
Seems like the logs are very active:
```

[G3 Flex] rtsp outgoing message
 TEARDOWN rtsps://192.168.4.1:7441/null RTSP/1.0
CSeq: 2
User-Agent: Scrypted



[G3 Flex]

[G3 Flex] prebuffer session ended with error k [Error]: 
    at TLSSocket.n (/common/src/read-stream.ts:123:14)
    at TLSSocket.emit (node:events:539:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

[G3 Flex] restarting prebuffer session in 5 seconds

[G3 Flex] rebroadcast error Error: This socket has been ended by the other party
    at TLSSocket.write (node:net:487:14)
    at de.write (/common/src/rtsp-server.ts:289:21)
    at de.writeRequest (/common/src/rtsp-server.ts:398:14)
    at de.writeTeardown (/common/src/rtsp-server.ts:739:14)
    at de.safeTeardown (/common/src/rtsp-server.ts:355:18)
    at cleanupSockets (/src/rtsp-session.ts:38:20)
    at O.useUdp (/src/rtsp-session.ts:296:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'EPIPE'
}

unhandledRejection k [Error]: 
    at TLSSocket.n (/common/src/read-stream.ts:123:14)
    at TLSSocket.emit (node:events:539:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

unhandledRejection k [Error]: 
    at TLSSocket.n (/common/src/read-stream.ts:123:14)
    at TLSSocket.emit (node:events:539:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

e Rebroadcast Plugin unhandledRejection Error
e Rebroadcast Plugin unhandledRejection Error
[G3 Flex] High prebuffer session started

[G3 Flex] prebuffer session starting

[G3 Flex] rebroadcast mode: rtsp

[G3 Flex] rtsp outgoing message
 OPTIONS rtsps://192.168.4.1:7441/null RTSP/1.0
CSeq: 0
User-Agent: Scrypted



[G3 Flex]

[G3 Flex] rtsp incoming message
 RTSP/1.0 200 OK
CSeq: 0
Cache-Control: no-store
Date: Fri, 02 Sep 2022 07:13:40 UTC
Expires: Fri, 02 Sep 2022 07:13:40 UTC
Pragma: no-cache
Public: DESCRIBE, OPTIONS, PAUSE, PLAY, SETUP, TEARDOWN, ANNOUNCE, RECORD
Server: EvoStream Media Server (www.evostream.com)

[G3 Flex]

[G3 Flex] rtsp outgoing message
 DESCRIBE rtsps://192.168.4.1:7441/null RTSP/1.0
Accept: application/sdp
CSeq: 1
User-Agent: Scrypted



[G3 Flex]

[G3 Flex] rtsp outgoing message
 TEARDOWN rtsps://192.168.4.1:7441/null RTSP/1.0
CSeq: 2
User-Agent: Scrypted



[G3 Flex]

[G3 Flex] prebuffer session ended with error k [Error]: 
    at TLSSocket.n (/common/src/read-stream.ts:123:14)
    at TLSSocket.emit (node:events:539:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

[G3 Flex] restarting prebuffer session in 5 seconds

[G3 Flex] rebroadcast error Error: This socket has been ended by the other party
    at TLSSocket.write (node:net:487:14)
    at de.write (/common/src/rtsp-server.ts:289:21)
    at de.writeRequest (/common/src/rtsp-server.ts:398:14)
    at de.writeTeardown (/common/src/rtsp-server.ts:739:14)
    at de.safeTeardown (/common/src/rtsp-server.ts:355:18)
    at cleanupSockets (/src/rtsp-session.ts:38:20)
    at O.useUdp (/src/rtsp-session.ts:296:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'EPIPE'
}

unhandledRejection k [Error]: 
    at TLSSocket.n (/common/src/read-stream.ts:123:14)
    at TLSSocket.emit (node:events:539:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
unhandledRejection k [Error]: 
    at TLSSocket.n (/common/src/read-stream.ts:123:14)
e Rebroadcast Plugin unhandledRejection Error
e Rebroadcast Plugin unhandledRejection Error
    at TLSSocket.emit (node:events:539:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

unhandledRejection TypeError: Cannot read properties of undefined (reading 'interfaces')
    at DeviceProxyHandler.interfaces [as get] (/server/node_modules/@scrypted/server/src/plugin/system.ts:54:78)
    at apply (/src/types/camera/camera-snapshot.ts:22:20)
    at invokeFunc (/node_modules/lodash/debounce.js:95:19)
    at trailingEdge (/node_modules/lodash/debounce.js:144:14)
    at Timeout.v [as _onTimeout] (/node_modules/lodash/debounce.js:132:14)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

e HomeKit unhandledRejection TypeError: Cannot read properties of undefined (reading 'interfaces')
[G3 Flex] High prebuffer session started

[G3 Flex] prebuffer session starting

[G3 Flex] rebroadcast mode: rtsp

[G3 Flex] rtsp outgoing message
 OPTIONS rtsps://192.168.4.1:7441/null RTSP/1.0
CSeq: 0
User-Agent: Scrypted



[G3 Flex]

[G3 Flex] rtsp incoming message
 RTSP/1.0 200 OK
CSeq: 0
Cache-Control: no-store
Date: Fri, 02 Sep 2022 07:13:45 UTC
Expires: Fri, 02 Sep 2022 07:13:45 UTC
Pragma: no-cache
Public: DESCRIBE, OPTIONS, PAUSE, PLAY, SETUP, TEARDOWN, ANNOUNCE, RECORD
Server: EvoStream Media Server (www.evostream.com)

[G3 Flex]

[G3 Flex] rtsp outgoing message
 DESCRIBE rtsps://192.168.4.1:7441/null RTSP/1.0
Accept: application/sdp
CSeq: 1
User-Agent: Scrypted



[G3 Flex]

[G3 Flex] rtsp outgoing message
 TEARDOWN rtsps://192.168.4.1:7441/null RTSP/1.0
CSeq: 2
User-Agent: Scrypted



```

**Comment by koush** [comment]
use a admin account. looks like its is disabled on unifi.

**Comment by koush** [comment]
`rtsps://192.168.4.1:7441/null`

**Comment by justinshuls** [comment]
Resolved that error. Was not sure if the user needed to be from unifi console or protect applications. Seems to be from that main console that is desired by scrypted. Still having it crash and make the pi inaccessible. Seems to be related to when motion is triggered although it could be coincidental. At a loss for how to get this stable and troubleshoot further

**Comment by koush** [comment]
3b is not powerful enough as I mentioned.
