### ISSUE TITLE
Hikvision DS-KH6320-WTE1 not working as doorbell

### ISSUE THREAD

**Issue by wladkolc** [koush/scrypted#344]
Hi i have tried to add Hikvision DS-KH6320-WTE1 doorbell with indoor unit, but without success.

I am having an E_UNAUTHORIZED_KEY errror, but i have tried to change password without any dots or special characters, but without success. 

GUI shows me codec problem, but i cant change it... i have tried use no sound option..

> This camera is configured for G.711ulaw on the main channel. Configuring it for AAC is recommended for optimal performance.

I have tried it via rtsp://ip:554/ISAPI/Streaming/channels/101 and stream works, but scrypted shows me this error:

```
[Rebroadcast Plugin]: Stream 1 prebuffer session started
[Rebroadcast Plugin]: prebuffer session starting
[Rebroadcast Plugin]: rebroadcast mode: rtsp
rtsp stream url rtsp://10.20.0.15:554/ISAPI/Streaming/channels/101/?transportmode=unicast
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://10.20.0.15:554/ISAPI/Streaming/channels/101/?transportmode=unicast RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: Public: OPTIONS, DESCRIBE, PLAY, PAUSE, SETUP, TEARDOWN
[Rebroadcast Plugin]: Date:  Mon, Aug 22 2022 01:13:46 GMT
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://10.20.0.15:554/ISAPI/Streaming/channels/101/?transportmode=unicast RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: WWW-Authenticate: Digest realm="Hikvision", nonce="12d70a5b2f3fbadca74d30106783d200", random="la4kjkB2twyNIAVeMl4OLFEUPq4016kg+/LOb0NT0XDUVhXk/wx+FhB1j5zMLNgs", stale="FALSE"
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="Hikvision"
[Rebroadcast Plugin]: Date:  Mon, Aug 22 2022 01:13:46 GMT
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: prebuffer session ended with error t: E_UNAUTHORIZED_KEY (2, random): E_UNAUTHORIZED_KEY
[Rebroadcast Plugin]:     at /src/utils.ts:44:15
[Rebroadcast Plugin]:     at Array.reduce (<anonymous>)
[Rebroadcast Plugin]:     at parseHTTPHeadersQuotedKeyValueSet (/src/utils.ts:28:16)
[Rebroadcast Plugin]:     at Object.DIGEST [as parseWWWAuthenticateRest] (/src/mechanisms/digest.ts:100:12)
[Rebroadcast Plugin]:     at te.createAuthorizationHeader (/common/src/rtsp-server.ts:422:25)
[Rebroadcast Plugin]:     at te.writeRequest (/common/src/rtsp-server.ts:351:45)
[Rebroadcast Plugin]:     at te.request (/common/src/rtsp-server.ts:453:14)
[Rebroadcast Plugin]:     at te.request (/common/src/rtsp-server.ts:470:25)
[Rebroadcast Plugin]:     at process.sdpResponse (node:internal/process/task_queues:96:5)
[Rebroadcast Plugin]:     at C.useUdp (/src/rtsp-session.ts:63:15) {
[Rebroadcast Plugin]:   code: 'E_UNAUTHORIZED_KEY',
[Rebroadcast Plugin]:   params: [ 2, 'random' ],
[Rebroadcast Plugin]:   wrappedErrors: []
[Rebroadcast Plugin]: }
[Rebroadcast Plugin]: restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: rebroadcast error Error: rtsp socket closed
[Rebroadcast Plugin]:     at Socket.<anonymous> (/src/rtsp-session.ts:53:14)
[Rebroadcast Plugin]:     at Socket.emit (node:events:513:28)
[Rebroadcast Plugin]:     at Socket.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at TCP.<anonymous> (node:net:757:14)
```

**Comment by koush** [comment]
I think this is a bug in the scrypted rasp parser, I'll take a look.

**Comment by wladkolc** [comment]
Is there any way to bypass error and make it work?

**Comment by koush** [comment]
try ffmpeg parser maybe
