### ISSUE TITLE
ONVIF camera in HomeKit throws an error when HTTP port override is used

### ISSUE THREAD

**Issue by eugr** [koush/scrypted#354]
Using Reolink E1 Pro camera with Scrypted. Connected as ONVIF to get motion events - it works as long as no other client subscribes to ONVIF events (otherwise throws SOAP errors), however when using with Homekit, it throws this message:

```
[HomeKit]: @scrypted/onvif:host
[HomeKit]: Error: connect ECONNREFUSED <my_camera_ip>:80
[HomeKit]:     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
[HomeKit]:   cause: undefined
[HomeKit]: }
```
Looks like it doesn't respect the port override as Reolink ONVIF server is listening on port 8000, so I have it set so in HTTP Port Override parameter.

Doesn't seem to affect functionality much, but seems to result in longer motion sensor trigger state (until a timeout?)

**Comment by eugr** [comment]
Also seems to do the same during initialization:

```
[Rebroadcast Plugin]: 
[HomeKit]: HomeKit Connection <blanked out>
[HomeKit]: snapshot error host:@scrypted/homekit
[HomeKit]: @scrypted/onvif:host
[HomeKit]: Error: connect ECONNREFUSED <my ip camera address>:80
[HomeKit]:     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
[HomeKit]:   cause: undefined
[HomeKit]: }
```

**Comment by koush** [comment]
what is homekit trying to do at the time? fetch snapshots maybe? do you see this error every 10 seconds or so, ie, the snapshot refresh interval?

**Comment by eugr** [comment]
Looks like you are right, it is indeed trying to take a snapshot periodically(also explains why snapshot is always blank):

```
HomeKit Connection ::ffff:x.x.x.x
[HomeKit]: snapshot error host:@scrypted/homekit
[HomeKit]: @scrypted/onvif:host
[HomeKit]: Error: connect ECONNREFUSED x.x.x.y:80
[HomeKit]:     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
[HomeKit]:   cause: undefined
[HomeKit]: }
```

**Comment by koush** [comment]
please try the beta v0.0.95 in from the onvif plugin version dropdown.

**Comment by eugr** [comment]
That error disappeared, but there is a new one now:

```
[HomeKit]: snapshot error host:@scrypted/homekit
[HomeKit]: @scrypted/onvif:host
[HomeKit]: Error: Request failed with status code 405
[HomeKit]:     at createError (/node_modules/axios/lib/core/createError.js:16:15)
[HomeKit]:     at settle (/node_modules/axios/lib/core/settle.js:17:12)
[HomeKit]:     at IncomingMessage.<anonymous> (/node_modules/axios/lib/adapters/http.js:269:11)
[HomeKit]:     at IncomingMessage.emit (node:events:539:35)
[HomeKit]:     at IncomingMessage.emit (node:domain:475:12)
[HomeKit]:     at endReadableNT (node:internal/streams/readable:1345:12)
[HomeKit]:     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
[HomeKit]:   cause: undefined
[HomeKit]: }
[HomeKit]: snapshot error host:@scrypted/homekit
[HomeKit]: @scrypted/onvif:host
[HomeKit]: Error: Request failed with status code 405
[HomeKit]:     at createError (/node_modules/axios/lib/core/createError.js:16:15)
[HomeKit]:     at settle (/node_modules/axios/lib/core/settle.js:17:12)
[HomeKit]:     at IncomingMessage.<anonymous> (/node_modules/axios/lib/adapters/http.js:269:11)
[HomeKit]:     at IncomingMessage.emit (node:events:539:35)
[HomeKit]:     at IncomingMessage.emit (node:domain:475:12)
[HomeKit]:     at endReadableNT (node:internal/streams/readable:1345:12)
[HomeKit]:     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
[HomeKit]:   cause: undefined
[HomeKit]: }
[HomeKit]: HomeKit Connection ::ffff:192.168.24.132
[HomeKit]: snapshot error host:@scrypted/homekit
[HomeKit]: @scrypted/onvif:host
[HomeKit]: Error: Request failed with status code 405
[HomeKit]:     at createError (/node_modules/axios/lib/core/createError.js:16:15)
[HomeKit]:     at settle (/node_modules/axios/lib/core/settle.js:17:12)
[HomeKit]:     at IncomingMessage.<anonymous> (/node_modules/axios/lib/adapters/http.js:269:11)
[HomeKit]:     at IncomingMessage.emit (node:events:539:35)
[HomeKit]:     at IncomingMessage.emit (node:domain:475:12)
[HomeKit]:     at endReadableNT (node:internal/streams/readable:1345:12)
[HomeKit]:     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
[HomeKit]:   cause: undefined
[HomeKit]: }
```

**Comment by koush** [comment]
yeah I think this is an onvif implementation bug on your camera. use the snapshot url in the snapshot plugin to manually specify a snapshot location.

**Comment by eugr** [comment]
Thanks, the snapshot plugin with the option to fetch from the pre-buffer helped. Still not very happy with this camera - comparable Amcrest ASH21 works better and supports more onvif features (once you configure it properly via their Windows application). The only redeeming quality is 5GHz wifi support...

**Comment by koush** [comment]
reolink snap url:
```
http://(ip address)/cgi-bin/api.cgi?cmd=Snap&channel=(channel id)&rs=(any combination of numbers and letters)&user=(user name)&password=(user password)
```

**Comment by eugr** [comment]
Unfortunately, E1 Pro camera doesn't have a webserver running on port 80. And port 8000 seems to handle only ONVIF connections as when I try to modify this request for that port I get a SOAP message that HTTP GET method is not implemented...

**Comment by eugr** [comment]
Here is nmap output:
```
ORT     STATE SERVICE
554/tcp  open  rtsp
6001/tcp open  X11:1
8000/tcp open  http-alt
8888/tcp open  sun-answerbook
9000/tcp open  cslistener
```
