### ISSUE TITLE
Huge number of errors in log - scrypted/core - Cannot read properties of undefined (reading 'state')

### ISSUE THREAD

**Issue by TheOriginalMrWolf** [koush/scrypted#371]
Hi,

Running scrypted in docker on Odroid N2.  Have a couple of Hikvision cameras, Ring doorbell, MQTT client, & talking nicely with homekit.  Everything seems to be running well, but... I am getting a huge number of errors in logs (docker logs -f scrypted; get 1 error message per second):

engine.io plugin error @scrypted/core:host
host:@scrypted/core
TypeError: Cannot read properties of undefined (reading 'state')
    at getState (/server/node_modules/@scrypted/server/src/state.ts:222:30)
    at PluginComponent.getDeviceInfo (/server/node_modules/@scrypted/server/src/services/plugin.ts:81:29)
    at RpcPeer.handleMessage (/server/node_modules/@scrypted/server/src/rpc.ts:505:66)
    at ChildProcess.<anonymous> (/server/node_modules/@scrypted/server/src/plugin/runtime/node-fork-worker.ts:45:22)
    at ChildProcess.emit (node:events:527:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  cause: undefined
}

Thought this might be important since it's in core.

**Comment by TheOriginalMrWolf** [comment]
NVM... only whilst the UI was running.  Closing & re-opening UI made the problem go away....

**Comment by TheOriginalMrWolf** [comment]
Closing & re-opening UI made the problem go away....

**Comment by TheOriginalMrWolf** [comment]
NVM... only whilst the UI was running. Closing & re-opening UI made the problem go away....
