### ISSUE TITLE
What may be causing these timeouts?

### ISSUE THREAD

**Issue by lvnilesh** [koush/scrypted#390]
```

scrypted  | [Frontyard] Stream 1 prebuffer session started
scrypted  | 
scrypted  | [Frontyard] prebuffer session starting
scrypted  | 
scrypted  | [Frontyard] rebroadcast mode: rtsp
scrypted  | 
scrypted  | rtsp stream url rtsp://asdasd:554/live/ch0
scrypted  | 
scrypted  | [Frontyard] rtsp outgoing message
scrypted  |  OPTIONS rtsp://asdasd:554/live/ch0 RTSP/1.0
scrypted  | CSeq: 0
scrypted  | User-Agent: Scrypted
scrypted  | 
scrypted  | 
scrypted  | 
scrypted  | [Frontyard]
scrypted  | 
scrypted  | timeout waiting for data, killing parser session rtsp
scrypted  | 
scrypted  | [Frontyard] rebroadcast error Error: timeout waiting for data, killing parser session
scrypted  |     at dataKill (/common/src/ffmpeg-rebroadcast.ts:100:14)
scrypted  |     at Timeout.<anonymous> (/common/src/ffmpeg-rebroadcast.ts:117:17)
scrypted  |     at listOnTimeout (node:internal/timers:559:17)
scrypted  |     at processTimers (node:internal/timers:502:7)
scrypted  | 
scrypted  | [Frontyard] rtsp outgoing message
scrypted  |  TEARDOWN rtsp://asdasd:554/live/ch0 RTSP/1.0
scrypted  | CSeq: 1
scrypted  | User-Agent: Scrypted
scrypted  | 
scrypted  | 
scrypted  | [Frontyard]
scrypted  | 
scrypted  | [Frontyard] prebuffer session ended with error q [Error]: Operation Timed Out
scrypted  |     at Timeout._onTimeout (/common/src/promise-utils.ts:32:33)
scrypted  |     at listOnTimeout (node:internal/timers:559:17)
scrypted  |     at processTimers (node:internal/timers:502:7) {
scrypted  |   promise: Promise { <pending> }
scrypted  | }
scrypted  | 
scrypted  | [Frontyard] restarting prebuffer session in 5 seconds
scrypted  | 
scrypted  | unhandledRejection q [Error]: Operation Timed Out
scrypted  |     at Timeout._onTimeout (/common/src/promise-utils.ts:32:33)
scrypted  |     at listOnTimeout (node:internal/timers:559:17)
scrypted  |     at processTimers (node:internal/timers:502:7) {
scrypted  |   promise: Promise { <pending> }
scrypted  | }
scrypted  | 
scrypted  | e Rebroadcast Plugin unhandledRejection Error: Operation Timed Out
scrypted  | [Frontyard] Stream 1 prebuffer session started
scrypted  | 
scrypted  | [Frontyard] prebuffer session starting
scrypted  | 
scrypted  | [Frontyard] rebroadcast mode: rtsp
scrypted  | 
scrypted  | rtsp stream url rtsp://asdasd:554/live/ch0
scrypted  | 
scrypted  | [Frontyard] rtsp outgoing message
scrypted  |  OPTIONS rtsp://asdasd:554/live/ch0 RTSP/1.0
scrypted  | CSeq: 0
scrypted  | User-Agent: Scrypted
scrypted  | 
scrypted  | 
scrypted  | 
scrypted  | [Frontyard]
scrypted  | 
scrypted  | timeout waiting for data, killing parser session rtsp
scrypted  | 
scrypted  | [Frontyard] rebroadcast error Error: timeout waiting for data, killing parser session
scrypted  |     at dataKill (/common/src/ffmpeg-rebroadcast.ts:100:14)
scrypted  |     at Timeout.<anonymous> (/common/src/ffmpeg-rebroadcast.ts:117:17)
scrypted  |     at listOnTimeout (node:internal/timers:559:17)
scrypted  |     at processTimers (node:internal/timers:502:7)
scrypted  | 
scrypted  | [Frontyard] rtsp outgoing message
scrypted  |  TEARDOWN rtsp://asdasd:554/live/ch0 RTSP/1.0
scrypted  | CSeq: 1
scrypted  | User-Agent: Scrypted
scrypted  | 
scrypted  | 
scrypted  | 
scrypted  | [Frontyard]
scrypted  | 
scrypted  | [Frontyard] prebuffer session ended with error q [Error]: Operation Timed Out
scrypted  |     at Timeout._onTimeout (/common/src/promise-utils.ts:32:33)
scrypted  |     at listOnTimeout (node:internal/timers:559:17)
scrypted  |     at processTimers (node:internal/timers:502:7) {
scrypted  |   promise: Promise { <pending> }
scrypted  | }
scrypted  | 
scrypted  | e Rebroadcast Plugin unhandledRejection Error: Operation Timed Out
scrypted  | [Frontyard] restarting prebuffer session in 5 seconds
scrypted  | 
scrypted  | unhandledRejection q [Error]: Operation Timed Out
scrypted  |     at Timeout._onTimeout (/common/src/promise-utils.ts:32:33)
scrypted  |     at listOnTimeout (node:internal/timers:559:17)
scrypted  |     at processTimers (node:internal/timers:502:7) {
scrypted  |   promise: Promise { <pending> }
scrypted  | }
scrypted  | 
scrypted  | [Frontyard] Selected stream Stream 1
scrypted  | 
scrypted  | [Frontyard] Stream 1 prebuffer session started
scrypted  | 
scrypted  | [Frontyard] rebroadcast mode: rtsp
scrypted  | 
scrypted  | rtsp stream url rtsp://asdasd:554/live/ch0
scrypted  | 
scrypted  | [Frontyard] rtsp outgoing message
scrypted  |  OPTIONS rtsp://asdasd:554/live/ch0 RTSP/1.0
scrypted  | CSeq: 0
scrypted  | User-Agent: Scrypted
scrypted  | 
scrypted  | 
scrypted  | 
scrypted  | [Frontyard]
scrypted  | 
scrypted  | [Frontyard] prebuffer session starting
scrypted  | 
scrypted  | timeout waiting for data, killing parser session rtsp
scrypted  | 
scrypted  | [Frontyard] rebroadcast error Error: timeout waiting for data, killing parser session
scrypted  |     at dataKill (/common/src/ffmpeg-rebroadcast.ts:100:14)
scrypted  |     at Timeout.<anonymous> (/common/src/ffmpeg-rebroadcast.ts:117:17)
scrypted  |     at listOnTimeout (node:internal/timers:559:17)
scrypted  |     at processTimers (node:internal/timers:502:7)
scrypted  | 
scrypted  | [Frontyard] rtsp outgoing message
scrypted  |  TEARDOWN rtsp://asdasd:554/live/ch0 RTSP/1.0
scrypted  | CSeq: 1
scrypted  | User-Agent: Scrypted
scrypted  | 
scrypted  | 
scrypted  | [Frontyard]
scrypted  | 
scrypted  | [Frontyard] prebuffer session ended with error q [Error]: Operation Timed Out
scrypted  |     at Timeout._onTimeout (/common/src/promise-utils.ts:32:33)
scrypted  |     at listOnTimeout (node:internal/timers:559:17)
scrypted  |     at processTimers (node:internal/timers:502:7) {
scrypted  |   promise: Promise { <pending> }
scrypted  | }
scrypted  | 
scrypted  | [Frontyard] restarting prebuffer session in 5 seconds
scrypted  | 
scrypted  | e Rebroadcast Plugin unhandledRejection Error: Operation Timed Out
scrypted  | unhandledRejection q [Error]: Operation Timed Out
scrypted  |     at Timeout._onTimeout (/common/src/promise-utils.ts:32:33)
scrypted  |     at listOnTimeout (node:internal/timers:559:17)
scrypted  |     at processTimers (node:internal/timers:502:7) {
scrypted  |   promise: Promise { <pending> }
scrypted  | }
scrypted  | 
scrypted  | [Frontyard] failure retrieving stream host:@scrypted/objectdetector
scrypted  | @scrypted/prebuffer-mixin:host
scrypted  | Error: Operation Timed Out
scrypted  |     at Timeout._onTimeout (/common/src/promise-utils.ts:32:33)
scrypted  |     at listOnTimeout (node:internal/timers:559:17)
scrypted  |     at processTimers (node:internal/timers:502:7) {
scrypted  |   cause: undefined
scrypted  | }
scrypted  | 
scrypted  | [Frontyard] Stream 1 prebuffer session started
scrypted  | 
scrypted  | [Frontyard] prebuffer session starting
scrypted  | 
scrypted  | [Frontyard] rebroadcast mode: rtsp
scrypted  | 
scrypted  | rtsp stream url rtsp://asdasd:554/live/ch0
scrypted  | 
scrypted  | [Frontyard] rtsp outgoing message
scrypted  |  OPTIONS rtsp://asdasd:554/live/ch0 RTSP/1.0
scrypted  | CSeq: 0
scrypted  | User-Agent: Scrypted
scrypted  | 
scrypted  | 
scrypted  | 
scrypted  | [Frontyard]
scrypted  | 
scrypted  | [Frontyard] rtsp outgoing message
scrypted  |  TEARDOWN rtsp://asdasd:554/live/ch0 RTSP/1.0
scrypted  | CSeq: 1
scrypted  | User-Agent: Scrypted
scrypted  | 
scrypted  | 
scrypted  | 
scrypted  | [Frontyard]
scrypted  | 
scrypted  | [Frontyard] prebuffer session ended with error q [Error]: Operation Timed Out
scrypted  |     at Timeout._onTimeout (/common/src/promise-utils.ts:32:33)
scrypted  |     at listOnTimeout (node:internal/timers:559:17)
scrypted  |     at processTimers (node:internal/timers:502:7) {
scrypted  |   promise: Promise { <pending> }
scrypted  | }
scrypted  | 
scrypted  | [Frontyard] restarting prebuffer session in 5 seconds
scrypted  | 
scrypted  | unhandledRejection q [Error]: Operation Timed Out
scrypted  |     at Timeout._onTimeout (/common/src/promise-utils.ts:32:33)
scrypted  |     at listOnTimeout (node:internal/timers:559:17)
scrypted  |     at processTimers (node:internal/timers:502:7) {
scrypted  |   promise: Promise { <pending> }
scrypted  | }
scrypted  | 
scrypted  | e Rebroadcast Plugin unhandledRejection Error: Operation Timed Out
scrypted  | [Frontyard] rebroadcast error Error: rtsp socket closed
scrypted  |     at Socket.<anonymous> (/src/rtsp-session.ts:57:14)
scrypted  |     at Socket.emit (node:events:527:28)
scrypted  |     at Socket.emit (node:domain:475:12)
scrypted  |     at TCP.<anonymous> (node:net:709:12)
scrypted  | 

```

**Comment by koush** [comment]
rtsp://asdasd:554/live/ch0

**Comment by lvnilesh** [comment]
Thanks
