### ISSUE TITLE
@scrypted/opencv won't start

### ISSUE THREAD

**Issue by bordeo** [koush/scrypted#472]
I'm using docker image koush/scrypted:v0.4.6

I think `aiofiles` is missing from docker image.

When @scrypted/opencv try to start It give me the error and won't start.

```JavaScript
e OpenCV Motion Detection @scrypted/opencv exited 1 null
plugin unexpectedly exited, restarting in 60000ms @scrypted/opencv
mixin error @scrypted/objectdetector:host
host:@scrypted/objectdetector
Error: device is unavailable 44 (mixin undefined)
    at PluginDeviceProxyHandler.applyMixin (/server/node_modules/@scrypted/server/src/plugin/plugin-device.ts:357:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RpcPeer.handleMessage (/server/node_modules/@scrypted/server/src/rpc.ts:527:37) {
  cause: undefined
}
i OpenCV Motion Detection loading @scrypted/opencv
i OpenCV Motion Detection pid 149
Traceback (most recent call last):
  File "/server/node_modules/@scrypted/server/python/plugin-remote.py", line 24, in <module>
    
import aiofiles
ModuleNotFoundError: No module named 'aiofiles'
e OpenCV Motion Detection @scrypted/opencv error Error: read ECONNRESET
plugin failed to load RPCResultError: host:@scrypted/opencv: error while retrieving PluginRemote
    at setupPluginRemote (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:397:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:212:28 {
  cause: RPCResultError: host:@scrypted/opencv: plugin disconnected
      at RpcPeer.kill (/server/node_modules/@scrypted/server/src/rpc.ts:299:23)
      at disconnect (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:316:23)
      at PythonRuntimeWorker.<anonymous> (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:333:13)
      at PythonRuntimeWorker.emit (node:events:513:28)
      at Socket.<anonymous> (/server/node_modules/@scrypted/server/src/plugin/runtime/python-worker.ts:71:18)
      at Socket.emit (node:events:513:28)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    cause: undefined
  }
}
error occured retrieving device from plugin
unhandled rejection of RPC Result RPCResultError: host:@scrypted/opencv: error while retrieving PluginRemote
    at setupPluginRemote (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:397:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:212:28 {
  cause: RPCResultError: host:@scrypted/opencv: plugin disconnected
      at RpcPeer.kill (/server/node_modules/@scrypted/server/src/rpc.ts:299:23)
      at disconnect (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:316:23)
      at PythonRuntimeWorker.<anonymous> (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:333:13)
      at PythonRuntimeWorker.emit (node:events:513:28)
      at Socket.<anonymous> (/server/node_modules/@scrypted/server/src/plugin/runtime/python-worker.ts:71:18)
      at Socket.emit (node:events:513:28)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    cause: undefined
  }
}
unhandled rejection of RPC Result RPCResultError: host:@scrypted/opencv: error while retrieving PluginRemote
    at setupPluginRemote (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:397:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:212:28 {
  cause: RPCResultError: host:@scrypted/opencv: plugin disconnected
      at RpcPeer.kill (/server/node_modules/@scrypted/server/src/rpc.ts:299:23)
      at disconnect (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:316:23)
      at PythonRuntimeWorker.<anonymous> (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:333:13)
      at PythonRuntimeWorker.emit (node:events:513:28)
      at Socket.<anonymous> (/server/node_modules/@scrypted/server/src/plugin/runtime/python-worker.ts:71:18)
      at Socket.emit (node:events:513:28)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    cause: undefined
  }
}
```

**Comment by koush** [comment]
can you delete and reinstall the plugin? or downgrade and upgrade? aiofiles is installed during the plugin install, not in the docker image.

**Comment by bordeo** [comment]
yes, I already tried to re-install the plugin.

https://user-images.githubusercontent.com/1566127/208468657-442477a5-2803-4428-8004-f8699a630d26.mp4

**Comment by bordeo** [comment]
<img width="788" alt="Screenshot 2022-12-19 at 19 49 29" src="https://user-images.githubusercontent.com/1566127/208498378-6efb139d-f455-4b78-a70e-fbc870112b57.png">

```javascript
installing package @scrypted/opencv 0.0.55
downloaded tarball 21358
parsing entry package/package.json
parsing entry package/tsconfig.json
parsing entry package/README.md
parsing entry package/dist/plugin.zip
npm package files: package/package.json, package/tsconfig.json, package/README.md, package/dist/plugin.zip
Skipping @scrypted/objectdetector : Plugin already installed.
i OpenCV Motion Detection loading @scrypted/opencv
i OpenCV Motion Detection pid 131
i Video Analysis Plugin auto enabling mixin for OpenCV Motion Detection
i Video Analysis Plugin auto enabling mixin for OpenCV Motion Detection
Traceback (most recent call last):
  File "/server/node_modules/@scrypted/server/python/plugin-remote.py", line 24, in <module>
    import aiofiles
ModuleNotFoundError: No module named 'aiofiles'
e OpenCV Motion Detection @scrypted/opencv error Error: read ECONNRESET
plugin failed to load RPCResultError: host:@scrypted/opencv: error while retrieving PluginRemote
    at setupPluginRemote (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:397:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:212:28 {
  cause: RPCResultError: host:@scrypted/opencv: plugin disconnected
      at RpcPeer.kill (/server/node_modules/@scrypted/server/src/rpc.ts:299:23)
      at disconnect (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:316:23)
      at PythonRuntimeWorker.<anonymous> (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:333:13)
      at PythonRuntimeWorker.emit (node:events:513:28)
      at Socket.<anonymous> (/server/node_modules/@scrypted/server/src/plugin/runtime/python-worker.ts:71:18)
      at Socket.emit (node:events:513:28)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    cause: undefined
  }
}
error occured retrieving device from plugin
error occured retrieving device from plugin
unhandled rejection of RPC Result RPCResultError: host:@scrypted/opencv: error while retrieving PluginRemote
    at setupPluginRemote (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:397:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:212:28 {
  cause: RPCResultError: host:@scrypted/opencv: plugin disconnected
      at RpcPeer.kill (/server/node_modules/@scrypted/server/src/rpc.ts:299:23)
      at disconnect (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:316:23)
      at PythonRuntimeWorker.<anonymous> (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:333:13)
      at PythonRuntimeWorker.emit (node:events:513:28)
      at Socket.<anonymous> (/server/node_modules/@scrypted/server/src/plugin/runtime/python-worker.ts:71:18)
      at Socket.emit (node:events:513:28)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    cause: undefined
  }
}
unhandled rejection of RPC Result RPCResultError: host:@scrypted/opencv: error while retrieving PluginRemote
    at setupPluginRemote (/server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:397:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:212:28 {
  cause: RPCResultError: host:@scrypted/opencv: plugin disconnected
      at RpcPeer.kill (/server/node_modules/@scrypted/server/src/rpc.ts:299:23)
      at disconnect (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:316:23)
      at PythonRuntimeWorker.<anonymous> (/server/node_modules/@scrypted/server/src/plugin/plugin-host.ts:333:13)
      at PythonRuntimeWorker.emit (node:events:513:28)
      at Socket.<anonymous> (/server/node_modules/@scrypted/server/src/plugin/runtime/python-worker.ts:71:18)
      at Socket.emit (node:events:513:28)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    cause: undefined
  }
}
e OpenCV Motion Detection @scrypted/opencv exited 1 null
plugin unexpectedly exited, restarting in 60000ms @scrypted/opencv
mixin error @scrypted/objectdetector:host
host:@scrypted/objectdetector
Error: device is unavailable 48 (mixin undefined)
    at PluginDeviceProxyHandler.applyMixin (/server/node_modules/@scrypted/server/src/plugin/plugin-device.ts:357:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RpcPeer.handleMessage (/server/node_modules/@scrypted/server/src/rpc.ts:527:37) {
  cause: undefined
}
i Scrypted Core requested listen OpenCV Motion Detection "Readme"
i Scrypted Core requested listen OpenCV Motion Detection "MixinProvider"
i Scrypted Core requested listen OpenCV Motion Detection null
i Scrypted Core requested listen OpenCV Motion Detection "Settings"
```

**Comment by koush** [comment]
I'm not seeing this in my docker installation. Did you somehow remove it from your running container? It's definitely there. See layer 22. Maybe nuke the container and pull again?

https://hub.docker.com/layers/koush/scrypted/latest/images/sha256-021cb58d6841b0622e30facf57b26bd4fc6efd4b88cd1e359c2f7b8da1bd9ae6?context=explore

**Comment by bordeo** [comment]
I found the problem. I'm using the v0.4.6 docker image that isn't a `full` image but a `thin` image.
Actually only the `latest` is as `full` image.
If not specified I expected that a tagged version is a full version otherwise it can be tagged with suffix eg: `v0.4.6-lite` `v0.4.6-thin`.
I'm I thinking in the right way?

I propose to tag images as follow:
full:  v0.4.6 v0.4.7 v0.4.8 latest
thin: v0.4.6-thin v0.4.7-thin v0.4.8-thin thin
thin: v0.4.6-lite v0.4.7-lite v0.4.8-lite lite

<img width="1552" alt="Screenshot 2022-12-19 at 23 54 36" src="https://user-images.githubusercontent.com/1566127/208543526-6f79f9f8-9094-4279-a805-eda42ffc85ab.png">
<img width="1552" alt="Screenshot 2022-12-19 at 23 54 23" src="https://user-images.githubusercontent.com/1566127/208543572-335e4049-d90f-414b-b09f-a6d960e479f1.png">

**Comment by koush** [comment]
there's no need for a suffix that has the tag in it. that's redundant with the docker tag.

koush/scrypted:latest
koush/scrypted:thin
koush/scrypted:full

**Comment by koush** [comment]
maybe I'm misunderstanding, are you saying latest contains a thin image?

**Comment by koush** [comment]
oh I see the issue now, apologies, I'll fix this
