### ISSUE TITLE
Windows installation script windows-build-tools no longer required?

### ISSUE THREAD

**Issue by longzheng** [koush/scrypted#494]
The Windows installation script tries to install `windows-build-tools` which actually fails

```
npm WARN config production Use `--omit=dev` instead.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated windows-build-tools@5.2.2: Node.js now includes build tools for Windows. You probably no longer need this tool. See https://github.com/felixrieseberg/windows-build-tools for details.
npm ERR! code 1
npm ERR! path C:\Users\Long\AppData\Roaming\npm\node_modules\windows-build-tools
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./dist/index.js
Downloading python-2.7.15.amd64.msi
npm ERR! [============================================>] 100.0% (0 B/s)
npm ERR! Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\Long\.windows-build-tools\python-2.7.15.amd64.msi.
Downloading vs_BuildTools.exe
npm ERR! [============================================>] 100.0% (0 B/s)
npm ERR! Downloaded vs_BuildTools.exe. Saved to C:\Users\Long\.windows-build-tools\vs_BuildTools.exe.
npm ERR!
npm ERR! Starting installation...
npm ERR! Downloading installers failed. Error: TypeError: 'process.env' only accepts a configurable, writable, and enumerable data descriptor
npm ERR!     at Function.defineProperty (<anonymous>)
npm ERR!     at Object.removePath (C:\Users\Long\AppData\Roaming\npm\node_modules\windows-build-tools\dist\utils\remove-path.js:11:12)
npm ERR!     at Object.install (C:\Users\Long\AppData\Roaming\npm\node_modules\windows-build-tools\dist\install\index.js:29:19)
npm ERR!     at C:\Users\Long\AppData\Roaming\npm\node_modules\windows-build-tools\dist\start.js:17:19
npm ERR!     at Object.download (C:\Users\Long\AppData\Roaming\npm\node_modules\windows-build-tools\dist\download.js:35:5)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async Object.aquireInstallers (C:\Users\Long\AppData\Roaming\npm\node_modules\windows-build-tools\dist\aquire-installers.js:32:13) {
npm ERR!   code: 'ERR_INVALID_OBJECT_DEFINE_PROPERTY'
npm ERR! }
npm ERR! windows-build-tools will now exit.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Long\AppData\Local\npm-cache\_logs\2023-01-06T01_18_46_253Z-debug-0.log
```

But according to the library itself, it might be [redundant now since that Node.js comes with required tools](https://github.com/felixrieseberg/windows-build-tools) which can be installed from the installer or the "Install Additional Tools for Node.js" start menu option.

**Comment by koush** [comment]
I'm not sure, windows is pretty neglected at the moment. I'd need the approbate winget package or way to trigger the node installer.

**Comment by longzheng** [comment]
> I'm not sure, windows is pretty neglected at the moment. I'd need the appropriate winget package or way to trigger the node installer.

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/484912/210928500-5f1e3118-1c8d-4cf8-8c5a-a4b4d558e401.png">

The shortcut seems to simply run 
```
C:\Windows\System32\cmd.exe /d /c "C:\Program Files\nodejs\install_tools.bat"
```

Which then in turn runs this https://github.com/nodejs/node/blob/main/tools/msvs/install_tools/install_tools.bat#L55

```
"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command Start-Process '%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe' -ArgumentList '-NoProfile -InputFormat None -ExecutionPolicy Bypass -Command [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString(''https://chocolatey.org/install.ps1'')); choco upgrade -y python visualstudio2019-workload-vctools; Read-Host ''Type ENTER to exit'' ' -Verb RunAs
```

I'm not sure if it's easy to just run that command directly or if the installer supports some sort of additional parameter.

**Comment by koush** [comment]
Gotcha. I don't have time to work on this, but if you have a line I can run (that doesn't assume Windows is installed on C:), let me know.

**Comment by longzheng** [comment]
Ah it should be just the last command since that's the one Node itself runs, but it'll test tomorrow and confirm.

**Comment by koush** [comment]
Yes, please do. Would like to make the Windows installer reliable.
