### ISSUE TITLE
Pushover Notifications Aren't Working

### ISSUE THREAD

**Issue by RamboRogers** [koush/scrypted#513]
uncaughtException Error: message cannot be blank
    at u.errors (/node_modules/pushover-notifications/lib/pushover.js:146:13)
    at IncomingMessage.<anonymous> (/node_modules/pushover-notifications/lib/pushover.js:250:12)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

e Pushover Plugin uncaughtException Error: message cannot be blank

I'm getting this when clicking "Send" to test.  
![image](https://user-images.githubusercontent.com/7763805/212493991-261a9b2c-feca-4700-b661-d29bd5b8eabd.png)

**Comment by koush** [comment]
updated, can you test and verify?

**Comment by RamboRogers** [comment]
Fixed! Thank you!!!!!
