### ISSUE TITLE
Scrypted/Arlo plugin fails to load

### ISSUE THREAD

**Issue by DaveS68** [koush/scrypted#523]
I am new to all this but got scrypted working and was able to connect some old RTSP cameras to homekit and was hoping to do the same for Arlo given my free cloud recording is going away in April. I downloaded the @scrypted/arlo plugin but it fails to load with the following log.  Tried doing some research to figure it out and it sounds like a python issue but I am not even sure what that means.  I am not a programmer and not sure what the issue is so any help is appreciated.  Thanks!

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/build_env.py", line 20, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/misc.py", line 37, in <module>
    from pip._vendor.pep517 import Pep517HookCaller
ImportError: cannot import name 'Pep517HookCaller' from 'pip._vendor.pep517' (unknown location)
pip install result 1

**Comment by bjia56** [comment]
What OS/hardware are you running scrypted on? Did you install scrypted with Docker or as a standalone app?

**Comment by DaveS68** [comment]
I am on a RP4 4gb. Installed homebridge, running side by side with Docker, Scrypted per Eddie Dsuza's video.

**Comment by bjia56** [comment]
It sounds to me like you may have a broken python install, which is odd if you're running scrypted via Docker. What scrypted server version are you on? Are you using the `koush/scrypted` Docker image or a different name?

**Comment by DaveS68** [comment]
Docker installed using Eddie Dsuza's magic scrypt that downloads Docker, Scrypted, Portainer, Heimdall etc.  I am not sure what version it is

**Comment by bjia56** [comment]
Can you try running `sudo docker pull koush/scrypted` then reboot your machine

**Comment by DaveS68** [comment]
Thank you for your help and the work you have done on the Arlo program.  I just started from scratch and ditched the homebridge and went with the scrypted docker instal on raspPi os lite per the instructions and have it working now.  I do miss the UI of the homebridge for info such as CPU and Ram usage but the cameras are mostly working now although seem to randomly go offline here and there.

**Comment by bjia56** [comment]
Cool, glad to hear you got it installed now
