### ISSUE TITLE
Rebroadcast parse error - Error: RTSP Server expected frame magic but received: TEAR

### ISSUE THREAD

**Issue by jordanmkoncz** [koush/scrypted#531]
I'm using the SIP stream (via RTSP) exposed by Scrypted for a Ring Stick Up Cam Elite. I can start the live stream and it initially works fine, but after some time the live stream freezes. When I check the Rebroadcast Plugin console log, I see the following:

```
[Backyard Stick Up Cam] rebroadcast parse error Error: RTSP Server expected frame magic but received: TEAR
    at A.handleRecord (/@scrypted/prebuffer-mixin/main.nodejs.js:1:92318)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.parse (/@scrypted/prebuffer-mixin/main.nodejs.js:1:84651)
    at async /@scrypted/prebuffer-mixin/main.nodejs.js:1:74316
[Backyard Stick Up Cam] SIP active rebroadcast clients: 0
[Backyard Stick Up Cam] rebroadcast error Error: RTSP Server expected frame magic but received: TEAR
    at A.handleRecord (/@scrypted/prebuffer-mixin/main.nodejs.js:1:92318)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.parse (/@scrypted/prebuffer-mixin/main.nodejs.js:1:84651)
    at async /@scrypted/prebuffer-mixin/main.nodejs.js:1:74316
uncaughtException Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:917:11)
    at Socket._write (node:net:929:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at t.safeKillFFmpeg (/@scrypted/prebuffer-mixin/main.nodejs.js:1:155534)
    at _ (/@scrypted/prebuffer-mixin/main.nodejs.js:1:73774)
    at /@scrypted/prebuffer-mixin/main.nodejs.js:1:74428 {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
[Backyard Stick Up Cam] ffmpeg exited
[Backyard Stick Up Cam] refreshing media stream in 89923
[Backyard Stick Up Cam] SIP terminating rebroadcast due to inactivity
```

In the app I'm using to view the live stream, if I reload the stream, it comes back again and works for a while, but then eventually the same thing happens again and the same error appears in the log.

For this camera, under "Stream: SIP", I have "Rebroadcast Container" set to "RTSP", and "RTSP Parser" set to "FFmpeg (UDP)", everything else here is set to defaults.

I'm using the following versions:
* Scrypted - 0.5.13
* Scrypted Core - 0.1.83
* Rebroadcast Plugin - 0.9.70
* Ring Plugin - 0.0.92

**Comment by jordanmkoncz** [comment]
@koush just a note that the same issue is still happening after upgrading Scrypted to v0.6.10-2.

**Comment by koush** [comment]
not an issue, just normal teardown noise.

**Comment by jordanmkoncz** [comment]
@koush thanks for looking into this. I've now updated to the latest version of Scrypted and I'm not having this problem anymore, so some recent change to Scrypted has fixed the root problem, whatever it was.
