### ISSUE TITLE
Error registering to Scrypted Cloud and Alexa plugin not working

### ISSUE THREAD

**Issue by psmith3** [koush/scrypted#539]
When trying to determine why my Alexa plugin is not showing the video from my cameras, my investigation revealed another issue when the Scrypted cloud plug attempts to register. I have tried UPNP as well as manual port forwarding and the port forward test is successful. It seems the cloud registration is successful too, but I see the following error in the console for Scrypted Cloud when registering:

```
server version: 0.6.10
plugin version: @scrypted/cloud 0.1.7
########################
1/29/2023, 10:52:30 PM
########################
uncaughtException Error: carrier stream ended before end message received
    at t.Decoder.r (/node_modules/bpmux/index.js:621:29)
    at t.Decoder.emit (node:events:525:35)
    at t.Decoder.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  carrier_done: true
}
uncaughtException Error: carrier stream ended before end message received
    at t.Decoder.r (/node_modules/bpmux/index.js:621:29)
    at t.Decoder.emit (node:events:525:35)
    at t.Decoder.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  carrier_done: true
}
uncaughtException Error: carrier stream ended before end message received
    at t.Decoder.r (/node_modules/bpmux/index.js:621:29)
    at t.Decoder.emit (node:events:525:35)
    at t.Decoder.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  carrier_done: true
}
scrypted server connection ended: 0rhv9znnvvk
registered {
  success: true,
  sender_id: '827888101440',
  registration_id: 'enuLRSuHB6g:APA91bFOZAJXD1iScNTI97Vpfkr1_K7UZN9ov6Rh0y7MD0VatZD1MO-8zonXlXPEUzmyY-OIbaWNltxeMIRErZcvceXq9psSarUR9EmWrh0fY7ZHdiqkxbzm0HYpnqs6tBtnFGLLrEWU',
  upnp_port: 46699,
  ip_address: '173.xxx.xxx.xxx'
}
scrypted server requested a connection: 87k2levo9a7
```

then for Alexa, I see this error:

```
########################
1/29/2023, 10:15:04 PM
########################
request failed due to invalid authorization TypeError: Invalid value "undefined" for header "Authorization"
    at ClientRequest.setHeader (node:_http_outgoing:647:3)
    at new ClientRequest (node:_http_client:284:14)
    at Object.request (node:https:360:10)
    at g._performRequest (/node_modules/follow-redirects/index.js:279:24)
    at new g (/node_modules/follow-redirects/index.js:61:8)
    at Object.request (/node_modules/follow-redirects/index.js:487:14)
    at /node_modules/axios/lib/adapters/http.js:226:25
    at new Promise (<anonymous>)
    at adapter (/node_modules/axios/lib/adapters/http.js:48:10)
    at e.exports (/node_modules/axios/lib/core/dispatchRequest.js:56:44) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
```

Any issue come to mind? Is the Alexa error due to the Scrypted Cloud error?

**Comment by koush** [comment]
did Alexa link successfully? you need to use the Alexa app to do that.

**Comment by psmith3** [comment]
Alexa has always appeared to link, but no video will work. I am able to get motion alerts from my cameras, but no video. The error message finally stopped on the Scrypted Cloud registration. On the Alexa integration, I have used the web browser on the desktop to authenticate it. I’ll try removing it and try again with the mobile app to see what happens there.

On Jan 29, 2023, at 9:21 PM, Koushik Dutta ***@***.***> wrote:

﻿

did Alexa link successfully? you need to use the Alexa app to do that.

**Comment by koush** [comment]
What camera model?

**Comment by psmith3** [comment]
Amcrest
IP8M-2796EW-AI

On Jan 30, 2023, at 12:03 AM, Koushik Dutta ***@***.***> wrote:

﻿

What camera model?

**Comment by koush** [comment]
fixed, different regions had different servers

**Comment by VikramGoswami10** [comment]
guys , can anyone guide me step by step how to use scrypted for alexa and google home . i have already added scrypted addon . Now i dont know how to use scrypted . 
My main goal is to automate Doorbell where when doorbell is pressed , video will stream in alexa display or google nest display .

**Comment by VikramGoswami10** [comment]
when sign in with scrypted cloud it is saying : "Scrypted Cloud has not been set up for this email address. Install the Cloud plugin on the Scrypted Server and log in " 
solutions  ?
