### ISSUE TITLE
Snapshot URL issue

### ISSUE THREAD

**Issue by merv2k4** [koush/scrypted#541]
Hi,

I am having an issue with using a Snapshot URL from my Hikvision camera.

Can I run snapshot without using rebroadcast plugin? Cos I am running scrypted as an image in Docker. And it will use considerable resources in the system if i run this with the rebroadcast plugin.

When I am using either links on my browser, i can see the still image of the camera.

1) http://192.168.100.30/ISAPI/streaming/channels/101/picture?auth='xxxxxxxxxxxxxxxxxxxxxxxxxxxx'

2) http://user:pass@192.168.100.30/ISAPI/streaming/channels/101/picture

But when i put into scrypted, it fails to load with this error when i am accessing from homekit.
I can view the live stream in homekit without any issues or delays.

[B1 CP RSTP] snapshot error TypeError: Cannot read properties of undefined (reading 'interfaces')
    at DeviceProxyHandler.interfaces [as get] (/server/node_modules/@scrypted/server/src/plugin/system.ts:54:78)
    at snapshotThrottle (/src/types/camera/camera-snapshot.ts:23:20)
    at snapshotAll (/src/types/camera/camera-snapshot.ts:50:13)
    at Object.handleSnapshotRequest (/src/types/camera/camera-snapshot.ts:76:13)
    at /external/HAP-NodeJS/src/lib/controller/CameraController.ts:651:23
    at new Promise (<anonymous>)
    at Ct.handleSnapshotRequest (/external/HAP-NodeJS/src/lib/controller/CameraController.ts:635:12)
    at $r.handleResource (/external/HAP-NodeJS/src/lib/Accessory.ts:1826:18)
    at Oe.emit (node:events:513:28)
    at Oe.emit (node:domain:489:12)

[B1 CP RSTP] snapshot error TypeError: Cannot read properties of undefined (reading 'interfaces')
    at DeviceProxyHandler.interfaces [as get] (/server/node_modules/@scrypted/server/src/plugin/system.ts:54:78)
    at snapshotThrottle (/src/types/camera/camera-snapshot.ts:23:20)
    at snapshotAll (/src/types/camera/camera-snapshot.ts:50:13)
    at Object.handleSnapshotRequest (/src/types/camera/camera-snapshot.ts:76:13)
    at /external/HAP-NodeJS/src/lib/controller/CameraController.ts:651:23
    at new Promise (<anonymous>)
    at Ct.handleSnapshotRequest (/external/HAP-NodeJS/src/lib/controller/CameraController.ts:635:12)
    at $r.handleResource (/external/HAP-NodeJS/src/lib/Accessory.ts:1826:18)
    at Oe.emit (node:events:513:28)
    at Oe.emit (node:domain:489:12)

[B1 CP RSTP] snapshot error TypeError: Cannot read properties of undefined (reading 'interfaces')
    at DeviceProxyHandler.interfaces [as get] (/server/node_modules/@scrypted/server/src/plugin/system.ts:54:78)
    at snapshotThrottle (/src/types/camera/camera-snapshot.ts:23:20)
    at snapshotAll (/src/types/camera/camera-snapshot.ts:50:13)
    at Object.handleSnapshotRequest (/src/types/camera/camera-snapshot.ts:76:13)
    at /external/HAP-NodeJS/src/lib/controller/CameraController.ts:651:23
    at new Promise (<anonymous>)
    at Ct.handleSnapshotRequest (/external/HAP-NodeJS/src/lib/controller/CameraController.ts:635:12)
    at $r.handleResource (/external/HAP-NodeJS/src/lib/Accessory.ts:1826:18)
    at Oe.emit (node:events:513:28)
    at Oe.emit (node:domain:489:12)

[B1 CP RSTP] snapshot error TypeError: Cannot read properties of undefined (reading 'interfaces')
    at DeviceProxyHandler.interfaces [as get] (/server/node_modules/@scrypted/server/src/plugin/system.ts:54:78)
    at snapshotThrottle (/src/types/camera/camera-snapshot.ts:23:20)
    at snapshotAll (/src/types/camera/camera-snapshot.ts:50:13)
    at Object.handleSnapshotRequest (/src/types/camera/camera-snapshot.ts:76:13)
    at /external/HAP-NodeJS/src/lib/controller/CameraController.ts:651:23
    at new Promise (<anonymous>)
    at Ct.handleSnapshotRequest (/external/HAP-NodeJS/src/lib/controller/CameraController.ts:635:12)
    at $r.handleResource (/external/HAP-NodeJS/src/lib/Accessory.ts:1826:18)
    at Oe.emit (node:events:513:28)
    at Oe.emit (node:domain:489:12)

Thank you

**Comment by merv2k4** [comment]
![image](https://user-images.githubusercontent.com/78693962/215503366-d18c1d6b-76ed-4d4d-9680-dcc93aabbec4.png)
![image](https://user-images.githubusercontent.com/78693962/215503452-daa322d7-57b8-4ec1-98e6-8be89c20f44c.png)

**Comment by koush** [comment]
please use discord for a support forum. GitHub is for bugs.
