### ISSUE TITLE
error after update Image Reader skipping converter due to error Error: Could not parse MIME type string "undefined" 

### ISSUE THREAD

**Issue by GravityRZ** [koush/scrypted#631]
after updating the container to version 0.7.9 my log is flooded with this message

```
Image Reader skipping converter due to error Error: Could not parse MIME type string "undefined" 
 at new MIMEType (/server/node_modules/whatwg-mimetype/lib/mime-type.js:15:13)
at MediaManagerImpl.convert (/server/node_modules/@scrypted/server/dist/plugin/media.js:326:47)
at MediaManagerImpl.convertMediaObjectToBuffer (/server/node_modules/@scrypted/server/dist/plugin/media.js:236:41
 at z.startPrebufferSession (/@scrypted/prebuffer-mixin/main.nodejs.js:1:119441
```
i am using the rtsp plugin with a hikvision camera

**Comment by brianschrameck** [comment]
Have you tried restarting the Snapshot plugin? That worked for me.

**Comment by GravityRZ** [comment]
ok. will try tomorrow. i restarted the complete container after the update  so if this is the case it should restart. maybee it is the order of restarting

**Comment by koush** [comment]
https://github.com/koush/scrypted/commit/b27156742830e6bdbe11e52ab697d3a04d2188aa
