### ISSUE TITLE
Missing module on install

### ISSUE THREAD

**Issue by jandreaucodes** [koush/scrypted#64]
When trying to run scrypted for the first time, I'm hitting an error that I can't find a solution for online:

`Alfred@Pennyworth .scrypted % npx -y scrypted serve
cwd /Users/Alfred/.scrypted
Starting scrypted main...
running /usr/local/Cellar/node/17.0.1/bin/node --expose-gc node_modules/@scrypted/server/dist/scrypted-main.js
#######################################################
Scrypted Server (Local)   : https://localhost:10443/
Scrypted Server (Remote)  : https://fe80::184b:7fc9:f420:3147:10443/
Scrypted Server (Remote)  : https://192.168.5.145:10443/
Scrypted Server (Remote)  : https://fe80::1411:fd0f:1395:22f9:10443/
Scrypted Server (Remote)  : https://192.168.4.36:10443/
Version:       : 0.0.81
#######################################################
Chrome Users: You may need to type "thisisunsafe" into
              the window to bypass the warning. There
              may be no button to continue, type the
              letters "thisisunsafe" and it will proceed.
#######################################################
Scrypted insecure http service port: 10080
Ports can be changed with environment variables.
https: $SCRYPTED_SECURE_PORT
http : $SCRYPTED_INSECURE_PORT
#######################################################
i Scrypted Core loading @scrypted/core
i Scrypted Core pid 44018
starting plugin @scrypted/core 0.0.146
native dependencies (outdated) @koush/wrtc
failure loadZip Error: npm installation failed with exit code 1
    at installOptionalDependencies (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/plugin/plugin-npm-dependencies.ts:48:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.beforeLoadZip (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/plugin/plugin-host.ts:628:17)
    at Object.loadZip (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:409:17)
    at RpcPeer.handleMessage (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/rpc.ts:426:37)
a Scrypted Core Plugin failed to load. Console for more information.
alert {
  timestamp: 1638194866622,
  level: 'a',
  message: 'Plugin failed to load. Console for more information.',
  path: '/device/1',
  title: 'Scrypted Core'
}
e Scrypted Core plugin load error Error: host:@scrypted/core: npm installation failed with exit code 1
plugin load error @scrypted/core:host
Error: npm installation failed with exit code 1
    at installOptionalDependencies (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/plugin/plugin-npm-dependencies.ts:48:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.beforeLoadZip (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/plugin/plugin-host.ts:628:17)
    at Object.loadZip (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:409:17)
    at RpcPeer.handleMessage (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/rpc.ts:426:37) {
  cause: undefined
}
plugin failed to load @scrypted/core:host
Error: npm installation failed with exit code 1
    at installOptionalDependencies (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/plugin/plugin-npm-dependencies.ts:48:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.beforeLoadZip (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/plugin/plugin-host.ts:628:17)
    at Object.loadZip (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:409:17)
    at RpcPeer.handleMessage (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/rpc.ts:426:37) {
  cause: undefined
}
unhandled rejection of RPC Result @scrypted/core:host
Error: npm installation failed with exit code 1
    at installOptionalDependencies (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/plugin/plugin-npm-dependencies.ts:48:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.beforeLoadZip (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/plugin/plugin-host.ts:628:17)
    at Object.loadZip (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:409:17)
    at RpcPeer.handleMessage (/Users/Alfred/.scrypted/node_modules/@scrypted/server/src/rpc.ts:426:37) {
  cause: undefined
}`

How can I get around this to get the script working?

**Comment by koush** [comment]
m1 or intel Mac?

**Comment by koush** [comment]
I'm guessing you're not on node 16 if you hit this error.

**Comment by jandreaucodes** [comment]
Intel Mac. 

I had apparently upgraded to Node 17, somehow. I'll downgrade to 16 and try again.

**Comment by koush** [comment]
Yeah, the prebuilt node-webrtc is only for node 16.
