### ISSUE TITLE
Missing library in Python codecs package

### ISSUE THREAD

**Issue by matjahs** [koush/scrypted#643]
I am getting the following error from the `@scrypted/python-codecs` plugin (v0.1.14).

To add some context: I am running Scrypted as a Home Assistant add-on. I saw this error occur on the previous version. Have just now updated to 0.7.17 where it still occurs.

```log
server version: 0.7.17
plugin version: @scrypted/python-codecs 0.1.14
########################
3/20/2023, 7:51:16 AM
########################
python version: python3.9
requirements.txt (up to date)
# plugin
PyGObject>=3.30.4; sys_platform != 'win32'
# libav doesnt work on arm7
av>=10.0.0; sys_platform != 'linux' or platform_machine == 'x86_64' or platform_machine == 'aarch64'
pyvips

site-packages: /data/scrypted_data/plugins/@scrypted/python-codecs/python3.9-Linux-aarch64/lib/python3.9/site-packages
plugin failed to start
Traceback (most recent call last):
  File "/data/scrypted_data/plugins/@scrypted/python-codecs/python3.9-Linux-aarch64/lib/python3.9/site-packages/pyvips/__init__.py", line 19, in <module>
    import _libvips
ModuleNotFoundError: No module named '_libvips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/server/node_modules/@scrypted/server/python/plugin_remote.py", line 514, in loadZip
    from main import create_scrypted_plugin  # type: ignore
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/scrypted_data/plugins/@scrypted/python-codecs/zip/1-0f4fabd8a5ea4b2d47bdf4308be32370.zip/main.py", line 5, in <module>
    import gstreamer
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._boostrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/scrypted_data/plugins/@scrypted/python-codecs/zip/1-0f4fabd8a5ea4b2d47bdf4308be32370.zip/gstreamer.py", line 6, in <module>
    import pyvips
  File "/data/scrypted_data/plugins/@scrypted/python-codecs/python3.9-Linux-aarch64/lib/python3.9/site-packages/pyvips/__init__.py", line 71, in <module>
    vips_lib = ffi.dlopen(_vips_libname)
  File "/data/scrypted_data/plugins/@scrypted/python-codecs/python3.9-Linux-aarch64/lib/python3.9/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/data/scrypted_data/plugins/@scrypted/python-codecs/python3.9-Linux-aarch64/lib/python3.9/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/data/scrypted_data/plugins/@scrypted/python-codecs/python3.9-Linux-aarch64/lib/python3.9/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libvips.so.42'
```

**Comment by Spont09** [comment]
Same Problem here
