### ISSUE TITLE
ONVIF SOAP error

### ISSUE THREAD

**Issue by dsully** [koush/scrypted#655]
I have a Doorbird hooked up to Scrypted's ONVIF plugin, and am getting these errors in syslog.

Any thoughts? Or how to debug further? Thanks 

```
Mar 24 09:07:49 server scrypted[76152]: createSubscription error Error: Wrong ONVIF SOAP response
Mar 24 09:07:49 server scrypted[76152]:     at cb (/node_modules/onvif/lib/utils.js:74:15)
Mar 24 09:07:49 server scrypted[76152]:     at o.<anonymous> (/node_modules/xml2js/lib/parser.js:304:18)
Mar 24 09:07:49 server scrypted[76152]:     at o.emit (node:events:513:28)
Mar 24 09:07:49 server scrypted[76152]:     at o.emit (node:domain:489:12)
Mar 24 09:07:49 server scrypted[76152]:     at o.event [as onclosetag] (/node_modules/xml2js/lib/parser.js:262:26)
Mar 24 09:07:49 server scrypted[76152]:     at emit (/node_modules/sax/lib/sax.js:624:29)
Mar 24 09:07:49 server scrypted[76152]:     at emitNode (/node_modules/sax/lib/sax.js:629:5)
Mar 24 09:07:49 server scrypted[76152]:     at closeTag (/node_modules/sax/lib/sax.js:889:7)
Mar 24 09:07:49 server scrypted[76152]:     at o.write (/node_modules/sax/lib/sax.js:1436:13)
Mar 24 09:07:49 server scrypted[76152]:     at o.parseString (/node_modules/xml2js/lib/parser.js:323:31)
Mar 24 09:07:49 server scrypted[76152]:
Mar 24 09:07:49 server scrypted[76152]: listen loop connection failed, restarting listener. Wrong ONVIF SOAP response
Mar 24 09:07:49 server scrypted[76152]:
Mar 24 09:07:59 server scrypted[76152]: Camera does not show WSPullPoint support, but trying anyway <?xml version="1.0" encoding="UTF-8"?>#015
Mar 24 09:07:59 server scrypted[76152]: <SOAP-ENV:Envelope                            ><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><tds:GetCapabilitiesResponse><tds:
Capabilities><tt:Device><tt:XAddr>http://10.0.0.30/onvif/device_service</tt:XAddr><tt:Network><tt:IPFilter>false</tt:IPFilter><tt:ZeroConfiguration>false</tt:
ZeroConfiguration><tt:IPVersion6>false</tt:IPVersion6><tt:DynDNS>false</tt:DynDNS></tt:Network><tt:System><tt:DiscoveryResolve>true</tt:DiscoveryResolve><tt:
DiscoveryBye>true</tt:DiscoveryBye><tt:RemoteDiscovery>false</tt:RemoteDiscovery><tt:SystemBackup>false</tt:SystemBackup><tt:SystemLogging>false</tt:SystemLogging><tt:
FirmwareUpgrade>false</tt:FirmwareUpgrade><tt:SupportedVersions><tt:Major>2</tt:Major><tt:Minor>10</tt:Minor></tt:SupportedVersions></tt:System><tt:IO><tt:
InputConnectors>1</tt:InputConnectors><tt:RelayOutputs>1</tt:RelayOutputs></tt:IO><tt:Security><tt:TLS1.1>true</tt:TLS1.1><tt:TLS1.2>false</tt:TLS1.2><tt:
OnboardKeyGeneration>true</tt:OnboardKeyGeneration><tt:AccessPolicyConfig>true</tt:AccessPolicyConfig><tt:X.509Token>false</tt:X.509Token><tt:SAMLToken>false</tt:
SAMLToken><tt:KerberosToken>false</tt:KerberosToken><tt:RELToken>false</tt:RELToken><tt:Extension><tt:TLS1.0>true</tt:TLS1.0></tt:Extension></tt:Security></tt:Device><tt:
Media><tt:XAddr>http://10.0.0.30/onvif/Media</tt:XAddr><tt:StreamingCapabilities><tt:RTPMulticast>false</tt:RTPMulticast><tt:RTP_TCP>false</tt:RTP_TCP><tt:
RTP_RTSP_TCP>true</tt:RTP_RTSP_TCP></tt:StreamingCapabilities><tt:Extension><tt:ProfileCapabilities><tt:MaximumNumberOfProfiles>1</tt:MaximumNumberOfProfiles></tt:
ProfileCapabilities></tt:Extension></tt:Media></tds:Capabilities></tds:GetCapabilitiesResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>
Mar 24 09:07:59 server scrypted[76152]:
Mar 24 09:07:59 server scrypted[76152]:
```

**Comment by koush** [comment]
it doesn't support ONVIF motion events.

**Comment by dsully** [comment]
Ok, what’s the best way to silence that logging error then?

**Comment by koush** [comment]
Use the RTSP plugin and manually enter the rtsp urls per stream (there might be 2). I'll see about removing not using the event listener if it doesn't exist.

**Comment by dsully** [comment]
Thanks - that worked.

**Comment by ThisIsQasim** [comment]
Is it possible the plugin is updated to work without motion detection if the camera doesn't support motion events over onvif but still automatically extract the rtsp and snapshot urls via onvif?
