### ISSUE TITLE
ObjectDetector 110+ breaks on ARM Ubuntu

### ISSUE THREAD

**Issue by midnyt** [koush/scrypted#671]
Hi, I've been running Scrypted for a while and it's been great however issues popped up with my RTSP cameras last week and I think I narrowed down the issue. If I use ObjectDetector plugin version 109 things work fine but 110 and later give the following error:

linux arm64 #76-Ubuntu SMP Fri Mar 17 17:25:19 UTC 2023
server version: 0.7.37
plugin version: @scrypted/objectdetector 0.0.119
########################
3/29/2023, 2:03:32 AM
########################
native dependencies (up to date). sharp
plugin failed to start Error: Cannot find module '/server/volume/plugins/@scrypted/objectdetector/node18-linux-arm64-node18-linux-arm64/node_modules/sharp'
Require stack:
- /server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js
- /server/node_modules/@scrypted/server/dist/scrypted-plugin-main.js
- /server/node_modules/@scrypted/server/dist/scrypted-main-exports.js
- /server/node_modules/@scrypted/server/dist/scrypted-main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at params.require (/server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js:179:28)
    at 5200 (/@scrypted/objectdetector/main.nodejs.js:1:84109)
    at r (/@scrypted/objectdetector/main.nodejs.js:1:84455)
    at 1159 (/@scrypted/objectdetector/main.nodejs.js:1:63031)
    at r (/@scrypted/objectdetector/main.nodejs.js:1:84455)
    at 6360 (/@scrypted/objectdetector/main.nodejs.js:1:66832) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-plugin-main.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-main-exports.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-main.js'
  ]
}
plugin start/fork failed Error: Cannot find module '/server/volume/plugins/@scrypted/objectdetector/node18-linux-arm64-node18-linux-arm64/node_modules/sharp'
Require stack:
- /server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js
- /server/node_modules/@scrypted/server/dist/scrypted-plugin-main.js
- /server/node_modules/@scrypted/server/dist/scrypted-main-exports.js
- /server/node_modules/@scrypted/server/dist/scrypted-main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at params.require (/server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js:179:28)
    at 5200 (/@scrypted/objectdetector/main.nodejs.js:1:84109)
    at r (/@scrypted/objectdetector/main.nodejs.js:1:84455)
    at 1159 (/@scrypted/objectdetector/main.nodejs.js:1:63031)
    at r (/@scrypted/objectdetector/main.nodejs.js:1:84455)
    at 6360 (/@scrypted/objectdetector/main.nodejs.js:1:66832) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-plugin-main.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-main-exports.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-main.js'
  ]
}

**Comment by koush** [comment]
is this docker or local install?

**Comment by midnyt** [comment]
Docker Sent from my iPhoneOn Mar 28, 2023, at 7:30 PM, Koushik Dutta ***@***.***> wrote:﻿
is this docker or local install?

**Comment by koush** [comment]
run on the host machine and get me output:

`file docker`

**Comment by midnyt** [comment]
```
root@docker:~# file docker
docker: cannot open `docker' (No such file or directory)

root@docker:~# which docker
/snap/bin/docker

root@docker:~# file /snap/bin/docker
/snap/bin/docker: symbolic link to /usr/bin/snap

root@docker:~# ls -l /snap/bin/docker
lrwxrwxrwx 1 root root 13 Mar  7 16:52 /snap/bin/docker -> /usr/bin/snap

root@docker:~# file /usr/bin/snap
/usr/bin/snap: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, Go BuildID=8mNqx8E9JpT0uHPw93Yi/XPcPvDcx_5MYgf4aQ5XK/pwFWkyWEgIi-84C-5Ewm/_l1FN2KO1rgdmbHvg2XE, stripped

root@docker:~# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.5.0)

Server:
 Containers: 29
  Running: 24
  Paused: 0
  Stopped: 5
 Images: 30
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: 
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-69-generic
 Operating System: Ubuntu Core 18
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 5.779GiB
 Name: docker
 ID: OYXQ:HCZB:XIV4:YMZL:C2QP:RNRI:VIJ7:2G6F:TU5X:5C7B:JR54:GRJS
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

root@docker:~# docker ps | grep scrypt
dd66a2619bf1   koush/scrypted:latest                  "/init /bin/sh -c 'n…"   56 seconds ago   Up 55 seconds                                                                                                                     scrypted

```

**Comment by koush** [comment]
delete/reinstall video analysis. if that doesn't work, I'd  try updating your docker.

```
koush@Koushik-Ubuntu:~$ docker --version
Docker version 23.0.1, build a5ee5b1
```

Might be an arm arch issue. using 32bit

**Comment by midnyt** [comment]
I've deleted and reinstalled the Video Analysis plugin a few times and get the same result. Also tried OpenCV vs Pam Diff. I even tried different versions of Scrypted including the beta and versions from a month ago. I also completely removed the Scrypted container and started fresh. The only thing that worked was manually installing version 109 of the Video Analysis (Object Detector) plugin. Even going to 110 or the latest 119 breaks it.

As for the host, I've done all the apt updates and upgrades. Do you have a recommended way to manually upgrade the docker version on Ubuntu 22.04.2 LTS Arch64?

<img width="637" alt="Screenshot 2023-03-29 at 8 42 47 AM" src="https://user-images.githubusercontent.com/13856801/228594079-ba079fbf-54e2-4e5d-85cd-97820367963c.png">

**Comment by koush** [comment]
Check this please:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/73924/228618622-d3014ad5-34c5-4794-8687-21c8cf8058d3.png">


I am testing on docker on an arm64 machine and VideoAnalysis instals fine.
The only reason I could think it may be na issue is if there's some weird arch issue happening here.

**Comment by midnyt** [comment]
```
root@scrypted:/server# node
Welcome to Node.js v18.15.0.
Type ".help" for more information.
> os.arch()
'arm64'
> os.machine()
'aarch64'
> 
```

**Comment by koush** [comment]
which docker image are you on? just the one installed by the script?

**Comment by midnyt** [comment]
I'm on the latest version of the Scrypted image 0.7.38. I've tried the beta and various other "full", "lite" and "thin" versions including going all the way back to scrypted:18-bullseye-full-v0.6.26. I'm using Portainer and Watchtower to deploy and maintain my containers. Everything has been working great for several months (maybe close to a year?) until a week or so ago

**Comment by koush** [comment]
ok sharp is optional now. try again.

**Comment by koush** [comment]
something is wrong with the permissions on your volume.

**Comment by koush** [comment]
try deleting `~/.scrypted/volume/plugins/@scrypted/objectdetector` on the host. then reload plugin.

**Comment by midnyt** [comment]
i deleted the directory and reloaded the plugin but got the same error

what's the correct way to install the older version of the plugin from CLI? I installed it on the host and can see it with "npm list" but not seeing the other plug-ins and not seeing it in the application - must be something i'm missing

**Comment by koush** [comment]
update your docker

**Comment by koush** [comment]
never mind, it looks up to date now that I see

**Comment by midnyt** [comment]
ya i already updated the scrypted docker image - just don't know how to downgrade the video analysis plugin to 109 now that it doesn't show up in the GUI drop down list

**Comment by midnyt** [comment]
Strange. Using the internal volume instead of my external drive where I keep all my configs made it work again. Don't know why it's been working fine that way for so long or why the plugin before 110 works

**Comment by koush** [comment]
what are the filesystem types of your drives

**Comment by midnyt** [comment]
the internal OS drive where it's running now is EXT4 in an Ubuntu VM under Parallels
the external mount is APFS but presented to Ubuntu using Parallels Tools as PRL_FS
