### ISSUE TITLE
Video Analysis Plugin Gives RPCResultError on Windows

### ISSUE THREAD

**Issue by AaqilRazak** [koush/scrypted#688]
I currently have a Windows machine running Scrypted through Docker. I use the Ring and Amcrest plugins (Lorex NVR) to pull the RTSP streams and integrate them into HomeKit. Even though I use the main stream for video analysis, I haven't had any issues with any of the cameras with OpenCV.

Since 3/26 or so motion detection stopped working on the Amcrest plugin cameras, causing no events to be recorded at all even though the Ring plugin continues to work well.

I assumed this may have been an iOS16.4 error but after power cycling many times, I noticed the Ring camera still works so it couldn't be a hub issue.

When checking the console, I see the following regarding an RPCResultError: Device is unavailable 55 (mixin undefined):

```
[Rebroadcast Plugin]: Stream 1 prebuffer session started
[Rebroadcast Plugin]: prebuffer session starting
[Rebroadcast Plugin]: stream Stream 2 will be rebroadcast on demand.
[Video Analysis Plugin]: decoder: Libav
[Rebroadcast Plugin]: rebroadcast mode: rtsp
stream url rtsp://192.168.4.100:554/cam/realmonitor?channel=5&subtype=0
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://192.168.4.100:554/cam/realmonitor?channel=5&subtype=0 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 401 Unauthorized
[Rebroadcast Plugin]: Server: Rtsp Server/2.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: WWW-Authenticate: Basic realm="DahuaRtsp"
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://192.168.4.100:554/cam/realmonitor?channel=5&subtype=0 RTSP/1.0
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic YWRtaW46MjU0NTc4
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: Server: Rtsp Server/2.0
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: Public: OPTIONS,DESCRIBE,SETUP,PLAY,PAUSE,TEARDOWN,SET_PARAMETER,GET_PARAMETER,ANNOUNCE
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://192.168.4.100:554/cam/realmonitor?channel=5&subtype=0 RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic YWRtaW46MjU0NTc4
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: Server: Rtsp Server/2.0
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: Content-Base: rtsp://192.168.4.100:554/cam/realmonitor?channel=5&subtype=0
[Rebroadcast Plugin]: Content-Type: application/sdp
[Rebroadcast Plugin]: Content-Length: 335
[Rebroadcast Plugin]: Cache-Control: must-revalidate
[Rebroadcast Plugin]: x-Accept-Dynamic-Rate: 1
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: sdp v=0
[Rebroadcast Plugin]: o=- 2257149998 2257149998 IN IP4 0.0.0.0
[Rebroadcast Plugin]: s=RTSP Session/2.0
[Rebroadcast Plugin]: c=IN IP4 0.0.0.0
[Rebroadcast Plugin]: t=0 0
[Rebroadcast Plugin]: a=control:*
[Rebroadcast Plugin]: a=range:npt=now-
[Rebroadcast Plugin]: a=packetization-supported:DH
[Rebroadcast Plugin]: m=video 0 RTP/AVP 96
[Rebroadcast Plugin]: a=control:trackID=0
[Rebroadcast Plugin]: a=rtpmap:96 H264/90000
[Rebroadcast Plugin]: a=fmtp:96 packetization-mode=1;profile-level-id=4D0028;sprop-parameter-sets=J00AKI1oB4AiXlQ=,KO4EYg==
[Rebroadcast Plugin]: a=recvonly
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  SETUP rtsp://192.168.4.100:554/cam/realmonitor?channel=5&subtype=0&channel=5&subtype=0/trackID=0 RTSP/1.0
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=0-1
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic YWRtaW46MjU0NTc4
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: Server: Rtsp Server/2.0
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: Session: 5211832026018;timeout=60
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=0-1;ssrc=CD9F1B36
[Rebroadcast Plugin]: x-dynamic-rate: 1
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: parsed sdp sps { width: 1920, height: 1080 }
[Rebroadcast Plugin]: No audio stream detected.
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  PLAY rtsp://192.168.4.100:554/cam/realmonitor?channel=5&subtype=0&channel=5&subtype=0 RTSP/1.0
[Rebroadcast Plugin]: Range: npt=0.000-
[Rebroadcast Plugin]: CSeq: 4
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Authorization: Basic YWRtaW46MjU0NTc4
[Rebroadcast Plugin]: Session: 5211832026018
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: prebuffer session started
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: Server: Rtsp Server/2.0
[Rebroadcast Plugin]: CSeq: 4
[Rebroadcast Plugin]: Session: 5211832026018
[Rebroadcast Plugin]: RTP-Info: url=trackID=0;seq=19550;rtptime=177186708;ssrc=cd9f1b36
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: sending prebuffer 4000
[Video Analysis Plugin]: video pipeline ended with error RPCResultError: device is unavailable 55 (mixin undefined)
[Video Analysis Plugin]:     at PluginDeviceProxyHandler.applyMixin (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\plugin\plugin-device.ts:375:23)
[Video Analysis Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Video Analysis Plugin]:     at RpcPeer.handleMessageInternal (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\rpc.ts:734:37)
[Video Analysis Plugin]: host:@scrypted/objectdetector {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: video pipeline analysis ended, dps: 0
[Rebroadcast Plugin]: parsed bitstream sps { width: 1920, height: 1080 }
[HomeKit]: HomeKit Connection ::ffff:192.168.4.57
[Rebroadcast Plugin]: sending prebuffer 6000
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 1
[Rebroadcast Plugin]: Found sync frame in rtsp prebuffer.
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 0
[Rebroadcast Plugin]: client connection timed out
[WebRTC Plugin]: signalingState have-remote-offer
[WebRTC Plugin]: iceGatheringState gathering
[WebRTC Plugin]: signalingState stable
[WebRTC Plugin]: connectionState connecting
[WebRTC Plugin]: iceConnectionState checking
[WebRTC Plugin]: waiting ice connected
[WebRTC Plugin]: iceConnectionState completed
[WebRTC Plugin]: iceGatheringState complete
[WebRTC Plugin]: iceConnectionState connected
[WebRTC Plugin]: connectionState connected
[WebRTC Plugin]: ice transport { ipv4: true, isPrivate: true, destinationId: '192.168.4.202' }
[WebRTC Plugin]: Connection is local network: true
[WebRTC Plugin]: done waiting ice connected
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 1743.8
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 1
[Rebroadcast Plugin]: Found sync frame in rtsp prebuffer.
[WebRTC Plugin]: signalingState closed
[WebRTC Plugin]: connectionState closed
[WebRTC Plugin]: iceConnectionState closed
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 0
[RTC Connection Bridge]: Client Stream Profile {
[RTC Connection Bridge]:   transcodeBaseline: false,
[RTC Connection Bridge]:   sessionSupportsH264High: true,
[RTC Connection Bridge]:   maximumCompatibilityMode: false,
[RTC Connection Bridge]:   userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15',
[RTC Connection Bridge]:   capabilities: {
[RTC Connection Bridge]:     audio: { codecs: [Array], headerExtensions: [Array] },
[RTC Connection Bridge]:     video: { codecs: [Array], headerExtensions: [Array] }
[RTC Connection Bridge]:   },
[RTC Connection Bridge]:   screen: { devicePixelRatio: 2, width: 3008, height: 1692 }
[RTC Connection Bridge]: }
[RTC Connection Bridge]: rtsp/tcp h264
[RTC Connection Bridge]: a/v h264 undefined found h264 undefined
[RTC Connection Bridge]: bypassing ffmpeg, perfect codecs
[RTC Connection Bridge]: first video packet 494
[Video Analysis Plugin]: decoder: Libav
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 2004.75
[Video Analysis Plugin]: video pipeline ended with error RPCResultError: device is unavailable 55 (mixin undefined)
[Video Analysis Plugin]:     at PluginDeviceProxyHandler.applyMixin (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\plugin\plugin-device.ts:375:23)
[Video Analysis Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Video Analysis Plugin]:     at RpcPeer.handleMessageInternal (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\rpc.ts:734:37)
[Video Analysis Plugin]: host:@scrypted/objectdetector {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: video pipeline analysis ended, dps: 0
[Rebroadcast Plugin]: client connection timed out
[Video Analysis Plugin]: decoder: Libav
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 2000.25
[Video Analysis Plugin]: video pipeline ended with error RPCResultError: device is unavailable 55 (mixin undefined)
[Video Analysis Plugin]:     at PluginDeviceProxyHandler.applyMixin (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\plugin\plugin-device.ts:375:23)
[Video Analysis Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Video Analysis Plugin]:     at RpcPeer.handleMessageInternal (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\rpc.ts:734:37)
[Video Analysis Plugin]: host:@scrypted/objectdetector {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: video pipeline analysis ended, dps: 0
[Rebroadcast Plugin]: client connection timed out
[Video Analysis Plugin]: decoder: Libav
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 1990
[Video Analysis Plugin]: video pipeline ended with error RPCResultError: device is unavailable 55 (mixin undefined)
[Video Analysis Plugin]:     at PluginDeviceProxyHandler.applyMixin (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\plugin\plugin-device.ts:375:23)
[Video Analysis Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Video Analysis Plugin]:     at RpcPeer.handleMessageInternal (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\rpc.ts:734:37)
[Video Analysis Plugin]: host:@scrypted/objectdetector {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: video pipeline analysis ended, dps: 0
[Rebroadcast Plugin]: client connection timed out
[Video Analysis Plugin]: decoder: Libav
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 1994.75
[Video Analysis Plugin]: video pipeline ended with error RPCResultError: device is unavailable 55 (mixin undefined)
[Video Analysis Plugin]:     at PluginDeviceProxyHandler.applyMixin (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\plugin\plugin-device.ts:375:23)
[Video Analysis Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Video Analysis Plugin]:     at RpcPeer.handleMessageInternal (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\rpc.ts:734:37)
[Video Analysis Plugin]: host:@scrypted/objectdetector {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: video pipeline analysis ended, dps: 0
[Rebroadcast Plugin]: client connection timed out
listen loop 5m idle timeout, destroying listener.
listen loop closed, restarting listener.
[Video Analysis Plugin]: decoder: Libav
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 1999.75
[Video Analysis Plugin]: video pipeline ended with error RPCResultError: device is unavailable 55 (mixin undefined)
[Video Analysis Plugin]:     at PluginDeviceProxyHandler.applyMixin (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\plugin\plugin-device.ts:375:23)
[Video Analysis Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Video Analysis Plugin]:     at RpcPeer.handleMessageInternal (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\rpc.ts:734:37)
[Video Analysis Plugin]: host:@scrypted/objectdetector {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: video pipeline analysis ended, dps: 0
[Rebroadcast Plugin]: client connection timed out
[Video Analysis Plugin]: decoder: Libav
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 2007.5
[Video Analysis Plugin]: video pipeline ended with error RPCResultError: device is unavailable 55 (mixin undefined)
[Video Analysis Plugin]:     at PluginDeviceProxyHandler.applyMixin (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\plugin\plugin-device.ts:375:23)
[Video Analysis Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Video Analysis Plugin]:     at RpcPeer.handleMessageInternal (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\rpc.ts:734:37)
[Video Analysis Plugin]: host:@scrypted/objectdetector {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: video pipeline analysis ended, dps: 0
[Rebroadcast Plugin]: client connection timed out
[Video Analysis Plugin]: decoder: Libav
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 1994.75
[Video Analysis Plugin]: video pipeline ended with error RPCResultError: device is unavailable 55 (mixin undefined)
[Video Analysis Plugin]:     at PluginDeviceProxyHandler.applyMixin (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\plugin\plugin-device.ts:375:23)
[Video Analysis Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Video Analysis Plugin]:     at RpcPeer.handleMessageInternal (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\rpc.ts:734:37)
[Video Analysis Plugin]: host:@scrypted/objectdetector {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: video pipeline analysis ended, dps: 0
[Rebroadcast Plugin]: client connection timed out
[Video Analysis Plugin]: decoder: Libav
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 2000.25
[Video Analysis Plugin]: video pipeline ended with error RPCResultError: device is unavailable 55 (mixin undefined)
[Video Analysis Plugin]:     at PluginDeviceProxyHandler.applyMixin (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\plugin\plugin-device.ts:375:23)
[Video Analysis Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Video Analysis Plugin]:     at RpcPeer.handleMessageInternal (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\rpc.ts:734:37)
[Video Analysis Plugin]: host:@scrypted/objectdetector {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: video pipeline analysis ended, dps: 0
[Rebroadcast Plugin]: client connection timed out
[Video Analysis Plugin]: decoder: Libav
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 1999.75
[Video Analysis Plugin]: video pipeline ended with error RPCResultError: device is unavailable 55 (mixin undefined)
[Video Analysis Plugin]:     at PluginDeviceProxyHandler.applyMixin (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\plugin\plugin-device.ts:375:23)
[Video Analysis Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Video Analysis Plugin]:     at RpcPeer.handleMessageInternal (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\rpc.ts:734:37)
[Video Analysis Plugin]: host:@scrypted/objectdetector {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: video pipeline analysis ended, dps: 0
[Rebroadcast Plugin]: client connection timed out
listen loop 5m idle timeout, destroying listener.
listen loop closed, restarting listener.
[Video Analysis Plugin]: decoder: Libav
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 1996.75
[Video Analysis Plugin]: video pipeline ended with error RPCResultError: device is unavailable 55 (mixin undefined)
[Video Analysis Plugin]:     at PluginDeviceProxyHandler.applyMixin (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\plugin\plugin-device.ts:375:23)
[Video Analysis Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Video Analysis Plugin]:     at RpcPeer.handleMessageInternal (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\rpc.ts:734:37)
[Video Analysis Plugin]: host:@scrypted/objectdetector {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: video pipeline analysis ended, dps: 0
[Rebroadcast Plugin]: client connection timed out
[Video Analysis Plugin]: decoder: Libav
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 1992.5
[Video Analysis Plugin]: video pipeline ended with error RPCResultError: device is unavailable 55 (mixin undefined)
[Video Analysis Plugin]:     at PluginDeviceProxyHandler.applyMixin (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\plugin\plugin-device.ts:375:23)
[Video Analysis Plugin]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Video Analysis Plugin]:     at RpcPeer.handleMessageInternal (C:\Users\Aaqil\.scrypted\node_modules\@scrypted\server\src\rpc.ts:734:37)
[Video Analysis Plugin]: host:@scrypted/objectdetector {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: video pipeline analysis ended, dps: 0
```

The events log looks like:
<img width="526" alt="Screenshot 2023-04-03 at 9 11 24 PM" src="https://user-images.githubusercontent.com/33614846/229668744-e88db952-1cfa-4051-a34a-0b54de954268.png">

Not sure where to go to troubleshoot this issue... Would you have any pointers for me on reenabling OpenCV detection? The same issue persists with PAM-DIFF.

I had to delete parts of the console log to fit into the comment. I'd be willing to send the entire log some other way.

Appreciate all the work and time you've put into the project!

**Comment by koush** [comment]
you dont need opencv with the amcrest plugin.

**Comment by AaqilRazak** [comment]
> you dont need opencv with the amcrest plugin.

Understood, however the Lorex NVR (rebranded Amcrest NVR) does not support webhooks or SMTP for motion detection events. I don’t seem to see the plugin automatically using motion detection some other way although the NVR does have working motion detection on its own. I’d be willing to explore other solutions besides OpenCV, but it did seem to be the best option which worked flawlessly up until recently.

The only thing that I can find for what’s wrong is the RPCResultError in the VideoAnalysis plugin. Not sure if it could be something like a Windows or NodeJS version issue but its definitely beyond my scope.

**Comment by koush** [comment]
What is device 55? can you navigate to that in the management console

**Comment by AaqilRazak** [comment]
Apologies, not sure I know where to find that.

When navigating into Scrypted Management Console -> Devices, I see a total of 37 devices:
![image](https://user-images.githubusercontent.com/33614846/229925066-099dfdb8-f852-4d64-9fd1-69e877c5ebcb.jpeg)

Issue persists through reinstall of plugins too so I’m not sure where it’s pulling 55 from.

**Comment by koush** [comment]
Go to any device, and change the url number in the url to 55.

**Comment by AaqilRazak** [comment]
Looks like Device 55 is Libav

![image](https://user-images.githubusercontent.com/33614846/229929369-a9152df4-d871-4b09-8147-1a234e0ca6b9.jpeg)

**Comment by AaqilRazak** [comment]
Just out of curiosity before starting a new install of Scrypted, I tried to delete Libav and reinstall PythonCodecs.

I'm not sure the ramifications of doing so, but I almost instantly noticed motion detection back to working although it seems to be extremely sensitive. HKSV is back to working  but VideoAnalysis plugin is nowhere to be found in the console log.

Hopefully this doesn't have any negative consequences. Thanks for all the help, Koush!

**Comment by kapabel** [comment]
Hello! I have the same error. I don’t get any recordings in HomeKit anymore.  I get device 31 is unavailable which is in my case Gstreamer.
