### ISSUE TITLE
no 2FA from scrytpted ring plugin

### ISSUE THREAD

**Issue by imcl75** [koush/scrypted#701]
no 2fa code generated when trying to login to ring via scripted plugin.  This issue has been associated with the issues also seen by homebridge ring plugin authentication issue (which is now rersolved).

**Comment by Ricox1975** [comment]
same here

**Comment by koush** [comment]
was also resolved in scrypted. https://github.com/koush/scrypted/commit/2dd4721b7f35218c6d998c738d65f847aab6d748

**Comment by imcl75** [comment]
Plug in fails to load 

linux x64 #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2
server version: 0.7.46
plugin version: @scrypted/ring 0.0.109
########################
08/04/2023, 03:03:52
########################
node modules /home/innes/.scrypted/volume/plugins/@scrypted/ring/node18-linux-x64
native dependencies (outdated) got socket.io-client
Removing old dependencies: /home/innes/.scrypted/volume/plugins/@scrypted/ring/node18-linux-x64-20230329
plugin start/fork failed Error: EACCES: permission denied, mkdir '/home/innes/.scrypted/volume/plugins/@scrypted/ring/node18-linux-x64'
    at Object.mkdirSync (node:fs:1396:3)
    at mkdirpNativeSync (/home/innes/.scrypted/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/home/innes/.scrypted/node_modules/mkdirp/index.js:21:7)
    at installOptionalDependencies (/home/innes/.scrypted/node_modules/@scrypted/server/dist/plugin/plugin-npm-dependencies.js:55:26)
    at Object.onLoadZip (/home/innes/.scrypted/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js:218:77)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.loadZip (/home/innes/.scrypted/node_modules/@scrypted/server/dist/plugin/plugin-remote.js:584:28)
    at async RpcPeer.handleMessageInternal (/home/innes/.scrypted/node_modules/@scrypted/server/dist/rpc.js:583:37) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/home/innes/.scrypted/volume/plugins/@scrypted/ring/node18-linux-x64'
}
