### ISSUE TITLE
Rotated video doesn't work

### ISSUE THREAD

**Issue by martijndierckx** [koush/scrypted#730]
I have multiple Dahua cameras from which I use the second substream (h264 720p) to show up in Homekit via Scrypted. 
I use go2rtc to proxy the videostreams towards multiple consumers (nx witness, frigate & scrypted).

Which works perfectly fine ... however Scrypted/Homekit don't like the rotated video stream. (The other camera's work flawlessly including HKSV)
Once I rotate the video, the stream still works in VLC/ffprobe and it shows up in Scrypted. But live viewing nor recording work in Homekit.

Go2RTC config:
```
- frontdoor-720p:          rtsp://REDACTED:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
- frontdoor-720p-rotated:  ffmpeg:frontdoor-720p#video=h264#raw=-g 40 -r 10 -keyint_min 40#audio=copy#raw=-vf transpose=2
```

Dahua settings:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/3973630/230347386-d3609289-d28d-42df-9709-ccf212119fb7.png">

Scrypted stream info:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/3973630/230347688-ee2216e6-3697-4ce2-aec1-5d72f0a5b032.png">

Scrypted logs when trying to view the live feed (Homekit eventually shows 'camera not responding'):
```
[HomeKit]: HomeKit Connection 192.168.10.91
[Rebroadcast Plugin]: sending prebuffer 6000
[HomeKit]: destination address 192.168.10.91 51858 57593
[HomeKit]: using address override 192.168.10.210
[HomeKit]: source address 192.168.10.210 51992 40349
[HomeKit]: handleStreamRequest {
[HomeKit]:   sessionID: '92f209e8-6d73-41f6-9ceb-50c39be44632',
[HomeKit]:   type: 'start',
[HomeKit]:   video: {
[HomeKit]:     codec: 0,
[HomeKit]:     profile: 1,
[HomeKit]:     level: 2,
[HomeKit]:     packetizationMode: 0,
[HomeKit]:     cvoId: undefined,
[HomeKit]:     width: 1280,
[HomeKit]:     height: 720,
[HomeKit]:     fps: 30,
[HomeKit]:     pt: 99,
[HomeKit]:     ssrc: 3877866067,
[HomeKit]:     max_bit_rate: 299,
[HomeKit]:     rtcp_interval: 0.5,
[HomeKit]:     mtu: 1378
[HomeKit]:   },
[HomeKit]:   audio: {
[HomeKit]:     codec: 'OPUS',
[HomeKit]:     channel: 1,
[HomeKit]:     bit_rate: 0,
[HomeKit]:     sample_rate: 24,
[HomeKit]:     packet_time: 20,
[HomeKit]:     pt: 110,
[HomeKit]:     ssrc: 3796550495,
[HomeKit]:     max_bit_rate: 24,
[HomeKit]:     rtcp_interval: 5,
[HomeKit]:     comfort_pt: 13,
[HomeKit]:     comfortNoiseEnabled: false
[HomeKit]:   }
[HomeKit]: }
[HomeKit]: { isLowBandwidth: false, isWatch: false, destination: 'local' }
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 129.15384615384616
[HomeKit]: { tool: undefined, rtpSender: 'Default' }
[HomeKit]: rtsp/tcp h264
[HomeKit]: a/v h264 opus found h264 undefined
[HomeKit]: rtsp/tcp aac
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 1
[HomeKit]: -hide_banner -i rtsp:[REDACTED] -acodec libopus -application lowdelay -frame_duration 20 -flags +global_header -ar 24k -b:a 24k -bufsize 96k -ac 1 -payload_type 110 -ssrc 985381 -dn -sn -vn -f rtp rtp://127.0.0.1:33433?pkt_size=400 -sdp_file pipe:4
[HomeKit]: received first video packet
[HomeKit]: scanning for idr start found: 1
[HomeKit]: [rtsp @ 0x698bcc0] method SETUP failed: 461 Unsupported Transport
[HomeKit]: scanning for idr start found: 1 28 24 7 8
[HomeKit]: idr start found: 28 5
[HomeKit]: Input #0, rtsp, from 'rtsp://127.0.0.1:36493':
[HomeKit]:   Metadata:
[HomeKit]:     title           : go2rtc/1.3.1
[HomeKit]:   Duration: N/A, start: 0.000000, bitrate: N/A
[HomeKit]:   Stream #0:0: Audio: aac (LC), 8000 Hz, mono, fltp
[HomeKit]: Stream mapping:
[HomeKit]:   Stream #0:0 -> #0:0 (aac (native) -> opus (libopus))
[HomeKit]: Press [q] to stop, [?] for help
[HomeKit]: Output #0, rtp, to 'rtp://127.0.0.1:33433?pkt_size=400':
[HomeKit]:   Metadata:
[HomeKit]:     title           : go2rtc/1.3.1
[HomeKit]:     encoder         : Lavf59.16.100
[HomeKit]:   Stream #0:0: Audio: opus, 24000 Hz, mono, flt, 24 kb/s
[HomeKit]:     Metadata:
[HomeKit]:       encoder         : Lavc59.18.100 libopus
[HomeKit]: video/audio detected, discarding further input
[HomeKit]: received first audio packet
[Video Analysis Plugin]: Gstreamer + PAM Diff Motion Detection
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 128.23076923076923
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 2
[Video Analysis Plugin]: detection areas [ 0.8571744537353516 ]
[HomeKit]: Voordeur recording session starting ::ffff:192.168.10.51 {
[HomeKit]:   mediaContainerConfiguration: { prebufferLength: 4000, type: 0, fragmentLength: 4000 },
[HomeKit]:   videoCodec: {
[HomeKit]:     type: 0,
[HomeKit]:     bitrate: 2000,
[HomeKit]:     level: 2,
[HomeKit]:     profile: 0,
[HomeKit]:     resolution: [ 1920, 1080, 30 ],
[HomeKit]:     iFrameInterval: 4000
[HomeKit]:   },
[HomeKit]:   audioCodec: {
[HomeKit]:     audioChannels: 1,
[HomeKit]:     type: 0,
[HomeKit]:     samplerate: 3,
[HomeKit]:     bitrateMode: 0,
[HomeKit]:     bitrate: 64
[HomeKit]:   }
[HomeKit]: }
[Rebroadcast Plugin]: Selected stream Stream 1
[Rebroadcast Plugin]: sending prebuffer 10000
[HomeKit]: motion recording starting
[HomeKit]: -hide_banner -analyzeduration 0 -probesize 2606453 -reorder_queue_size 0 -rtsp_transport tcp -f rtsp -i rtsp:[REDACTED] -vcodec copy -acodec copy -bsf:a aac_adtstoasc -movflags frag_keyframe+empty_moov+default_base_moof+skip_sidx+skip_trailer -f mp4 pipe:3
[HomeKit]: motion recording started
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 3
[HomeKit]: Input #0, rtsp, from 'rtsp://127.0.0.1:41163/3a058b69032dd9a5':
[HomeKit]:   Metadata:
[HomeKit]:     title           : go2rtc/1.3.1
[HomeKit]:   Duration: N/A, start: 0.000000, bitrate: N/A
[HomeKit]:   Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 720x1280 [SAR 1:1 DAR 9:16],
[HomeKit]: 10 fps, 10 tbr, 90k tbn
[HomeKit]:   Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
[HomeKit]: motion fragment #1 sent. size: 1292
[HomeKit]: Output #0, mp4, to 'pipe:3':
[HomeKit]:   Metadata:
[HomeKit]:     title           : go2rtc/1.3.1
[HomeKit]:     encoder         : Lavf59.16.100
[HomeKit]:   Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 720x1280 [SAR 1:1 DAR 9:16], q=2-31, 10 fps, 10 tbr, 90k tbn
[HomeKit]:   Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 8000 Hz, mono, fltp
[HomeKit]: Stream mapping:
[HomeKit]:   Stream #0:0 -> #0:0 (copy)
[HomeKit]:   Stream #0:1 -> #0:1 (copy)
[HomeKit]: Press [q] to stop, [?] for help
[HomeKit]: frame=    0 fps=0.0 q=-1.0 size=       1kB time=00:00:00.00 bitrate=N/A speed=   0x
[HomeKit]: video/audio detected, discarding further input
[HomeKit]: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'pipe:3':
[HomeKit]:   Metadata:
[HomeKit]:     major_brand     : iso5
[HomeKit]:     minor_version   : 512
[HomeKit]:     compatible_brands: iso5iso6mp41
[HomeKit]:     title           : go2rtc/1.3.1
[HomeKit]:     encoder         : Lavf59.16.100
[HomeKit]: Duration: 00:00:09.22, start: 0.000000, bitrate: N/A
[HomeKit]:   Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 720x1280 [SAR 1:1 DAR 9:16], 1132 kb/s, 5.43 fps, 10 tbr, 90k tbn (default)
[HomeKit]:     Metadata:
[HomeKit]:       handler_name    : VideoHandler
[HomeKit]:       vendor_id       : [0][0][0][0]
[HomeKit]:   Stream #0:1[0x2](und): Audio: aac (mp4a / 0x6134706D), 8000 Hz, mono, fltp, 16 kb/s (default)
[HomeKit]:     Metadata:
[HomeKit]:       handler_name    : SoundHandler
[HomeKit]:       vendor_id       : [0][0][0][0]
[HomeKit]: Output #0, h264, to 'pipe:4':
[HomeKit]:   Metadata:
[HomeKit]:     major_brand     : iso5
[HomeKit]:     minor_version   : 512
[HomeKit]:     compatible_brands: iso5iso6mp41
[HomeKit]:     title           : go2rtc/1.3.1
[HomeKit]:     encoder         : Lavf59.16.100
[HomeKit]:   Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 720x1280 [SAR 1:1 DAR 9:16], q=2-31, 1132 kb/s, 5.43 fps, 10 tbr, 10 tbn (default)
[HomeKit]:     Metadata:
[HomeKit]:       handler_name    : VideoHandler
[HomeKit]:       vendor_id       : [0][0][0][0]
[HomeKit]: Stream mapping:
[HomeKit]:   Stream #0:0 -> #0:0 (copy)
[HomeKit]: frame=    1 fps=0.0 q=-1.0 size=     514kB time=00:00:00.10 bitrate=42135.8kbits/s speed=5e+04x
[HomeKit]: video/audio detected, discarding further input
[HomeKit]: ffmpeg exited
[HomeKit]: skipping mp4 fragment: non idr frame 1
[Rebroadcast Plugin]: rebroadcast error Error: rtsp socket closed
[Rebroadcast Plugin]:     at Socket.<anonymous> (/@scrypted/prebuffer-mixin/main.nodejs.js:1:146290)
[Rebroadcast Plugin]:     at Socket.emit (node:events:513:28)
[Rebroadcast Plugin]:     at Socket.emit (node:domain:489:12)
[Rebroadcast Plugin]:     at TCP.<anonymous> (node:net:322:12)
[Rebroadcast Plugin]: prebuffer session ended
[Rebroadcast Plugin]: restarting prebuffer session in 5 seconds
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 2
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 1
[Rebroadcast Plugin]: Stream 1 active rebroadcast clients: 0
[HomeKit]: streaming session killed, duration: 13s
[HomeKit]: motion fragment #2 sent. size: 1050272
[HomeKit]: ffmpeg exited
[HomeKit]: ffmpeg exited
[HomeKit]: motion recording completed Error
[Video Analysis Plugin]: Video Analysis ended with error [Traceback (most recent call last):
[Video Analysis Plugin]:   File "/server/node_modules/@scrypted/server/python/rpc.py", line 449, in handleMessage
[Video Analysis Plugin]:     value = await maybe_await(invoke(*args))
[Video Analysis Plugin]:   File "/server/node_modules/@scrypted/server/python/rpc.py", line 24, in maybe_await
[Video Analysis Plugin]:     return await value
[Video Analysis Plugin]:   File "/server/node_modules/@scrypted/server/python/rpc.py", line 80, in __anext__
[Video Analysis Plugin]:     return await RpcProxyMethod(self, self.__dict__[RpcPeer.PROPERTY_PROXY_PROPERTIES]['Symbol(Symbol.asyncIterator)']['next'])()
[Video Analysis Plugin]:   File "/server/node_modules/@scrypted/server/python/rpc.py", line 509, in createPendingResult
[Video Analysis Plugin]:     return await future
[Video Analysis Plugin]: rpc.RPCResultError: (None, 'peer was killed')
[Video Analysis Plugin]: 
[Video Analysis Plugin]: cluster-server:@scrypted/pam-diff
[Video Analysis Plugin]: cluster-server:@scrypted/objectdetector] {
[Video Analysis Plugin]:   cause: undefined
[Video Analysis Plugin]: }
[Video Analysis Plugin]: Video Analysis motion detection ended.
[Rebroadcast Plugin]: Stream 1 prebuffer session started
[Rebroadcast Plugin]: prebuffer session starting
[Rebroadcast Plugin]: rebroadcast mode: rtsp
stream url rtsp://REDACTED:8554/frontdoor-720p-rotated
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  OPTIONS rtsp://REDACTED:8554/frontdoor-720p-rotated RTSP/1.0
[Rebroadcast Plugin]: CSeq: 0
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: Public: OPTIONS, SETUP, TEARDOWN, DESCRIBE, PLAY, PAUSE, ANNOUNCE, RECORD
[Rebroadcast Plugin]: Cseq: 0
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  DESCRIBE rtsp://REDACTED:8554/frontdoor-720p-rotated RTSP/1.0
[Rebroadcast Plugin]: Accept: application/sdp
[Rebroadcast Plugin]: CSeq: 1
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: Content-Type: application/sdp
[Rebroadcast Plugin]: Cseq: 1
[Rebroadcast Plugin]: Content-Length: 402
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: sdp v=0
[Rebroadcast Plugin]: o=- 1 1 IN IP4 0.0.0.0
[Rebroadcast Plugin]: s=go2rtc/1.3.1
[Rebroadcast Plugin]: c=IN IP4 0.0.0.0
[Rebroadcast Plugin]: t=0 0
[Rebroadcast Plugin]: m=video 0 RTP/AVP 96
[Rebroadcast Plugin]: a=rtpmap:96 H264/90000
[Rebroadcast Plugin]: a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAKay0BaBQ2AtwEBAUAAADAAQAAAMAUjxgyoA=,aO8Pyw==; profile-level-id=640029
[Rebroadcast Plugin]: m=audio 0 RTP/AVP 97
[Rebroadcast Plugin]: a=rtpmap:97 MPEG4-GENERIC/8000
[Rebroadcast Plugin]: a=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1588
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  SETUP rtsp://REDACTED:8554/frontdoor-720p-rotated RTSP/1.0
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=0-1
[Rebroadcast Plugin]: CSeq: 2
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=0-1
[Rebroadcast Plugin]: Cseq: 2
[Rebroadcast Plugin]: Session: 1
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  SETUP rtsp://REDACTED:8554/frontdoor-720p-rotated RTSP/1.0
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=2-3
[Rebroadcast Plugin]: CSeq: 3
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Session: 1
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: Transport: RTP/AVP/TCP;unicast;interleaved=2-3
[Rebroadcast Plugin]: Cseq: 3
[Rebroadcast Plugin]: Session: 1
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: parsed sdp sps { width: 720, height: 1280 }
[Rebroadcast Plugin]: Detected audio codec is mp4/mpegts compatible. aac
[Rebroadcast Plugin]: rtsp outgoing message
[Rebroadcast Plugin]:  PLAY rtsp://REDACTED:8554/frontdoor-720p-rotated RTSP/1.0
[Rebroadcast Plugin]: Range: npt=0.000-
[Rebroadcast Plugin]: CSeq: 4
[Rebroadcast Plugin]: User-Agent: Scrypted
[Rebroadcast Plugin]: Session: 1
[Rebroadcast Plugin]: 
[Rebroadcast Plugin]: prebuffer session started
[Rebroadcast Plugin]: rtsp incoming message
[Rebroadcast Plugin]:  RTSP/1.0 200 OK
[Rebroadcast Plugin]: Cseq: 4
[Rebroadcast Plugin]: Session: 1
[Rebroadcast Plugin]: 
[HomeKit]: handleStreamRequest { sessionID: '92f209e8-6d73-41f6-9ceb-50c39be44632', type: 'stop' }
[Rebroadcast Plugin]: sending prebuffer 6000
```

There's 2 things I'm noticing:
- The keyframe interval seems off (it shows up correctly when using the original non-rotated 720p feed)
- Homekit is requesting 1280x720 instead of 720x1280

I've tried [a couple things](https://github.com/AlexxIT/go2rtc/issues/337#issuecomment-1506467577) to correct the keyframe interval. But nothing seems to change the weird number I'm seeing in Scrypted.
I've tried resetting/repairing the homekit camera accessory.

If I enable transcoding in Scrypted, it does work. But the delay increases and the quality gets REALLY poor. So I don't want to go that route.

Any advice/ideas?

**Comment by koush** [comment]
Hksv expects video to be a certain aspect ratio and bitrate. There are no suggestions beyond what is in the troubleshooting guide.
