### ISSUE TITLE
Errors in logs after deleting camera

### ISSUE THREAD

**Issue by briangunderson** [koush/scrypted#744]
I deleted (2) of my unsupported Amcrest cameras and re-added them from scratch as generic RTSP devices in order to stop the Amcrest plugin from repeatedly failing to query the camera's HTTP API endpoint since it doesn't exist on these cheap models. After doing so, I'm seeing an internal error in logs that seems to indicate that the deleted devices may have some vestigial references that weren't scrubbed by the deletion process. 

```
engine.io plugin error RPCResultError: device 30 does not exist
    at PluginComponent.getDeviceInfo (/server/node_modules/@scrypted/server/src/services/plugin.ts:81:19)
    at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:738:66)
    at RpcPeer.handleMessage (/server/node_modules/@scrypted/server/src/rpc.ts:683:18)
    at ChildProcess.<anonymous> (/server/node_modules/@scrypted/server/src/plugin/runtime/node-fork-worker.ts:45:22)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
host:@scrypted/core
@scrypted/core:host {
  cause: undefined
}
```

**Comment by koush** [comment]
That's a browser page (engine.io) querying an old device. The server itself fine, but browser is on hanging onto something old. Browser logs are dumped into the plugin console too, but maybe shouldn't be.

**Comment by briangunderson** [comment]
Ok, thanks for letting me know! Makes perfect sense.
