### ISSUE TITLE
Python Codecs will not load in macOS install, "Failed to build pycairo"

### ISSUE THREAD

**Issue by jlg89** [koush/scrypted#748]
Followed the Wiki instructions to install Scrypted on macOS 12.6.5. It runs, RTSP camera is working, but I can't get Python Codecs to load, so motion detection isn't working.

```
darwin x64 Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64
server version: 0.7.84
plugin version: @scrypted/python-codecs 0.1.35
########################
4/20/2023, 3:12:51 PM
########################
python version: python3.9
python prefix: /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64
Removing old dependencies: /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64
requirements.txt (outdated)
# needed by libav to_ndarray
numpy>=1.16.2

# gobject instrospection for gstreamer.
PyGObject>=3.30.4; sys_platform != 'win32'

# libav doesnt work on arm7
av>=10.0.0; sys_platform != 'linux' or platform_machine == 'x86_64' or platform_machine == 'aarch64'

# pyvips is not available on windows, and is preinstalled as part of the installer scripts on
# mac and linux.
pyvips; sys_platform != 'win32'

# in case pyvips fails to load, use a pillow fallback.
# pillow for anything not intel linux, pillow-simd is available on x64 linux
Pillow>=5.4.1; sys_platform != 'linux' or platform_machine != 'x86_64'
pillow-simd; sys_platform == 'linux' and platform_machine == 'x86_64'

Ignoring pillow-simd: markers 'sys_platform == "linux" and platform_machine == "x86_64"' don't match your environment
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.9/site-packages (from -r /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64/requirements.txt (line 2)) (1.24.2)
Collecting PyGObject>=3.30.4 (from -r /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64/requirements.txt (line 5))
  Using cached PyGObject-3.44.1.tar.gz (720 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Collecting setuptools
        Using cached setuptools-67.7.0-py3-none-any.whl (1.1 MB)
      Collecting wheel
        Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
      Collecting pycairo
        Using cached pycairo-1.23.0.tar.gz (344 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: pycairo
        Building wheel for pycairo (pyproject.toml): started
        Building wheel for pycairo (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for pycairo (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [12 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.macosx-12-x86_64-cpython-39
            creating build/lib.macosx-12-x86_64-cpython-39/cairo
            copying cairo/__init__.py -> build/lib.macosx-12-x86_64-cpython-39/cairo
            copying cairo/__init__.pyi -> build/lib.macosx-12-x86_64-cpython-39/cairo
            copying cairo/py.typed -> build/lib.macosx-12-x86_64-cpython-39/cairo
            running build_ext
            'pkg-config' not found.
            Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pycairo
      Failed to build pycairo
      ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
pip install result 1
plugin start/fork failed
Traceback (most recent call last):
  File "/Users/admin/.scrypted/node_modules/@scrypted/server/python/plugin_remote.py", line 380, in loadZip
    return await self.loadZipWrapped(packageJson, zipData, options)
  File "/Users/admin/.scrypted/node_modules/@scrypted/server/python/plugin_remote.py", line 617, in loadZipWrapped
    raise Exception('non-zero result from pip %s' % result)
Exception: non-zero result from pip 1
```

**Comment by jlg89** [comment]
OK...ran "brew install peg-config" and got a little farther...

```
darwin x64 Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64
server version: 0.7.84
plugin version: @scrypted/python-codecs 0.1.35
########################
4/20/2023, 3:22:55 PM
########################
python version: python3.9
python prefix: /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64
Removing old dependencies: /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64
requirements.txt (outdated)
# needed by libav to_ndarray
numpy>=1.16.2

# gobject instrospection for gstreamer.
PyGObject>=3.30.4; sys_platform != 'win32'

# libav doesnt work on arm7
av>=10.0.0; sys_platform != 'linux' or platform_machine == 'x86_64' or platform_machine == 'aarch64'

# pyvips is not available on windows, and is preinstalled as part of the installer scripts on
# mac and linux.
pyvips; sys_platform != 'win32'

# in case pyvips fails to load, use a pillow fallback.
# pillow for anything not intel linux, pillow-simd is available on x64 linux
Pillow>=5.4.1; sys_platform != 'linux' or platform_machine != 'x86_64'
pillow-simd; sys_platform == 'linux' and platform_machine == 'x86_64'

Ignoring pillow-simd: markers 'sys_platform == "linux" and platform_machine == "x86_64"' don't match your environment
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.9/site-packages (from -r /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64/requirements.txt (line 2)) (1.24.2)
Collecting PyGObject>=3.30.4 (from -r /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64/requirements.txt (line 5))
  Using cached PyGObject-3.44.1.tar.gz (720 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting av>=10.0.0 (from -r /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64/requirements.txt (line 8))
  Downloading av-10.0.0-cp39-cp39-macosx_10_9_x86_64.whl (26.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.1/26.1 MB 25.4 MB/s eta 0:00:00
Collecting pyvips (from -r /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64/requirements.txt (line 12))
  Downloading pyvips-2.2.1.tar.gz (633 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 633.6/633.6 kB 19.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting Pillow>=5.4.1 (from -r /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64/requirements.txt (line 16))
  Using cached Pillow-9.5.0-cp39-cp39-macosx_10_10_x86_64.whl (3.4 MB)
Collecting pycairo>=1.16.0 (from PyGObject>=3.30.4->-r /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64/requirements.txt (line 5))
  Using cached pycairo-1.23.0-cp39-cp39-macosx_12_0_x86_64.whl
Collecting cffi>=1.0.0 (from pyvips->-r /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64/requirements.txt (line 12))
  Using cached cffi-1.15.1-cp39-cp39-macosx_10_9_x86_64.whl (179 kB)
Collecting pkgconfig (from pyvips->-r /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64/requirements.txt (line 12))
  Using cached pkgconfig-1.5.5-py3-none-any.whl (6.7 kB)
Collecting pycparser (from cffi>=1.0.0->pyvips->-r /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64/requirements.txt (line 12))
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Building wheels for collected packages: PyGObject, pyvips
  Building wheel for PyGObject (pyproject.toml): started
  Building wheel for PyGObject (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for PyGObject (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-x86_64-cpython-39
      creating build/lib.macosx-12-x86_64-cpython-39/pygtkcompat
      copying pygtkcompat/pygtkcompat.py -> build/lib.macosx-12-x86_64-cpython-39/pygtkcompat
      copying pygtkcompat/__init__.py -> build/lib.macosx-12-x86_64-cpython-39/pygtkcompat
      copying pygtkcompat/generictreemodel.py -> build/lib.macosx-12-x86_64-cpython-39/pygtkcompat
      creating build/lib.macosx-12-x86_64-cpython-39/gi
      copying gi/_signalhelper.py -> build/lib.macosx-12-x86_64-cpython-39/gi
      copying gi/_constants.py -> build/lib.macosx-12-x86_64-cpython-39/gi
      copying gi/pygtkcompat.py -> build/lib.macosx-12-x86_64-cpython-39/gi
      copying gi/_ossighelper.py -> build/lib.macosx-12-x86_64-cpython-39/gi
      copying gi/importer.py -> build/lib.macosx-12-x86_64-cpython-39/gi
      copying gi/_error.py -> build/lib.macosx-12-x86_64-cpython-39/gi
      copying gi/_gtktemplate.py -> build/lib.macosx-12-x86_64-cpython-39/gi
      copying gi/_propertyhelper.py -> build/lib.macosx-12-x86_64-cpython-39/gi
      copying gi/__init__.py -> build/lib.macosx-12-x86_64-cpython-39/gi
      copying gi/types.py -> build/lib.macosx-12-x86_64-cpython-39/gi
      copying gi/docstring.py -> build/lib.macosx-12-x86_64-cpython-39/gi
      copying gi/_option.py -> build/lib.macosx-12-x86_64-cpython-39/gi
      copying gi/module.py -> build/lib.macosx-12-x86_64-cpython-39/gi
      creating build/lib.macosx-12-x86_64-cpython-39/gi/repository
      copying gi/repository/__init__.py -> build/lib.macosx-12-x86_64-cpython-39/gi/repository
      creating build/lib.macosx-12-x86_64-cpython-39/gi/overrides
      copying gi/overrides/GIMarshallingTests.py -> build/lib.macosx-12-x86_64-cpython-39/gi/overrides
      copying gi/overrides/Gdk.py -> build/lib.macosx-12-x86_64-cpython-39/gi/overrides
      copying gi/overrides/Pango.py -> build/lib.macosx-12-x86_64-cpython-39/gi/overrides
      copying gi/overrides/GdkPixbuf.py -> build/lib.macosx-12-x86_64-cpython-39/gi/overrides
      copying gi/overrides/Gtk.py -> build/lib.macosx-12-x86_64-cpython-39/gi/overrides
      copying gi/overrides/__init__.py -> build/lib.macosx-12-x86_64-cpython-39/gi/overrides
      copying gi/overrides/GLib.py -> build/lib.macosx-12-x86_64-cpython-39/gi/overrides
      copying gi/overrides/GObject.py -> build/lib.macosx-12-x86_64-cpython-39/gi/overrides
      copying gi/overrides/Gio.py -> build/lib.macosx-12-x86_64-cpython-39/gi/overrides
      copying gi/overrides/keysyms.py -> build/lib.macosx-12-x86_64-cpython-39/gi/overrides
      running build_ext
      Package gobject-introspection-1.0 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'gobject-introspection-1.0' found
      Command '('pkg-config', '--print-errors', '--exists', 'gobject-introspection-1.0 >= 1.56.0')' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyGObject
  Building wheel for pyvips (setup.py): started
  Building wheel for pyvips (setup.py): finished with status 'done'
  Created wheel for pyvips: filename=pyvips-2.2.1-cp39-cp39-macosx_12_0_x86_64.whl size=85526 sha256=27b95feb6287089022ac08335ea9e23ffd136755289da5c1ebe9ac7a725b478b
  Stored in directory: /Users/admin/Library/Caches/pip/wheels/cf/b8/f5/25f3202da9460cc789c5d232653d384474b3d10d829fa7002a
Successfully built pyvips
Failed to build PyGObject
ERROR: Could not build wheels for PyGObject, which is required to install pyproject.toml-based projects
pip install result 1
plugin start/fork failed
Traceback (most recent call last):
  File "/Users/admin/.scrypted/node_modules/@scrypted/server/python/plugin_remote.py", line 380, in loadZip
    return await self.loadZipWrapped(packageJson, zipData, options)
  File "/Users/admin/.scrypted/node_modules/@scrypted/server/python/plugin_remote.py", line 617, in loadZipWrapped
    raise Exception('non-zero result from pip %s' % result)
Exception: non-zero result from pip 1
```
