### ISSUE TITLE
When installing locally on Raspberry Pi it is stuck in a loop of restarting.

### ISSUE THREAD

**Issue by pyesandcakes** [koush/scrypted#80]
Stuck here:
`Starting scrypted main...
running /usr/bin/node --expose-gc node_modules/@scrypted/server/dist/scrypted-main.js
`
and then it goes away and only says `Service exited. Restarting momentarily.
`

**Comment by koush** [comment]
I need a full log

**Comment by pyesandcakes** [comment]
`npx -y scrypted serve
cwd /home/pi/.scrypted
Starting scrypted main...
running /usr/bin/node --expose-gc node_modules/@scrypted/server/dist/scrypted-main.js
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js
- /home/pi/.scrypted/node_modules/node-pty/lib/index.js
- /home/pi/.scrypted/node_modules/@scrypted/server/dist/runtime.js
- /home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js',
    '/home/pi/.scrypted/node_modules/node-pty/lib/index.js',
    '/home/pi/.scrypted/node_modules/@scrypted/server/dist/runtime.js',
    '/home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js'
  ]
}
/home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: Cannot find module '../build/Release/pty.node'
Require stack:
- /home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js
- /home/pi/.scrypted/node_modules/node-pty/lib/index.js
- /home/pi/.scrypted/node_modules/@scrypted/server/dist/runtime.js
- /home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js',
    '/home/pi/.scrypted/node_modules/node-pty/lib/index.js',
    '/home/pi/.scrypted/node_modules/@scrypted/server/dist/runtime.js',
    '/home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js'
  ]
}
Service exited. Restarting momentarily.

Starting scrypted main...
running /usr/bin/node --expose-gc node_modules/@scrypted/server/dist/scrypted-main.js

innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js
- /home/pi/.scrypted/node_modules/node-pty/lib/index.js
- /home/pi/.scrypted/node_modules/@scrypted/server/dist/runtime.js
- /home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js',
    '/home/pi/.scrypted/node_modules/node-pty/lib/index.js',
    '/home/pi/.scrypted/node_modules/@scrypted/server/dist/runtime.js',
    '/home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js'
  ]
}
/home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: Cannot find module '../build/Release/pty.node'
Require stack:
- /home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js
- /home/pi/.scrypted/node_modules/node-pty/lib/index.js
- /home/pi/.scrypted/node_modules/@scrypted/server/dist/runtime.js
- /home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js',
    '/home/pi/.scrypted/node_modules/node-pty/lib/index.js',
    '/home/pi/.scrypted/node_modules/@scrypted/server/dist/runtime.js',
    '/home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js'
  ]
}
Service exited. Restarting momentarily.
Starting scrypted main...
running /usr/bin/node --expose-gc node_modules/@scrypted/server/dist/scrypted-main.js
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js
- /home/pi/.scrypted/node_modules/node-pty/lib/index.js
- /home/pi/.scrypted/node_modules/@scrypted/server/dist/runtime.js
- /home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js',
    '/home/pi/.scrypted/node_modules/node-pty/lib/index.js',
    '/home/pi/.scrypted/node_modules/@scrypted/server/dist/runtime.js',
    '/home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js'
  ]
}
/home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: Cannot find module '../build/Release/pty.node'
Require stack:
- /home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js
- /home/pi/.scrypted/node_modules/node-pty/lib/index.js
- /home/pi/.scrypted/node_modules/@scrypted/server/dist/runtime.js
- /home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/.scrypted/node_modules/node-pty/lib/unixTerminal.js',
    '/home/pi/.scrypted/node_modules/node-pty/lib/index.js',
    '/home/pi/.scrypted/node_modules/@scrypted/server/dist/runtime.js',
    '/home/pi/.scrypted/node_modules/@scrypted/server/dist/scrypted-main.js'
  ]
}
Service exited. Restarting momentarily.
`

**Comment by koush** [comment]
There's a new 1 liner script to handle installation on a raspberry pi. Please wipe your pi and use that. Or use docker.
