### ISSUE TITLE
Homekit not restarting correctly

### ISSUE THREAD

**Issue by aegjoyce** [koush/scrypted#82]
Local installation on Mac. I'm finding that when Scrypted restarts or when the Homekit plugin is reloaded it often is unable to start the Homekit service with the following error:

```
Starting to advertise 'Scrypted 0406' using bonjour-hap backend!
uncaughtException Error: Service name is already in use on the network
    at o._onProbeComplete (/@scrypted/homekit/main.nodejs.js:2:534217)
    at n.done (/@scrypted/homekit/main.nodejs.js:2:532607)
    at n.onMDNSresponse (/@scrypted/homekit/main.nodejs.js:2:532502)
    at EventEmitter.emit (node:events:390:28)
    at EventEmitter.emit (node:domain:475:12)
    at Socket.<anonymous> (/@scrypted/homekit/main.nodejs.js:2:639521)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at UDP.onMessage (node:dgram:939:8)
```

Restarting the router and then Scrypted fixes it but it's a pain. Previous versions of the Homekit plugin seem to get cached on the network somewhere

**Comment by koush** [comment]
can you try ciao instead of bonjour?

**Comment by aegjoyce** [comment]
Trying it. Seems more stable and possibly a little quicker - thanks
