### ISSUE TITLE
Supervisorfailure when adding repository

### ISSUE THREAD

**Issue by Sebartoo** [koush/scrypted#928]
Hi,

I added the repository to my home assistant OS installation.
In the supervisor log I found the following message:

> 23-07-05 11:50:11 WARNING (SyncWorker_3) [supervisor.store.data] Can't read /data/addons/git/09e60fb6/external/ring-client-api/packages/homebridge-ring/config.schema.json: Invalid Add-on config!. Got {'pluginAlias': 'Ring', 'pluginType': 'platform', 'singular': True, 'customUi': True, 'customUiPath': './lib/homebridge-ui', 'customUiDevServer': 'http://localhost:3000/api/plugins/settings-ui/homebridge-ring', 'headerDisplay': 'See [the wiki](https://github.com/dgreif/ring/wiki/Refresh-Tokens) for details on generating a refresh token', 'accountLinkingHeader': 'Please supply your Ring credentials.  These will be used to contact the Ring servers and generate a unique access token for your acc...

I tried to install the addon and got message "unknown failure, see supervisor logs".

In the logs from the supervisor I got the following messages:

>     await self.sys_run_in_executor(
>  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
>    result = self.fn(*self.args, **self.kwargs)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1015, in fetch
>   res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 854, in _get_fetch_info_from_stderr
>    proc.wait(stderr=stderr_text)
>  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 604, in wait
>    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
>git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
>  cmdline: git fetch -v --update-shallow --depth=1 -- origin
>  stderr: 'fatal: unable to access 'https://github.com/home-assistant/addons/': Could not resolve host: github.com'
>The above exception was the direct cause of the following exception:
>Traceback (most recent call last):
>  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 156, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 176, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
[31m23-07-05 12:00:55 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-220833' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreGitError()>[0m
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 134, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1015, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 854, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 604, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/hassio-addons/repository/': Could not resolve host: github.com'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 156, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 176, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
[31m23-07-05 12:00:55 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-220832' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreGitError()>[0m
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 134, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1015, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 854, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 604, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/esphome/home-assistant-addon/': Could not resolve host: github.com'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 156, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 176, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
[31m23-07-05 12:00:55 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-220831' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreJobError("'GitRepo.pull' blocked from execution, no supervisor internet connection")>[0m
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 116, in wrapper
    raise self.on_condition(error_msg, _LOGGER.warning) from None
supervisor.exceptions.StoreJobError: 'GitRepo.pull' blocked from execution, no supervisor internet connection

**Comment by Sebartoo** [comment]
the installation was apparently nevertheless successful
