### ISSUE TITLE
error: google-device-access

### ISSUE THREAD

**Issue by RuntyCascade** [koush/scrypted#94]
followed instructions in [https://github.com/koush/scrypted/tree/main/plugins/google-device-access](url)
added the client id, secret id and project id and console stating this:

`starting plugin @scrypted/google-device-access 0.0.43
token error SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at GoogleSmartDeviceAccess.loadToken (/src/main.ts:390:59)
    at GoogleSmartDeviceAccess.authGet (/src/main.ts:436:20)
    at GoogleSmartDeviceAccess.apply (/src/main.ts:289:37)
    at invokeFunc (/node_modules/lodash/debounce.js:95:19)
    at leadingEdge (/node_modules/lodash/debounce.js:105:22)
    at GoogleSmartDeviceAccess.refreshThrottled (/node_modules/lodash/debounce.js:172:16)
    at GoogleSmartDeviceAccess.refresh (/src/main.ts:410:21)
    at GoogleSmartDeviceAccess.discoverDevices (/src/main.ts:460:35)
    at new GoogleSmartDeviceAccess (/src/main.ts:298:14)
plugin successfully loaded`

when logging in, i am able to set permissions of nest devices in account, click next, then it asks to choose account again (scrypted.app), choose account, says it isnt verified, choose "go to scrypted.app", asks me if i want to give access to scrypted.app, i click continue, then asks me to "sign in to your remotely access your scrypted management console", i choose "sign in with google", choose the same google account for the third time, then the next screen just says "Not Registered".

**Comment by koush** [comment]
screenshots please

**Comment by koush** [comment]
You might need to install and log into Scrypted Cloud first. Can you set up that plugin and then try again? I might have left that step off.

**Comment by RuntyCascade** [comment]
> You might need to install and log into Scrypted Cloud first. Can you set up that plugin and then try again? I might have left that step off.

that looks like it fixed the error. it returned me to home.scrypted.app, and my nest devices are now showing up in the "devices" tab.

now how do i add these cameras to homekit and use with HKSV?
