### ISSUE TITLE
Error get snaphot

### ISSUE THREAD

**Issue by aleksandrdobrynin** [koush/scrypted#942]
Hi. The camera (I FEEL) is connected via ONVIF (there are no other options) and does not automatically update the snapshot in Home.
At the same time, the video plays without problems. Please help me.

Log:

createSubscription error Error: ONVIF SOAP Fault: Optional Action Not Implemented
    at cb (/node_modules/onvif/lib/utils.js:101:13)
    at o.<anonymous> (/node_modules/xml2js/lib/parser.js:304:18)
    at o.emit (node:events:513:28)
    at o.emit (node:domain:489:12)
    at o.event [as onclosetag] (/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/node_modules/sax/lib/sax.js:624:29)
    at emitNode (/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/node_modules/sax/lib/sax.js:889:7)
    at o.write (/node_modules/sax/lib/sax.js:1436:13)
    at o.parseString (/node_modules/xml2js/lib/parser.js:323:31)
listen loop connection failed, restarting listener. ONVIF SOAP Fault: Optional Action Not Implemented
[HomeKit]: HomeKit Connection 192.168.252.166
[HomeKit]: snapshot error RPCResultError: socket hang up
[HomeKit]:     at connResetException (node:internal/errors:717:14)
[HomeKit]:     at Socket.socketOnEnd (node:_http_client:526:23)
[HomeKit]:     at Socket.emit (node:events:525:35)
[HomeKit]:     at Socket.emit (node:domain:489:12)
[HomeKit]:     at endReadableNT (node:internal/streams/readable:1359:12)
[HomeKit]:     at processTicksAndRejections (node:internal/process/task_queues:82:21)
[HomeKit]: @scrypted/onvif:host
[HomeKit]: host:@scrypted/homekit {
[HomeKit]:   cause: undefined
[HomeKit]: }
[HomeKit]: cam-ptz encountered an error while retrieving a new snapshot. Consider installing the Snapshot Plugin to show the most recent snapshot. origin:/#/component/plugin/install/@scrypted/snapshot}

**Comment by koush** [comment]
your camera doesn't support snapshots. use snapshot plugin with pre buffer.
