### ISSUE TITLE
Python Codecs TypeError: unsupported operand type(s)

### ISSUE THREAD

**Issue by jlg89** [koush/scrypted#995]
```
darwin x64 Darwin Kernel Version 21.6.0: Thu Jul  6 22:18:26 PDT 2023; root:xnu-8020.240.18.702.13~1/RELEASE_X86_64
server version: 0.41.0
plugin version: @scrypted/python-codecs 0.1.77
########################
8/3/2023, 10:28:20 AM
########################
python version: python3.9
python prefix: /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64
requirements.txt (up to date)
# needed by libav to_ndarray
numpy>=1.16.2

# gobject instrospection for gstreamer.
PyGObject>=3.30.4; sys_platform != 'win32'

# libav doesnt work on arm7
av>=10.0.0; sys_platform != 'linux' or platform_machine == 'x86_64' or platform_machine == 'aarch64'

# pyvips is not available on windows, and is preinstalled as part of the installer scripts on
# mac and linux.
pyvips; sys_platform != 'win32'

# in case pyvips fails to load, use a pillow fallback.
# pillow for anything not intel linux, pillow-simd is available on x64 linux
Pillow>=5.4.1; sys_platform != 'linux' or platform_machine != 'x86_64'
pillow-simd; sys_platform == 'linux' and platform_machine == 'x86_64'

site-packages: /Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/python3.9-Darwin-x86_64/lib/python3.9/site-packages
plugin start/fork failed
Traceback (most recent call last):
  File "/Users/admin/.scrypted/node_modules/@scrypted/server/python/plugin_remote.py", line 380, in loadZip
    return await self.loadZipWrapped(packageJson, zipData, options)
  File "/Users/admin/.scrypted/node_modules/@scrypted/server/python/plugin_remote.py", line 743, in loadZipWrapped
    from main import create_scrypted_plugin  # type: ignore
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/zip/1-b3521ee352ed897589ef3a27e180b7c6.zip/main.py", line 26, in <module>
    class LibavGenerator(scrypted_sdk.ScryptedDeviceBase, scrypted_sdk.VideoFrameGenerator):
  File "/Users/admin/.scrypted/volume/plugins/@scrypted/python-codecs/zip/1-b3521ee352ed897589ef3a27e180b7c6.zip/main.py", line 27, in LibavGenerator
    def __init__(self, nativeId: str | None, z):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by koush** [comment]
fixed
